### ISSUE TITLE
Justification box options

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#127]
Remove options on the side to include links, photos, etc. in the justification. Also can the tool identify when a link is included in the justification text box and suggest it is included as a reference?

**Comment by byndcivilization** [comment]
This is in reference to the textAngular module as used in the answer justification box. Please remove photo and video embed. @isabellee there isnt really a quick and dirty way to suggest link as reference. Are you sure you want to remove links functionality?

**Comment by byndcivilization** [comment]
@isabellee ive simplified this toolbar. Let know if i simplified it too much.

**Comment by isabellee** [comment]
@byndcivilization yes that's great, thanks!
