### ISSUE TITLE
Access to reference

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#132]
When answering a question and loading references, you can then open up a document for some of them by clicking on the title. However, others, such as interviews or government sources don't have this functionality, so we currently can't easily see what the references include. Can we create this link in the title to the reference for all types?

**Comment by byndcivilization** [comment]
@isabellee do you mean for the supervisor role?

**Comment by isabellee** [comment]
@byndcivilization I was working in the researcher role at the time.

**Comment by byndcivilization** [comment]
This goes against the anonomizing of references request from earlier. You should only be able to see interviewee info if you are a supervisor. Has that change? @ahasemann ?

**Comment by byndcivilization** [comment]
@ahasemann can you clarify? Do want these anonomyzed or not?

**Comment by isabellee** [comment]
From what I gather, you should only be able to see the interviewee if you are the supervisor or the person inputting the interview.

**Comment by ahasemann** [comment]
Sorry, didn't see this one - this seems to be linked to issue #162, i.e. consultants being able to see these details for references they have input themselves. @isabellee Is this correct?

**Comment by isabellee** [comment]
@byndcivilization @ahasemann yes I mentioned the link in issue #162

**Comment by byndcivilization** [comment]
duplicate #162
