### ISSUE TITLE
Heading options in Justification box

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#135]
Can this be removed, or changed to a dropdown with font size options? Consultants are unlikely to know that H1, H2, etc. are headings, and then basically font sizes.

**Comment by byndcivilization** [comment]
There's not an easy way. We might be able to use this textAngular fork but will need a little testing:
https://github.com/mfrye/textAngular

**Comment by byndcivilization** [comment]
I'm setting this to a post release issue as it would be nice but isnt necessary.
