### ISSUE TITLE
Justification box/Comments box

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#136]
Can there be a character limit on these boxes to limit copying/pasting and not proper referencing? Maybe 4,000 characters?

**Comment by byndcivilization** [comment]
@alexander-elgin I believe this is an option in textAngular.

**Comment by alexander-elgin** [comment]
textAngular has an option (`ta-max-text`) to validate the content length only. But I found a way how to restrict the content length not breaking the HTML

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/163

**Comment by isabellee** [comment]
Can this be extended to the Justification box as well. It works for the Comments box but not for the justification box.
