### ISSUE TITLE
Uploading references

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#137]
If you try to upload a reference, eg. a document, by doing the following:
1. Select the document
2. Then don't upload it but REMOVE it
3. Try to select it again from the Computer
Nothing will load. It opens the Computer file to select the document but doesn't give you the option to upload it.
This is valid for all reference types

**Comment by byndcivilization** [comment]
@isabellee i cant recreate this. Can you tell me what browser you're using?

**Comment by isabellee** [comment]
@byndcivilization I'm in Chrome

**Comment by byndcivilization** [comment]
Closing. Please reopen if it comes up again.
