### ISSUE TITLE
Logging future interview dates

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#138]
Consultants currently have the option to log interviews for the whole current month, but not afterwards. Can it be all dates to the current day, rather than until the end of the month?

**Comment by byndcivilization** [comment]
@alexander-elgin this is in the settings for our calendar implementation. Can you set the limits to current day.

**Comment by alexander-elgin** [comment]
Actually any date could be selected. It is fixed in https://github.com/NRGI/rgi-assessment-tool/pull/165
