### ISSUE TITLE
Existing interview options

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#139]
When logging an interview, you can select "New Interviewee" from the top, but the "Existing interviewee" option is not valid. It's not quite clear that for existing interviews, consultants are simply required to select from a drop-down list. Can the list become dependent on them selecting "Existing interviewee"?

**Comment by byndcivilization** [comment]
@isabellee I dont understand this request. The current implementation only allows you to pick from the dropdown if you are in existing interviewee mode? Do you want to change the layout of this dialog?

**Comment by isabellee** [comment]
@byndcivilization I can't remember exactly what it looked like when I made this comment, but as the administrator it looks good now!
