### ISSUE TITLE
References

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#140]
Could you please remove.

**Document**
Remove: editor first name, editor last name, institution, city, date accessed 

**New webpage reference (PDF)**
Remove: date accessed

**Comment by byndcivilization** [comment]
@DianaHartmann Are we sure we want to remove data accessed. Especially for web pages as this is pretty standard across web page citation formats.

**Comment by byndcivilization** [comment]
Ive removed these but want to confirm on everything with @ahasemann. some of these were requested as mandatory in earlier requests.

**Comment by DianaHartmann** [comment]
Ok. Let's keep the date accessed
