### ISSUE TITLE
Delete reference

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#141]
Could be possible delete a reference? In case, the researcher/peer reviewer realise a wrong reference was created

**Comment by byndcivilization** [comment]
@alexander-elgin Reference link should be deleted but not the actual reference (i.e. document, webpage or interviewee). This should only be done by the user who created the reference link.

**Comment by DianaHartmann** [comment]
Sorry, I don't understand what is the difference btw the link and the actual reference?

**Comment by byndcivilization** [comment]
we are storing document information and a citation. The document stuff is its own thing that lives outside of but is referenced by a citation. This may be referenced by other citations. The citation is part of the answer record and references the document. If we delete that document that will mess with other answers.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/161

**Comment by byndcivilization** [comment]
Works. Needs 2 modifications:
- [x] a confirmation dialog box
- [x] Keep deleted reference but set no display flag to true.
