### ISSUE TITLE
Dead link in submission email

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#143]

**Comment by byndcivilization** [comment]
@ahasemann i need more information. Is this when a researcher submits an assessment? who is the reciever? can you post the link that it tries to send you to?

**Comment by ahasemann** [comment]
This is the link: http://rgiassessmenttool.elasticbeanstalk.com/admin/assessment-admin

**Comment by ahasemann** [comment]
Yes, it's whena researcher submits, I get an email to say it's been submitted. I think at some point you had set up yourself, Jim and me as receiver of these emails

**Comment by byndcivilization** [comment]
ahh. will take care of it.
