### ISSUE TITLE
Email sent from Jim's address when a new account is created

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#144]
Would it be possible to create an RGI email address rgi@resourcegovernce.org that would send out these emails? Otherwise the consultants will start emailing Jim. There needs to be a space between the second and third sentence in the email body.

**Comment by byndcivilization** [comment]
@ahasemann the emails are sent from the email of the supervisor who does the action. So if you create a user or assign it will be sent from the address associated with your user account. I had looked into creating a group email but there are issues with that (there isnt a way to autoforward to more than one person, if its an email group instead, i dont think it can send emails back, etc).

**Comment by ahasemann** [comment]
Ok, that's fine then.
