### ISSUE TITLE
References. New Webpage Reference (PDF) please add cancel

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#150]
Once you are adding the information require creating a reference (title, author fist name...) the only option is “create reference”. It would be useful to have "cancel" next to create reference as an option. As it shows for Add a document, where you have 2 choices: “create reference” and “cancel”.

**Comment by DianaHartmann** [comment]
I have discussed this with category with Anna and we want to remove it. As there is not difference between “add document” and “add webpage”. Thus, for references, the choices will be: add document or add interview.

**Comment by byndcivilization** [comment]
@ahasemann and @DianaHartmann The problem is that the required info for webpage and document is different. You really need to maintain the date accessed as that is a standard part of any web citation. I'll look when i get back but i remember there being similar issues across the citation.

**Comment by byndcivilization** [comment]
There's also the issue that if we do get something like an automatic screenshot implemented it will need a separate workflow path to make that work.

**Comment by DianaHartmann** [comment]
Will the automatic screenshot function work? If not, can we make invisible the "add webpage" option?

**Comment by byndcivilization** [comment]
It wont work for the launch but the hope is to get it up sometime in the near future once the basic tool is out in production and weve worked through bugs.

**Comment by ahasemann** [comment]
Can we make it invisible until it is functioning? It is confusing atm

**Comment by byndcivilization** [comment]
button added. moved website snapshot to beta and moved this issue to #49 .

**Comment by HumairaP** [comment]
I have been getting confused with the add document/add webpage option. Can we make the add webpage button invisible for now? It would be much simpler, as there is an option to select webpage in the dropdown box for type of document.

**Comment by HumairaP** [comment]
@byndcivilization

**Comment by byndcivilization** [comment]
Its required for the snapshotting websites which is under development and was requested to be fast tracked.

**Comment by ahasemann** [comment]
Until that is in place can this be hidden though? It is confusing to have that option
