### ISSUE TITLE
Publisher N/A

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#151]
Currently attempting to upload a Word Doc as a reference. The tool is automatically recognizing certain fields for completing the reference which I then cannot edit. However, the tool is then saying "You must provide the publisher!" and doesn't let me upload the document.

**Comment by byndcivilization** [comment]
making this field requred was requested by @ahasemann earlier. has that changed?

**Comment by byndcivilization** [comment]
If so can i get an updated required fields from someone?

**Comment by isabellee** [comment]
It's not the requirement which is an issue. It's that the tool automatically recognizes the document as having "no publisher" and I cannot edit this field. Then when I try to upload it with it's reference details, it says "You must provide the publisher!" but still doesn't let me edit the publisher field.

**Comment by byndcivilization** [comment]
@isabellee I think this document was created before we changed this to a required field. I'll reset the db after i get a finalized list of required fields and check this again before launch.

**Comment by isabellee** [comment]
Okay, thanks!

**Comment by byndcivilization** [comment]
This will be sorted in #169
