### ISSUE TITLE
Law has been removed from dropdown

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#152]
When adding a document reference

**Comment by byndcivilization** [comment]
I believe this was asked for. are we moving it back in?

**Comment by isabellee** [comment]
We will send you an updated list of the document reference options required.

**Comment by byndcivilization** [comment]
@isabellee when can i get this list?

**Comment by isabellee** [comment]
It was drafted yesterday, currently getting feedback

**Comment by byndcivilization** [comment]
this will be sorted in #169
