### ISSUE TITLE
When attempting to add a second document reference, reference fields would not allow text to be entered

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#154]

**Comment by byndcivilization** [comment]
Is this for existing docuemnts or for a new document?

**Comment by isabellee** [comment]
New document

**Comment by byndcivilization** [comment]
The description in the title isnt clear to me. can you list the steps that got you to the point where you couldnt add reference field text?

**Comment by isabellee** [comment]
It seems to have worked just now. 

In any case, the steps were:
1. open up a new question, 
2. add a first document reference (everything worked fine)
3, When adding a second document reference, select it from the browser, upload, and then none of the fields for referencing the documents would function.

**Comment by byndcivilization** [comment]
@isabellee cant recreate this. Please reopen if this happens again.
