### ISSUE TITLE
Adding webpages as references

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#156]
The PDF would upload and then nothing else would happen on the researcher page. No option to edit the document's details. Document didn't show up in references.

**Comment by byndcivilization** [comment]
was this on chrome?

**Comment by byndcivilization** [comment]
can you send me the wepage you tried

**Comment by isabellee** [comment]
Yes on chrome.
I was trying http://www.resourcegovernance.org/

**Comment by byndcivilization** [comment]
I cant recreate this on chrome or safari. @isabellee did the pdf have a .pdf extension?

**Comment by isabellee** [comment]
I can't either now. I had just saved NRGI homepage as a pdf, and then was uploading the pdf, but no option to edit it. I guess leave this for now.

**Comment by byndcivilization** [comment]
Okay @isabellee  ill close but please reopen if it comes up again.

**Comment by isabellee** [comment]
Trying this again. Basically when trying to upload a webpage that is a pdf, the document will upload, but when entering the pdf link as the webpage, the tool says the webpage doesn't exist. So you can enter a non-PDF html link as a webpage, but not a .pdf as a webpage.
I saved this file but the link (http://unctad.org/en/docs/osgdp20083_en.pdf) "doesn't exit".

**Comment by byndcivilization** [comment]
ahhhh. Okay i know whats happening will fix.

**Comment by isabellee** [comment]
Thank you!

**Comment by byndcivilization** [comment]
okay wait before I fix this @ahasemann @isabellee etc. The web ref should really be pointing to a PDF. If its a remote pdf it should be uploaded as a remote pdf in the "document" type. I think a better solution is to do a check for pdf (or any other accepted file format) file extension and spit back an error message if its found directing to upload as a remote document. Is this fair?

**Comment by byndcivilization** [comment]
Also a note on webpage snapshotting. Its being worked on presently so should be pushed out later today or early tomorrow.

**Comment by isabellee** [comment]
I'm happy with that option but I do fear that some consultants might not understand that a .pdf is not a webpage if they are looking at it in a browser.

**Comment by byndcivilization** [comment]
thats what the error message will be for

**Comment by isabellee** [comment]
Sure! Could it please explicitly say that .pdf files need to be uploaded as document references?

**Comment by byndcivilization** [comment]
i wouldnt limit it to pdf since a user could theoretically point to a csv etc file.

**Comment by isabellee** [comment]
This file needs to be uploaded as a document reference. ?

**Comment by byndcivilization** [comment]
i dont really know why you would take a pdf snapshot of a website, upload it to a server and then try to use that pdf as a source, but yes if that was what they were doing then yes.

**Comment by isabellee** [comment]
I'm talking about a pdf URL that they've stumbled upon. So the researcher navigates to this link for example:
http://www.green-alliance.org.uk/resources/Managing%20resources%20for%20a%20resilient%20economy.pdf
and then they save that document.
Add a webpage reference -> upload the saved PDF and then try to use the link above as the URL.

**Comment by ahasemann** [comment]
If we are going to have the snapshot function then this will all be different, right?

**Comment by byndcivilization** [comment]
@isabellee that should be uploaded as a remote document.

**Comment by isabellee** [comment]
Yes, I completely understand but I don't think consultants will understand unless they have a pop-up which explains the issue.

**Comment by byndcivilization** [comment]
And that is what i suggested 5 comments up..."spit back an error message if its found directing to upload as a remote document"

**Comment by isabellee** [comment]
Sorry I also don't understand why we're repeating this, it's all clear with me.

**Comment by ahasemann** [comment]
@byndcivilization Can you clarify whether this will be resolved once the snapshot function is in place?

**Comment by byndcivilization** [comment]
I am resolving it right now.

**Comment by ahasemann** [comment]
@byndcivilization Am I understanding it correctly that the function then - even once it is a snapshot function- will enable the consultant to upload a pdf directly from the internet (rather than saving and then uploading it) and it is not about screenshotting a general website? If so, could we change the label from 'add webpage' to 'add pdf from a webpage'?

**Comment by byndcivilization** [comment]
that already exists. A user selects interviewee, document or webpage. 
- Interviewees are straight forward. 
- Documents allows you to upload a file from your laptop or the url of a file, i.e. http://www.green-alliance.org.uk/resources/Managing%20resources%20for%20a%20resilient%20economy.pdf. Either one will check if the file exists and add it to the db if it doesnt. 
- web page currently allows you to uplaod a pdf or png snapshot of a website from your computer and add metadata around that snapshot. Added functionality will allow a user to supply a url which will trigger an automated pdf creation event and then allow a user to add metadata.

**Comment by byndcivilization** [comment]
so an example of a website would be http://google.com

**Comment by ahasemann** [comment]
Ok, thank you for the clarification. And the added functionality for webpage will be ready for the launch?

**Comment by byndcivilization** [comment]
It should be ready for testing tomorrow.

**Comment by ahasemann** [comment]
Ok, great
