### ISSUE TITLE
Submit question/Submit assessment

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#158]
We're slightly confused the use of the term "Submit". 
When working on an individual question, the researcher can submit their answer for that specific question, which is different to submitting their answers for the full assessment. However, they can still go back into it and edit it. However, submitting the assessment in full is different, they cannot edit their answers anymore.
If submitting an answer to a question simply flags to the administrator that this question is complete, can we change "Submit answer" to "Mark answer as complete"? @DianaHartmann @gjacovella

**Comment by byndcivilization** [comment]
does 'Mark complete' work?

**Comment by isabellee** [comment]
Yes thank you
