### ISSUE TITLE
Once an answer to a question is submitted, the researcher edit it but cannot reset the answer to blank

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#159]

**Comment by byndcivilization** [comment]
no you cannot reset it to blank.why would you want to?

**Comment by isabellee** [comment]
In case they've really misunderstood the question?

**Comment by byndcivilization** [comment]
I can add that to the admin but id really rather not give researchers/reviewers the ability to reset things.

**Comment by isabellee** [comment]
Okay, that's fine, we can leave it.

**Comment by byndcivilization** [comment]
@isabellee @ahasemann do we want the admin to be able to remove answers?

**Comment by byndcivilization** [comment]
for clarity, i can manually remove the answer via db command if absolutely necessary.

**Comment by isabellee** [comment]
We will be flagging them if they're wrong I suppose, but I think it would be good to have the option of removing them. @ahasemann ?

**Comment by ahasemann** [comment]
I don't see why we would need that function

**Comment by byndcivilization** [comment]
I'll leave this for now as an issue and we can reassess. I can create a function that reverts an answer but that would overwrite the newer answer so i dont think that would be a good solution. We could add an admin reset question functionality but they can also just overwrite the answer so I dont totally see what the point is.
