### ISSUE TITLE
Sector tag

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#160]
This was previously discussed, but might have gotten lost - can we have a tag that specifies which sector the assessment is for that shows up on the question pages?

**Comment by byndcivilization** [comment]
@ahasemann isnt this already there?
![voila_capture 2016-2-22_05-39-42_pm](https://cloud.githubusercontent.com/assets/2875950/13235349/6e608d98-d98b-11e5-8118-9770f86cdf6a.png)

**Comment by ahasemann** [comment]
Yes, you are right, sorry!
