### ISSUE TITLE
Viewing reference details

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#162]
When a researcher saves an interview, the **administrator** needs to be able to see all of the contact details for the interviewee. We will need this information to get in touch with any interviewees and to check their existence.
When a researcher saves any other reference,*\* both the administrator and the peer reviewer **should have access to the full details of the reference. They will need this information to access the targeted evidence quickly.

**Comment by isabellee** [comment]
In regard to Issue 132, amendment:
When logging an interview, the researcher should be able to see the name of the interviewee. This shouldn't change straight away to "government official".

**Comment by byndcivilization** [comment]
this is on the interviewee admin page. Do you mean you want a link to this page? also this goes agains previous request for non-admins not to be able to see interviewee details. @ahasemann has this changed?

**Comment by ahasemann** [comment]
Hi Chris, no generally this hasn't changed, but my understanding is that currently either researchers or peer reviewers can no longer see the details for interview references that they have entered themselves. The aim is to anonymise the details for the other consultant. Is this a possibility? @isabellee Am I getting this right?

**Comment by byndcivilization** [comment]
If thats the case I think I can do it but let we hit it when i get back.

**Comment by isabellee** [comment]
@ahasemann yes that's correct.

**Comment by gjacovella** [comment]
I got lost with the comments above, I just want to flag out that the admin has not yet access to all the information included in the interview references (email, phone number etc). This is not an urgent issue, but we might want to have this information when we review the assessments. Of course, these details shouldn't appear on the peer reviewers' or researchers' assessments because we want to anonymise the details to other consultants, so only the admin needs to have access to this information.

**Comment by ahasemann** [comment]
@gjacovella Just found the email information in the Interviewee dashboard (can be accessed through the admin dropdown in the admin view.

@byndcivilization Can't see the interview info there though, i.e. the interview excerpts provided by the consultants

**Comment by byndcivilization** [comment]
Interview details will be on the question page. On the interviewee admin page, there are links to the questions they are cited on. Do we want some sort of admin functionality that aggregates all of the references?

**Comment by ahasemann** [comment]
You are right, I was thrown off by that section showing up as comments (and assumed it's from the general comment box).

What do you mean with an aggregation functionality?

**Comment by byndcivilization** [comment]
some way to show all the quotes attributed to a specific interviewee. its low priority but doable at some point.

**Comment by byndcivilization** [comment]
so is this closed?

**Comment by ahasemann** [comment]
I see, that would be great, but like you said low priority. Yes, closed (can't close it because I didn't open it)
