### ISSUE TITLE
Firefox bug in rendering some angular bootstrap UI elements

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#166]
The buttons for submit (researcher view)/ move (admin view) assessment are now sitting on the first question category. Can they please be moved up higher towards the top of the page?

**Comment by byndcivilization** [comment]
Can you take a screen shot and post. This is what I see:
![voila_capture 2016-2-22_05-58-44_pm](https://cloud.githubusercontent.com/assets/2875950/13235807/01a34652-d98e-11e5-9adb-b9919cccd08d.png)

**Comment by ahasemann** [comment]
That's strange, that does look correct. For me it showed up on the left side of the Precept 2 bar. Showed up like that for Diana as well. Can't recreate it because all of the assessments previously set up have disappeared along with the function to create new assessments.

**Comment by ahasemann** [comment]
So it's generally a much more squashed view compared to what it looks like for you.

**Comment by ahasemann** [comment]
![rgi tool](https://cloud.githubusercontent.com/assets/12699192/13257976/05f842a0-da49-11e5-8d2b-2d244915f475.JPG)

**Comment by byndcivilization** [comment]
is that chrome?

**Comment by byndcivilization** [comment]
and is it happening for others?

**Comment by ahasemann** [comment]
Firefox. it looked the same for Diana, I'll check with her after the meeting which browser she was using

**Comment by byndcivilization** [comment]
Looks like there is firefox issues. Short term, use chrome or safari. Longer term will look into this.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/315
