### ISSUE TITLE
Final required fields for references

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#169]
I  need @ahasemann @isabellee @DianaHartmann or the other RAs to supply a final list of required fields for references and options for document types.

**Comment by isabellee** [comment]
- Book
- Chapter of book
- Data file
- Judicial decision
- Legislation
- Parliamentary meeting notes
- Policy document
- Press article
- Report
- Working report

@byndcivilization

**Comment by byndcivilization** [comment]
Thanks @isabellee and @DianaHartmann can you send me the required fields for new documents and interviewees now?

**Comment by DianaHartmann** [comment]
Are you working in the tool? I cannot access to any question to review the required fields

**Comment by DianaHartmann** [comment]
Required files for interview:
Date interviewed
Fist name
Last name
Relevant interview statements 
Type of organization
Interviewee email
Interviewee phone number
Interviewee position
Organization name

**Comment by DianaHartmann** [comment]
sorry, What do you mean with new documents?

**Comment by byndcivilization** [comment]
when you upload a new document there are some fields you have to fill out or the new document wont be accepted. currently its title author and a couple of others. TBH at this point, I'd say just require a title since we will be the ones that have to fill in the bulk of the info to get complete citations.

**Comment by byndcivilization** [comment]
for interviewees, you want all of those fields required or are those just the fields that should appear?

**Comment by DianaHartmann** [comment]
Yes, all required (interview)

**Comment by DianaHartmann** [comment]
title, page number and year - required (new document)

**Comment by byndcivilization** [comment]
I'm going to go out on a limb and say this is going to give you a ton of problems. If someone is creating a new interviewee and they dont have any of those, they will not be able to add the interview. So they will either stop and email you guys and say "what the hell..." or will just enter junk to hack through it. We have the option to require either/or stuff, i.e. either a phone number or an email if that helps.

**Comment by DianaHartmann** [comment]
you are right. what about?
Date interviewed
 Fist name
 Last name
 Relevant interview statements 
 Interviewee email or phone number
 Organization name

**Comment by DianaHartmann** [comment]
I have discussed this with Anna

**Comment by byndcivilization** [comment]
Okay im adding role to this.

**Comment by DianaHartmann** [comment]
New document reference - document types
The list of options for document types is different to the one sent by Isabelle last week. 
Isabelle’s final list
• Book
• Chapter of book
• Data file
• Judicial decision
• Legislation
• Parliamentary meeting notes
• Policy document
• Press article
• Report
• Working report

Current list
![Uploading image.png…]()

**Comment by DianaHartmann** [comment]
We agreed that the required files for new documents are:
title, page number and year - required (new document) 
However, I cannot create a reference without publisher and author
![image](https://cloud.githubusercontent.com/assets/16593022/13403056/0a8d9088-df0b-11e5-999e-3ce11781a193.png)

**Comment by byndcivilization** [comment]
Final list im using:
Book
Book Chapter
Legislation
Data File
Generic (we will need something to catch stuff that researcher don't know)
Journal (this is a pretty standard citation type and if it confuses a researcher to have this, we might have bigger issues)
Judicial Decision
Magazine Article
Newspaper Article (these two media types have different citation types and it makes no sense not to include them both)
Parliamentary meeting notes
Policy document
Report
Statute (I believe this is different than case law and legislation and seems like a reasonable thing to have)
Web Page
Working Paper (I don't know what a working report is but this would catch both that and a working paper, see journal article)

**Comment by byndcivilization** [comment]
On pub/author requirement that should be or rather than and. Will fix.

**Comment by byndcivilization** [comment]
Oh @DianaHartmann i think thats actually user error. You need to enter _either_ a first and last author name _or_ a publisher.

**Comment by ahasemann** [comment]
We want to keep that list as hsort as possible. A statute is still legislation so covered under that. Magazine and newspaper article are covered under press article - is there an issue with saving them under press article and amending that if needed later on?  Generic shouldn't be in there, if there is a source that doesn't fit exactly they can pick the closest one listed. Is there an issue with amending details later on? If so we need to think about how to handle that because there will be at least some mislabelling happening by the consultants.

**Comment by byndcivilization** [comment]
The more you restrict this stuff up front, the more you will end up with busy work down the line. It seems really inefficient to me.

**Comment by byndcivilization** [comment]
Basically all of these things you are aggregating now will need to be disaggregated once you start doing citations. If you dont keep track of the differentiations now, you will have to separate them by hand later down the road right?

**Comment by ahasemann** [comment]
Yes, that's the plan

**Comment by byndcivilization** [comment]
So why would you want to make your job harder?

**Comment by ahasemann** [comment]
For generic, for example, we would have to do that in any case. And I don't want that option to be there because then it becomes too easy to choose that for everything

**Comment by byndcivilization** [comment]
I mean, we've already minimized what the researcher/reviewer can add in terms of citation materials, so we will already have to go through everything to flesh it out anyways. This seems like a really really sub-optimal solutions for minimising busy work.

**Comment by ahasemann** [comment]
I don't understand how adding the generic option is minimising that? It will encourage people to choose that for anything rather than thinking about what to label it as. We will have to review these labels no matter what.

**Comment by byndcivilization** [comment]
All the better reason to have a way to triage things. Those that are clearly a magazine or a bill or whatever are categorised as that and those that are a bit more ambiguous or recommend additional categories come to us basically flagged. I really dont see how we can trust a researcher to actually do a good job if we cant do a simple selection from a list of 15 types.

**Comment by ahasemann** [comment]
You can be very knowledgeable and understand a lot a about governance/ legislation in your country and still not have been trained/ know how to do proper referencing or understand the difference between wider legislation and a statute. That's simply the reality of who we are working with and we have to accommodate that.

**Comment by ahasemann** [comment]
@byndcivilization Can we please have as the list: 
• Book
• Book Chapter
• Data file
• Journal
• Judicial decision
• Legislation
• Parliamentary meeting notes
• Policy document
• Press article
• Report
• Working paper

**Comment by jimc33** [comment]
Lets go with this from @ahasemann

**Comment by byndcivilization** [comment]
Fine. breaks mendeley integration and possibly automated formatting.

**Comment by DianaHartmann** [comment]
Reference.
It seems as the list for type of document is different to the final list we agreed. 
Final list:
• Book
• Book Chapter
• Data file
• Journal
• Judicial decision
• Legislation
• Parliamentary meeting notes
• Policy document
• Press article
• Report
• Working paper

In the reference below as type of document: statute
![image](https://cloud.githubusercontent.com/assets/16593022/13782118/b7243960-eabd-11e5-8339-4d815733ec65.png)

**Comment by byndcivilization** [comment]
its different in the admin side as it adheres to citation data standards.

**Comment by gjacovella** [comment]
My researcher for Botswana was able to select newspaper article, that it's not on our final list
![image](https://cloud.githubusercontent.com/assets/16592996/13782417/e3e7d7da-eabe-11e5-8d60-c3004216d60b.png)

**Comment by byndcivilization** [comment]
they selected press article which defaults to newspaper. Press article isn't a type in any citation managment schema or api.
