### ISSUE TITLE
No option to save edited response

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#173]
[no edit save option.docx](https://github.com/NRGI/rgi-assessment-tool/files/144885/no.edit.save.option.docx)

There is no option to save the edited version after admin has left comments

**Comment by gjacovella** [comment]
When the admin flags an answer to the researcher, the researcher can edit the justification box but can't save a new score.

**Comment by byndcivilization** [comment]
So just to clarify, we want a mark complete button and a save button  here right?

**Comment by gjacovella** [comment]
Yes, both of them would be great!
