### ISSUE TITLE
"Return to assessment" option

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#178]
Is it possible to exit a question and return to the precept instead of returning to the assessment homepage?

**Comment by byndcivilization** [comment]
I dont uderstand this request. We dont have precept pages.

**Comment by byndcivilization** [comment]
To me, the two main user scenario will be either:
- going sequentially through an assessment, in which case completing one question will bring you to the next one, with the upper right navigation to skip if necessary
- doing cleanup by doing a question and going back to menu to select another question incomplete
