### ISSUE TITLE
Questions have been approved but not shown as completed, questions not peer reviewed but shown as completed

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#180]
[questions completed but not showing up.docx](https://github.com/NRGI/rgi-assessment-tool/files/145001/questions.completed.but.not.showing.up.docx)

**Comment by byndcivilization** [comment]
Does this mean the headers for the collapsable divs?

**Comment by HumairaP** [comment]
Yes, the headers don't indicate once a question has been completed and completely reviewed. However, a completed green box showed up on the headers for questions that hadn't been peer reviewed at all.

**Comment by byndcivilization** [comment]
moved to #206
