### ISSUE TITLE
Citations-missing information

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#182]
[Citations-RGI tool.docx](https://github.com/NRGI/rgi-assessment-tool/files/146473/Citations-RGI.tool.docx)
When I create and save a reference, I can't see the details of the reference (e.g. author, title, year etc) anymore. (see screenshot attached)

**Comment by gjacovella** [comment]
Now I can see the reference details.
[Citations-RGI tool.pdf](https://github.com/NRGI/rgi-assessment-tool/files/146535/Citations-RGI.tool.pdf)

**Comment by byndcivilization** [comment]
@gjacovella can you just drop screenshots directly into the box instead of embedding them in pdfs or docs? they will show up in the thread that way.

**Comment by byndcivilization** [comment]
Okay this should be fixed in the next push. The page needs to reload to receive the new ref data which is now implemented.

**Comment by gjacovella** [comment]
@byndcivilization apologies for the screenshots, but yesterday I had to use a very old laptop and I couldn't save them as pictures, but only copy and paste them on a word doc. Thank you for your help with the references.
