### ISSUE TITLE
Citation-missing delete/edit options

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#183]
The delete/edit options have disappeared.

**Comment by gjacovella** [comment]
I am working as a researcher (cperry) on Afghanistan 2020 and I noticed that I had the delete/edit options for one precept and not for the other. Now the delete and edit options have re-appeared for both precepts.

**Comment by byndcivilization** [comment]
Let me know if this happens again after tomorrows push.
