### ISSUE TITLE
New reference-cancel option

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#184]
[New-reference-cancel-option-RGI tool.docx](https://github.com/NRGI/rgi-assessment-tool/files/146482/New-reference-cancel-option-RGI.tool.docx)
The cancel option seems to be frozen, I can only upload, delete or close the dialog box (see screenshot attached). Does the cancel option have the same function as close dialog?

**Comment by byndcivilization** [comment]
I'm removing the cancel option. It's really there for times when your uploading a really really big file and want to stop in the middle. It's only enabled once upload has started, which means its only enabled for like 2-3 seconds tops, which means its kind of useless.
