### ISSUE TITLE
Resource page - copy and paste not allowed

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#189]
When I want to create a new block, I cannot copy and paste the the list of readings that I have on a Word document. They do not exceed the limit of 4000 characters. 
[Training_Material-260216.docx](https://github.com/NRGI/rgi-assessment-tool/files/148546/Training_Material-260216.docx)

![image](https://cloud.githubusercontent.com/assets/16592996/13358104/862ee484-dca5-11e5-9c53-c7c95aaffa50.png)

**Comment by gjacovella** [comment]
I tried to copy and paste the list of videos in the Word document attached above (Training Material) but I couldn't.

**Comment by gjacovella** [comment]
It looks like I have to enter all the information manually, but then I can't add hyperlinks

**Comment by byndcivilization** [comment]
Im not sure whats going on here. You can paste from non-word sources. Also for links, there is a link button on the toolbar.

**Comment by byndcivilization** [comment]
•	The Decision Chain of Natural Resource Management (I) 
•	The Decision Chain of Natural Resource Management (II)
•	Transparency and Accountability
•	International Governance Initiatives  
•	Legal and Regulatory Frameworks
•	Allocation of Rights
•	State-Owned Enterprise
•	Resource Economics 
•	Fiscal Regime Types 
•	Challenges of Revenue Management 
•	Policy Responses
•	Revenue Sharing and Decentralization

**Comment by byndcivilization** [comment]
this seems like a bigger issue with word specifically (i cant copy links from word to slack for instance). If you open this in open office, you can copy past things in more or less as normal.
