### ISSUE TITLE
After admin reviewing the completed questionnaire and having any questions flagged, can only send back to researcher. We might have to move asessments with flagged questions on to the peer reviewer. Can this be adjusted?

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#194]

**Comment by byndcivilization** [comment]
There are a couple of issues here. We should probably keep multiple issues separated to keep things organised.

**Comment by byndcivilization** [comment]
I think ive got this fixed. Lets check in next push.

**Comment by byndcivilization** [comment]
So just to confirm here: an admin as the opportunity to marke a flagged question as unresolved. 
This is the way to pass an answer that still has flags that havent been addressed. A reviewer wont see it as "'unresolved' but they will see the unresolved flags on the answer page as visually distinct from flags addressed to them.

**Comment by ahasemann** [comment]
Ok, thanks

**Comment by ahasemann** [comment]
Works
