### ISSUE TITLE
Researcher role: Added a reference that was already in the system, can only add page number/ date accessed, but not allowed to create reference because year appears as N/A and cannot edit that field

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#197]

**Comment by ahasemann** [comment]
![reference_year](https://cloud.githubusercontent.com/assets/12699192/13364060/b3882fc0-dcc4-11e5-88a8-2fd2a85d6629.JPG)

**Comment by byndcivilization** [comment]
This was explicitly asked for. We didn't want to allow researchers to change this stuff so we could do quality control on the admin side. Has there been some decision to change this? If so it will need to wait since its a bit of a new workflow feature.

**Comment by ahasemann** [comment]
It's fine that changes canot be made - but how do I upload this reference if I get that error message? Rihght now I would have to ask  the admin to make changes to the year saved and cant upload until that is done

**Comment by byndcivilization** [comment]
Why cant you upload until the change is made? All thats being stored on the answer record are the fields you have access to and an link to the document record. So when admins make changes to the document metadata it will propegate. So for example if you upload the same document three times, a researcher could potentially see different metadata on this dialog as the metadata is fleshed out by admins.

**Comment by ahasemann** [comment]
I get the error message that I need to include a year for the reference. The field is N/A though and I cannot edit it, so can't complete the reference

**Comment by byndcivilization** [comment]
was this document added as a webpage earlier?

**Comment by ahasemann** [comment]
I added it as a document previously

**Comment by byndcivilization** [comment]
It says the type is web_page.

**Comment by ahasemann** [comment]
Oh, I see. Then it is probably from that time when I crashed the tool trying to use the webpage reference function. So the reference data was not completed in the normal way, but it's saved in the system. So that issue then shouldn't happen normally?

**Comment by byndcivilization** [comment]
yeah, so there was a bug that let a user submit a document twice for web pages, this is probably one of those. the bug is patched and will be int he next push.
