### ISSUE TITLE
Admin view: Assessment status dashboard - can we add admin and external reviewer 1/2/3 to the fields there, alongside Researcher/ Reviewer?

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#198]

**Comment by byndcivilization** [comment]
There isnt any more room. If you want those in there, what do you want to remove?

**Comment by ahasemann** [comment]
I see, can we get rid of Assigned and add the admin?

**Comment by byndcivilization** [comment]
I dont understand. We arent keeping track of admin? Are we assigning admin user profiles to each assessment?

**Comment by ahasemann** [comment]
That's a good point - so each assessment is assigned to a specific admin (the RAs, Jason, and me). my question was mainly about being able to quickly see on the dashboard when the assessment is assigned for review to the admin (like you can see with the pen icon for the researcher/ reviewer).

**Comment by ahasemann** [comment]
But yes, each assessment has a specifc admin

**Comment by byndcivilization** [comment]
Okay. This is the first I've heard about this. We can do it, but it may have to happen after launch. Is it okay if it this assignment happens in the same place where we assign researchers and reviewers?

**Comment by ahasemann** [comment]
Ah, I didn't think about this as a special function, would currently all admin accounts see all assesments/ get notifications for all assesments etc?

**Comment by ahasemann** [comment]
Yes, in the same place is good

**Comment by byndcivilization** [comment]
Yes all admins have access to all assessments.

**Comment by ahasemann** [comment]
That would be fine, but ideally not everyone would get all notifications for all 90 assessments, but only for the ones they are in charge of

**Comment by byndcivilization** [comment]
well that does make things easier in some ways but will take some work.

**Comment by ahasemann** [comment]
Ok

**Comment by byndcivilization** [comment]
Proposed solution:
- [x] Add data field to controller and model
- [x] Add controller handling to email routing
- [x] add assessment dashboard ui elements to differentiate

**Comment by byndcivilization** [comment]
@alexander-elgin let me know if this makes sense.

**Comment by byndcivilization** [comment]
should be good
