### ISSUE TITLE
Not a priority -Admin view: on assessment overview page, questions are indicated as completed once received from researcher, but before actually reviewing, then are shown as non-completed after review has been done

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#199]
![admin view](https://cloud.githubusercontent.com/assets/12699192/13364267/d6b1be52-dcc5-11e5-9821-00af61e931aa.JPG)
![admin view1](https://cloud.githubusercontent.com/assets/12699192/13364271/d8598604-dcc5-11e5-939a-b4ccefe336e2.JPG)
![admin view2](https://cloud.githubusercontent.com/assets/12699192/13364273/dbf1f6a2-dcc5-11e5-8c8b-c3ecbaf57dad.JPG)
![admin view3](https://cloud.githubusercontent.com/assets/12699192/13364274/dd829c24-dcc5-11e5-9c5a-4c052029fff7.JPG)

**Comment by byndcivilization** [comment]
I need to figure out phrasing and formatting for those headers still.

**Comment by byndcivilization** [comment]
This should be good now.

**Comment by ahasemann** [comment]
Yes, works
