### ISSUE TITLE
Peer reviewer role Workflow

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#200]
Peer reviewer role: Currently the reviewer has to complete questionnaire in the same manner as the researcher, i.e. choose an answer criteria, justification, reference - they should only have to do that if they disagree with the researcher and select a different answer or if they have to address a flag by the admin

**Comment by byndcivilization** [comment]
This has been the explicit design since the beginning of the process. researcher submits, admin reviews, admin sends on or sends back, peer reviewer answers the questionnaire seeing the researchers answer and either provides rational for new choice or types "agree". It was also requested that on the first pass a reviewer is presented all answers as blank and to only show researcher flags on the answer page. This is all to ensure that reviewers take the time to go through each question.

**Comment by byndcivilization** [comment]
I'm going to mark this as wontfix for now unless there is a pretty strong case to make a pretty major change in the core workflow that we've had since almost the beginning.

**Comment by ahasemann** [comment]
But they can't just type agree, even if the researcher provided all the needed evidence and answered properly, the reviewer would still have to upload additional references. Peer reviewers have to review the entire questionnaire, but that does not necessarily they have to answer all questions

**Comment by ahasemann** [comment]
What do you mean with the reviewer beingg presented the answers as blank?

**Comment by byndcivilization** [comment]
They shouldn't. The tool will check to see if there is at least one reference, an answer selection, and justification content. Since a researcher has to upload a reference, that will already be there.

**Comment by byndcivilization** [comment]
by blank i mean that we dont want to make it too  easy to just agree. so they still have to select the option and type something. If you really want to, we can remove the justification requirement for reviewers, but i think it makes it easier to make sure we have complete data.

**Comment by ahasemann** [comment]
Ok, all fields including reference are labeled as required, so might just need to change that then. Can't check atm if I can complete the answer without adding references, am at home and tool not working properly on my laptop

**Comment by byndcivilization** [comment]
just to confirm that reviewers do not need to upload a new reference.

**Comment by ahasemann** [comment]
They would have to if they choose a different answer from the researcher (then it would be required). Other cases might be if they choose the same answer, but want to or are requested by the admin to provide additional references

**Comment by byndcivilization** [comment]
Okay then so I'll set the check to look for ref by reviewer if disagreement. It will take a bit to make this happen and won't come up for at least a month so I'll start a new milestone of post launch issues.

**Comment by ahasemann** [comment]
Great, sounds good

**Comment by byndcivilization** [comment]
moved to #217
