### ISSUE TITLE
Admin role: Post-peer review, if there are any questions flagged by the admin, assessment can only be sent back to the reviewer - at this stage it will often have to be sent back to the researcher

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#202]

**Comment by ahasemann** [comment]
Or sent to additional reviewers

**Comment by byndcivilization** [comment]
external reviewer is dealt with in #203.

**Comment by byndcivilization** [comment]
This will be fixed in next push.

**Comment by gjacovella** [comment]
Diana and I had the same problem this morning, we had to approve all the questions and close the flags in order to be able to send the assessment back to the researcher. We weren't able to flags questions to the researcher after the peer reviewer's review.
