### ISSUE TITLE
Can't scroll down when adding a new interview reference

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#205]
Have not had this at work when using the tool looking at my external monitor, Am on my laptop at home, so maybe that's why. I've completed all fields required but now can't scroll down to button to complete the reference
![tool_scroll](https://cloud.githubusercontent.com/assets/12699192/13367159/2bec89a8-dcd8-11e5-8ec6-b17c953ac7ad.PNG)

**Comment by byndcivilization** [comment]
i know scrolling works when im using the mouse wheel over the dialog. not sure if this helps. we could think about making this draggable.

**Comment by ahasemann** [comment]
Thanks, that worked. If we could make it draggable that would be great, might require a lot of explaining to consultnats otherwise

**Comment by byndcivilization** [comment]
@alexander-elgin, the draggability functionality seems to be broken on the answer flag dialog. Can you see what the problem is and once fixed, apply it also to the new interview reference dialog?

**Comment by alexander-elgin** [comment]
`draggable-dialog` directive was removed in 6a0bdf887d5d0d5226b6681af129490313d54100. I've restored it. Draggable functionality is available now
