### ISSUE TITLE
Resource page - add general introduction

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#208]
I would like to add this introduction above the blocks: "The following materials provide general and technical information about some of the key topics covered by the RGI questionnaire."

**Comment by byndcivilization** [comment]
@gjacovella @ahasemann we will need to figure out if this content still needs to be here and if so, is it up to date. I know at one point Jason had talked about a guidance page(s).

**Comment by byndcivilization** [comment]
@jim215 @ahasemann what are we doing about this?

**Comment by ahasemann** [comment]
Isabelle sent you the doc for those today, right?
