### ISSUE TITLE
Resource page:  resource order

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#209]
Two issues: 
1. I can't put the blocks in the right order, with block 1 above the others, and block 2, 3 etc following down. 
2. Can we delete the number after the block title? (the number should indicate the order, but I find it confusing to have it after the title)

**Comment by byndcivilization** [comment]
the numbers are there for dev purposes so I can see make sure things are ordering correctly (which they arent)
- [x] fix order by function on resource and FAQ
- [x] remove numbers on resource/FAQ headers
