### ISSUE TITLE
Flags not displaying when assessment is returned to researcher after trial review.

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#210]
Researcher view: Flags from the admin don't show up when the assessment is returned to the researcher after admin has reviewed test questions. They do show up after all answers have been completed and reviewed by the admin

**Comment by byndcivilization** [comment]
We had discussed this earlier. The decision was not to handle trial issues via flags because it indicates broader issues with the researcher and should be handled via email.

**Comment by ahasemann** [comment]
Yes, we did discuss, , but didn't realise about the flags. Let me think about how we'll handle this.

**Comment by byndcivilization** [comment]
As i recall the thinking was this:
The trial questions should be selected as fairly basic and really a test to see if a researcher/reviewer understands the tool and the methodology. If they arent getting these questions, there is something really wrong and we need to have a direct discussion to sort this out before they get too far into the assessment.

**Comment by ahasemann** [comment]
Yes, that is correct. The only thing is that currently they submit the trial questions to the admin and cannot make any changes to them while they under review - and once it is send back to them it's the full questionnaire and without flags for the trial questions. We're clear on addressing this over email, but then they shouldn't be able to submit, because potentially we have to get them to redo/ submit additional info several times even for the trial questions and they need to be able to have editing access to the tool for that. Does that make sense?

**Comment by byndcivilization** [comment]
Okay there is now an option to send trial back with flags.

**Comment by ahasemann** [comment]
Ok, so the flags do show up now, but they still have to submit, which vreates the issue mentioned above.

**Comment by byndcivilization** [comment]
Why wouldn't the submit the trial? How else would they signal they're done with the trial questions?

**Comment by ahasemann** [comment]
There is no issue with submitting the trial per se, but once they submit the trial questions to the admin and researcher cannot make any changes to them while they under review - and once it is send back to them it's the full questionnaire. We're clear on addressing this over email, but then they shouldn't be able to submit, because potentially we have to get them to redo/ submit additional info several times even for the trial questions (and before they can access the full questionnaire) and they need to be able to have editing access to the tool for that.

**Comment by byndcivilization** [comment]
there should be two options, send back for review of the trial or let them continue on the whole assessment. Is that not happening?

**Comment by ahasemann** [comment]
There is only the option of sending them back the entire questionnaire after reviewing the trial, not just the trial questions

**Comment by byndcivilization** [comment]
This should be fixed in the latest push. Admin will be able to send researcher full questionaire if no flags or send back for review if there are flags.
