### ISSUE TITLE
When I try to delete a reference, the screen freezes and then there's the question page popping out

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#211]
![image](https://cloud.githubusercontent.com/assets/16592996/13393631/984ca5c0-deda-11e5-9a76-1ab4fe147520.png)

**Comment by byndcivilization** [comment]
@gjacovella did this happen everytime or just once? Is this for AFG 2021 Mining question 1.a? can you tell me which reference this was for?

**Comment by gjacovella** [comment]
Sorry Chris, we can close this issue because I was using internet explorer instead of google chrome because google chrome wasn't working on my computer. (so it happened only once, for a few minutes).
