### ISSUE TITLE
Stage key for admin view

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#212]
Admin view: Assessment dashboard - Can you provide us with a list for the different statuses and what stage they exactly refer to. Currently it is difficult to understand what stage the questionnaire is in.

**Comment by byndcivilization** [comment]
@ahasemann Do you just need me to list this or do you want something on the admin view page?

**Comment by ahasemann** [comment]
Just a list is fine

**Comment by byndcivilization** [comment]
cool. I'll pin it to the slack channel.

**Comment by ahasemann** [comment]
Thanks!

**Comment by ahasemann** [comment]
thanks for pinning the list, I have a few questions:

What's the use of assigned here - does it mean it's generally assigned to them or it is passed on to them (assigned) to complete?
- researcher_trial (assigned to at least a researcher for 10 question trial)
- reviewer_trial (assigned to at least a researcher for 10 question trial) - ***_is this meant to be 'assigned to at least a reviewer'? *_
  **
- assigned (trial completed but full assessment not started) - **is this not just when the assessment has been assigned to someone, before anyone starts anything?**

What is the difference between?
- researcher_started
- started (researcher has started the full assessment)

Can these have the researcher/ reviewer distinction added?
- trial_started (researcher has started trial)
- trial_submitted (researcher has submitted trial)
