### ISSUE TITLE
More questions appearing when the questionnaire is reassigned to the researcher

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#215]
When the admin reassigns the questionnaire to the researcher, there are more questions to be completed. (I don't think this is a new issue but I couldn't find the closed issue on Github)

**Comment by ahasemann** [comment]
This is intentional for the work flow, i.e. the researcher completes initial test questions then gets access to the entire questionnaire once they have been reviewed by the admin

**Comment by gjacovella** [comment]
That's right, sorry!

**Comment by gjacovella** [comment]
But what if there were flags in the first test questions and we want the researchers to review these flags before receiving the entire questionnaire?
