### ISSUE TITLE
Interview reference - it doesn't accept a phone number instead of an email address

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#216]
![image](https://cloud.githubusercontent.com/assets/16592996/13396996/9ba7ba42-deef-11e5-8ceb-3913f2866169.png)
I'm sure the phone number exists, but I can't create this reference without providing an email address.

**Comment by gjacovella** [comment]
@byndcivilization I had again this problem with the peer reviewer this morning

**Comment by DianaHartmann** [comment]
I have the same problem. I have provided a phone number, but also have to enter an email address

**Comment by byndcivilization** [comment]
sorry typo. will push.

**Comment by gjacovella** [comment]
![image](https://cloud.githubusercontent.com/assets/16592996/13459599/c73b042e-e06c-11e5-820c-7cf85cfae669.png)
Anna and I still have this problem

**Comment by byndcivilization** [comment]
I know where this is. Will fix when I get in.

**Comment by gjacovella** [comment]
Thank you Chris

**Comment by byndcivilization** [comment]
This is fixed and will be pushed a bit later.
