### ISSUE TITLE
Add mineral tag to assessment

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#218]
- [x] add mineral tag to data field
- [x] add UI for assigning mineral tag
- [x] add display on assesment page showing what mineral is tagged

**Comment by byndcivilization** [comment]
We need the ability to add a mineral type to mining assessments. @ahasemann will supply a list of possible types. A supervisor will have the ability to add a mineral tag to an assessment. This should be displayed on the assessment and answer pages at the top:
Afghanistan 2021 mining assessment
would be
Afghanistan 2021 copper mining assessment

**Comment by byndcivilization** [comment]
open question to @jim215 and @ahasemann, do we want the ability to add mulitple minerals?

**Comment by ahasemann** [comment]
Should I post the list here?

**Comment by byndcivilization** [comment]
yeah thanks.

Also just confirmed from jason that only one mineral per assessment.

**Comment by ahasemann** [comment]
Country Mineral
Afghanistan     Iron ore
Australia   Iron ore
Botswana    Diamond
Burkina Faso    Gold
Cambodia    Gold
Chile   Copper
Colombia    Gold
Congo Kinshasa  Copper
Eritrea     Gold
Ethiopia    Gold
Ghana   Gold
Guatemala   Gold
Guinea  Bauxite
Indonesia   Copper
Kyrgyzstan  Gold
Lao PDR Copper
Liberia     Iron ore
Madagascar  Nickel
Mali    Gold
Mauritania  Iron ore
Mexico  Gold
Mongolia    Copper
Morocco     Phosphate
Myanmar     Precious stones (Jade)
Niger   Uranium
Papua New Guinea    Copper
Peru    Copper
Philippines     Nickel
Sierra Leone    Iron ore
South Africa    Gold
Tanzania    Gold
Tunisia     Phosphate
Zambia  Copper
Zimbabwe    Gold

**Comment by byndcivilization** [comment]
Oh sorry i mean just the mineral type lists. so: 
- Bauxite
- Copper
- Diamond
- Gold
- Iron ore
- Nickel
- Phosphate
  -Precious stones (Jade)
- Uranium

**Comment by byndcivilization** [comment]
any others?

**Comment by ahasemann** [comment]
No, that's it

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/383

**Comment by DianaHartmann** [comment]
Mongolia is not showing up the mineral. Cold you help me to add the mineral? Thanks 
Mongolia Copper

**Comment by byndcivilization** [comment]
@DianaHartmann fixed. @HumairaP Does Ukraine have a mineral?

**Comment by ahasemann** [comment]
The Ukraine is hydrocarbons

**Comment by byndcivilization** [comment]
Nope its set up as mining.

**Comment by ahasemann** [comment]
It is a hydrocarbons assessment though

**Comment by ahasemann** [comment]
How can assessments be relabeled or deleted such as the Ukraine mining one?

**Comment by byndcivilization** [comment]
there isnt a function for  that

**Comment by ahasemann** [comment]
Ok, we'll just create a new one then

**Comment by byndcivilization** [comment]
hold off for a sec

**Comment by byndcivilization** [comment]
nevermind yes add a ukraine hydro and ill roll back mining
