### ISSUE TITLE
I cannot create a new reference

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#220]
I have completed the required files and cannot create a reference
![image](https://cloud.githubusercontent.com/assets/16593022/13403215/e531dbb8-df0b-11e5-8edc-b0dd1ef092c0.png)

**Comment by byndcivilization** [comment]
@DianaHartmann i need more information? is it giving you an error? is it hanging? what type of doc?

**Comment by ahasemann** [comment]
I am encountering the same issue, it's telling me I need to provide a title even though I've put something into the title field
![tool_title](https://cloud.githubusercontent.com/assets/12699192/13407264/687d1f38-df1f-11e5-9ca5-e02875454990.PNG)

**Comment by DianaHartmann** [comment]
I uploaded a PDF as a book chapter (type). It did not show any error, was hanging.  I waited for 5 minutes and tried again (3 more times).

**Comment by byndcivilization** [comment]
Did you add an accessed date?

**Comment by DianaHartmann** [comment]
Yes, I did

**Comment by byndcivilization** [comment]
Okay there was an access date bug that was fixed but thats not it and it seems to be working for me. 

@ahasemann @DianaHartmann what role are you guys under?

Browser?

**Comment by DianaHartmann** [comment]
I was under researcher
Browser. Chrome
This was yesterday. Today it is okay

**Comment by byndcivilization** [comment]
@ahasemann can i get confirmation that this is working from you or another RA?

**Comment by ahasemann** [comment]
Yes, this is working today
