### ISSUE TITLE
Cannot move assessment to peer reviewer after admin has approved researcher's answers

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#224]
![image](https://cloud.githubusercontent.com/assets/17277178/13424833/00bbb414-df9b-11e5-9d14-93793b88f821.png)

**Comment by DianaHartmann** [comment]
I have the same issue. Im working on Uruguay assessment.  
![image](https://cloud.githubusercontent.com/assets/16593022/13425426/9a93f1c0-df9e-11e5-9b27-399cf87e429a.png)

**Comment by HumairaP** [comment]
I was able to do this when I created a new assessment. I haven't yet attempted to do it again on the other assessment, where I had he problem.

**Comment by HumairaP** [comment]
I have now double checked and the issue is still there for the azerbaijan assessment: 
![image](https://cloud.githubusercontent.com/assets/17277178/13427008/164cddf4-dfa9-11e5-9461-67c6610ba2fe.png)

**Comment by DianaHartmann** [comment]
I created a new assessment (Antigua and Barbuda 2018) and had the same problem. I cannot move the assessment to peer reviewer
![image](https://cloud.githubusercontent.com/assets/16593022/13427153/f9911fb2-dfa9-11e5-9f59-8271e287af3a.png)

**Comment by byndcivilization** [comment]
All of those are still in trial mode. The latest workflow as it was explained to me was that a researcher completes the trial. If the trial is good, the admin allows a user to continue (opt 2) and if not, sends back to the researcher for review (opt 1).

**Comment by byndcivilization** [comment]
@ahasemann you guys need to clear up what this workflow is.

**Comment by ahasemann** [comment]
Everybody is clear on the workflow itself, they were not clear that this part of the workflow (trial mode) had been added to the tool

**Comment by byndcivilization** [comment]
This is something that has been there and was requested quite a long time ago. The assessment status is also "Trial submitted". Further, the ability to pass trial flags back was something you requested to be fast tracked last week. The issue was closed and its in there now. Do we not want this now?

**Comment by ahasemann** [comment]
No, all is good, I was just explaining where the confusion came from

**Comment by DianaHartmann** [comment]
@byndcivilization, I'm really sorry about this. I got confused with the trial mode.

**Comment by byndcivilization** [comment]
no its not a problem, i just need us all to be clear on what the final workflow is as I had hoped this would have been solid a few weeks ago.

**Comment by byndcivilization** [comment]
This should be fixed in tonights push.
