### ISSUE TITLE
"Pick a score" instead of "add a reference" issue for the peer reviewer

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#225]
![image](https://cloud.githubusercontent.com/assets/16592996/13424965/bfad074c-df9b-11e5-8ef5-a844e25b0bd3.png)

When I pick a score but don't add a reference, there's a pop out message saying that I need to pick a score, instead of saying that I should add a reference.

**Comment by gjacovella** [comment]
Ok, this happened three times but now I selected a score without providing any reference and I could mark my questions as complete

**Comment by byndcivilization** [comment]
I cant recreate the incorrect error message. As far as PR picking score without a reference: A PR only needs to add a new reference if their selected answer differs from the researchers. I'll deprioritize and close tomorrow if you can confirm that when you marked complete without a ref it was the same answer as the researcher.

**Comment by gjacovella** [comment]
Yes, we can close this issue.
