### ISSUE TITLE
Not urgent - I noticed that we can select future dates for references (eg 3 March 2016), do we want this?

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#226]
![image](https://cloud.githubusercontent.com/assets/16592996/13425501/167846a6-df9f-11e5-9bff-849a66d40cd4.png)

**Comment by gjacovella** [comment]
This applies for documents and webpages, not for interviews. We can also select two dates for "cited by" and "accessed on" categories which do not make much sense, eg:  
Cited by: you on 03/01/2016 
Accessed on: 03/30/2016

**Comment by gjacovella** [comment]
I didn't mean to close it, sorry!

**Comment by byndcivilization** [comment]
@alexander-elgin We're still getting cases where a user can select future dates.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/238
