### ISSUE TITLE
Confirm button not working. Can't send the admin reviewed answers back to the researcher.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#227]
![image](https://cloud.githubusercontent.com/assets/17277178/13426408/082f9300-dfa5-11e5-8470-5e1b9d09ce84.png)

**Comment by HumairaP** [comment]
I logged in as the researcher and found that they are able to access the reviewed questions. However, when I pressed confirm, when I was at the stage highlighted above, the box did not close, so I did not realise that it had actually sent the review back

**Comment by byndcivilization** [comment]
I think this should be fixed now.
