### ISSUE TITLE
No "mark complete" button on peer reviewer's page

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#228]
![image](https://cloud.githubusercontent.com/assets/17277178/13426909/874104f0-dfa8-11e5-8241-aef76ca91104.png)

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13426947/cab463e4-dfa8-11e5-90ad-7674ee1e993a.png)

**Comment by HumairaP** [comment]
as a result of that, there is no button to be able to send the questions back to admin.

**Comment by isabellee** [comment]
bump

**Comment by byndcivilization** [comment]
fixed
