### ISSUE TITLE
Cannt deploy new assessment - assessment already deployed

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#229]
I have tried to deployment a new assessment and have not selected any country that is already deployed. However, it is still shown as “assessment already deployed.”

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13428178/a1d77f8a-dfb0-11e5-93be-5758282f422f.png)

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13428188/b9039608-dfb0-11e5-9adc-6a74660dfd9a.png)

**Comment by HumairaP** [comment]
I tried to deploy a new assessment for Armenia and I had the same problem.

**Comment by ahasemann** [comment]
This error message happens across a large number of combinations and it's becoming quite difficult to create new assessments for testing even though only 17 are currently deployed

**Comment by byndcivilization** [comment]
The tool is currently set to deploy all countries at once. So if you try to deploy some of the 2016 mining countries and then some other countries later on it will error out. This is in part a bit of a vestigial requirement from when we were doing manual question versioning. fixed in next push
