### ISSUE TITLE
NA answers

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#232]
They say (Explain in 'comments' box.), which I did, but then before I can save the answer a pop up says "You must provide a justification".

**Comment by isabellee** [comment]
Can we change it to "Explain in 'Justification: box"? @ahasemann

**Comment by ahasemann** [comment]
yes

**Comment by ahasemann** [comment]
This does not apply to the new questionnaire anymore - it won't have those instructions (as a justification will be required for all answers)

**Comment by byndcivilization** [comment]
I dont understand this request.

**Comment by ahasemann** [comment]
You can close this, the intructions from the old questionnaire where the test questions are from dont match the tool instructions, but this won't apply to the updated questionnaire as this has been changed
