### ISSUE TITLE
Adding document reference as a PR - bug

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#233]
The document will upload but when attempting to select a document type from the dropdown, the dropdown becomes shaded in red and doesn't let me select the document. This worked on and off over a series of documents, no obvious trend for which type of documents - maybe .pdf but tried a range of Word and PDF and it would work every other time.

**Comment by byndcivilization** [comment]
Can you send me a screenshot?

**Comment by isabellee** [comment]
![screenshot 1 for chris](https://cloud.githubusercontent.com/assets/16593138/13436015/1db41626-dfd5-11e5-875b-1fbac50c77ea.png)

**Comment by byndcivilization** [comment]
and it wont let you select anything right?

**Comment by ahasemann** [comment]
Isabelle is leaving, but no it won't let you select anything or type into the fields apart from page numbers or comments. Same thing as #174

**Comment by byndcivilization** [comment]
I think this is also related to tool updates so I'm deprioritising for now.

**Comment by byndcivilization** [comment]
I'm closing this. open if it appears again.
