### ISSUE TITLE
Add new document: Cannot upload jpg

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#234]
Get this error message
![jpg](https://cloud.githubusercontent.com/assets/12699192/13439711/a42a2bbc-dfe6-11e5-8a7b-c0114609f176.JPG)

When trying to upload these: 
![admin view1](https://cloud.githubusercontent.com/assets/12699192/13439727/be20952e-dfe6-11e5-940c-1a3587dd00a5.JPG)
![admin view2](https://cloud.githubusercontent.com/assets/12699192/13439731/bf61edb6-dfe6-11e5-9fb1-9792cadee696.JPG)

**Comment by ahasemann** [comment]
They're jpg files

**Comment by byndcivilization** [comment]
bug with uppercase extensions not matching. fixed
