### ISSUE TITLE
Unable to mark the questionnaire as completed once having followed the workflow fully

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#237]
![image](https://cloud.githubusercontent.com/assets/17277178/13462885/83b43a12-e081-11e5-84a5-e4663079c5c8.png)

**Comment by gjacovella** [comment]
same issue

**Comment by byndcivilization** [comment]
is it giving you the option to approve the questionaire? I think its titled "Final approval"?

**Comment by HumairaP** [comment]
No it doesn't.

**Comment by byndcivilization** [comment]
ahhhh. Okay so you need to go through and finalize things. On each answer you must choose a final answer. This answer can be:
- agree with the researcher using their justification or a modification of it
- agree with the reviewer using their justification or a modification of it
- choose a different answer all together and provide your own justification.

once all answers are finalised you can finalise the assessment. My understanding was that this would happen after the external reviewers had made their pass.

**Comment by byndcivilization** [comment]
Since this is agreed upon workflow I'm closing this issue. If we need to change the workflow lets create a new ticket around that.

**Comment by HumairaP** [comment]
@byndcivilization I had already completed this step, as can be seen in the screenshot above.

**Comment by gjacovella** [comment]
@byndcivilization the workflow is right, the issue is that up until yesterday we were able to finalise the assessment, close it and then we had the option to assign it to the external reviewer. Now we don't have the option to finalise and close our assessments and, therefore, we cannot assign them to external reviewers. See the difference between Italy 2017 and Italy 2019: both assessments are completed, but I could close Italy 2017 yesterday and I couldn't close Italy 2019 today 
![image](https://cloud.githubusercontent.com/assets/16592996/13468510/cfb88c7e-e09a-11e5-83c2-c35eb1f8ccde.png)

**Comment by byndcivilization** [comment]
Finalization should come after (or at least in tandem) external review. Has that changed?

**Comment by byndcivilization** [comment]
as far as the finalization process. Did you approve them after finalizing?

**Comment by byndcivilization** [comment]
Approval is a step below finalization. The screenshot you posted shows all questions approved but not finalized. I'm guessing you finalized and then approved the quesiton. I can change the button text to something like "unfinalize" if the question is finalized. Would that help?

**Comment by byndcivilization** [comment]
As far as assigning an external reviewer, you have the ability to assign an external reveiwer at any point in the process. They will only be able to see it after 80% of the questionaire has been completed by the reviewer.

**Comment by byndcivilization** [comment]
@ahasemann can you let me know approriate workflow here?

**Comment by ahasemann** [comment]
Yes, that's the general workflow. One thing is though that we might have some assessments for which an additional review cannot be completed (e.g. if both the researcher and peer reviewer are really slow and there is not enough time to have somebody else review). Would this be an issue with the current workflow, i.e. can the assessment only be finalised after having undergone the additional review?

**Comment by byndcivilization** [comment]
we can brute force it, but its not ideal. how often do we see this happening?

**Comment by ahasemann** [comment]
It shouldn't be such a large number, but it's difficult to say for sure how many until we're a bit into the data collection. 

One other thing linked to this, we have recently discussed the possibility of some of these addtional reviewers (staff) only reviewing a particular set of questions instead of the entire questionnaire. Would this be possible with the current workflow (e.g. only getting them to look at flagged questions) or would the tool require them to review all questions? It's ok if it's not possible, that would just be something for us to take into account into how we plan things.

**Comment by byndcivilization** [comment]
It's possible but requires a bunch of work. right now an external reviewer is assigned to a specific assessment. This would require them to be assigned to speific questions. It introduces all sorts of admin difficulties and im not sure the benefit outweighs the difficulties. In the current model external reviewers are not required to walk through the complete questionaire which might be the best of all possible worlds. If its something we want, lets create a ticket and address it as time allows.

**Comment by ahasemann** [comment]
No, it's not something we need to have, especially since they don't have to walk through the entire questionnaire. Sounds like that should work just fine.

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13493388/bffeb8d0-e135-11e5-9d33-3fea7a69c7e6.png)

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13493416/df560238-e135-11e5-9bbc-113ecbf9250e.png)

**Comment by HumairaP** [comment]
@byndcivilization I can now see the final answers option.

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13493497/5391fbde-e136-11e5-8fa6-9ddd006ba666.png)

I guess all is going well at this point. Will  see what happens once I have approved the assessment

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13493637/0e3903ce-e137-11e5-8710-a7af08ea7dc2.png)

I have reached the stage that giulia managed to get to a couple of days ago, so I assume that all is going well again.

**Comment by byndcivilization** [comment]
Okay last thing on this workflow. We've got a system to assign external reviewers. They can only see assessments that have reached a threshold. We don't have a notification set yet. From talking to Anna my understanding is that we will only want external reviewers to look before a reviewer has completed fully in some cases. So it's best to trigger the notification manually. I.e. A button that sends an email to all external reviewers to go ahead and review. Any external reviewers added after this is triggered should recieve that notification automatically.

Is this correct?

**Comment by byndcivilization** [comment]
I guess thats a question for @ahasemann

**Comment by ahasemann** [comment]
Yes, that sounds good

**Comment by HumairaP** [comment]
If the above is the case, I don't understand why you can only send to the external reviewer once the questions have been finalised. I guess the threshold needs to change in this case.

**Comment by byndcivilization** [comment]
No, finalisation happens before external review or at the same time. It was explained that the final answer should take into account both the internal and the external answers.

**Comment by HumairaP** [comment]
Okay, so how do you send the questions to the external reviewer, if it's to be done at the same time? Also, I created a new issue #259 as I was unable to see the questionnaire in external reviewer mode after finalisation.

**Comment by byndcivilization** [comment]
- External reviewers are added to questionaire continuously.
- They only have access once 80% is completed.
- The notification process is what is outlined above.

**Comment by byndcivilization** [comment]
If there is more discussion please move it to #203
