### ISSUE TITLE
New document reference: File URL function not working

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#240]
I have tried uploading a few different documents: 

www.resourcegovernance.org/sites/default/files/nrgi_Resource-Curse.pdf

www.odi.org/sites/odi.org.uk/files/odi-assets/publications-opinion-files/9938.pdf

www.resourcegovernance.org/sites/default/files/documents/nrgi_myanmar-state-owned-enterprises_full-report.pdf

It is working for Giulia, but I get this error message (have logged out and in again, but it's still happening): 

![file upload](https://cloud.githubusercontent.com/assets/12699192/13465278/cf6c24be-e08c-11e5-90fd-af35bcbbb55b.JPG)

**Comment by byndcivilization** [comment]
These dont have http:// prefix. Will add error handling for that.

**Comment by byndcivilization** [comment]
will push shortly

**Comment by gjacovella** [comment]
This morning I couldn't upload a pdf document using the URL ![image](https://cloud.githubusercontent.com/assets/16592996/13526707/994e57c8-e201-11e5-9626-f49e0b681575.png)

**Comment by gjacovella** [comment]
I tried with a different url and it finally worked

**Comment by byndcivilization** [comment]
Was the Oman constitution the one not working?

**Comment by gjacovella** [comment]
yes, I now tried with a different links and sometimes it works sometimes it doesn't (same for the website reference)

**Comment by gjacovella** [comment]
![image](https://cloud.githubusercontent.com/assets/16592996/13528510/57f58ee2-e20e-11e5-9c13-d977dceae112.png)

**Comment by byndcivilization** [comment]
Are certain links consistently not working? If so can you list them?

**Comment by byndcivilization** [comment]
If this is only happening with the constitute site, I think it might be something to do with that specific website. They are rendering pdfs as the user visits the page and the server logs are behaving the same way it would if you entered a webpage without error checking.

**Comment by byndcivilization** [comment]
Moving this to issue #276.
