### ISSUE TITLE
Not urgent - Filter option doesn't sort the questions by component, status or question number

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#241]
The Filter option works when I filter the assessments, but it doesn't work when I try to sort the questions by component, status or question number

**Comment by byndcivilization** [comment]
Is this on the assessment detail page or the question admin page?

**Comment by gjacovella** [comment]
assessment detail page
![image](https://cloud.githubusercontent.com/assets/16592996/13466989/42fbd2f6-e094-11e5-98d1-e4808f2d68a9.png)

**Comment by byndcivilization** [comment]
moving this to #242.
