### ISSUE TITLE
Webpage screen capture full length

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#243]
the current implementation on staging branch cuts off screen capture. the returned image should be full scroll. It's find to limit the width to 800.

**Comment by alexander-elgin** [comment]
A website can look different based on the viewport size e.g. responsive design for desktop and mobile devices. Hence the viewport size should be defined to get a snapshot. The web site capture is got for the defined dimensions (scrolling content will not be shown). We can just make a snapshot using a big enough viewport and crop the image then. See https://github.com/NRGI/rgi-assessment-tool/pull/245
