### ISSUE TITLE
not a priority- Order of FAQ, Resources and assessment questions

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#247]
When I work as a researcher, the blocks of questions/resources in the **FAQ and Resources** tabs seem to be in the opposite order (but they are in the right order when I work as an admin)
![image](https://cloud.githubusercontent.com/assets/16592996/13493057/8ad5cdb2-e133-11e5-847b-c68a47786154.png)

The **assessment questions** are always in the wrong order when you work as a researcher, admin or reviewer. 

![image](https://cloud.githubusercontent.com/assets/16592996/13493132/21dfb11e-e134-11e5-8844-3eb9097612ec.png)

**Comment by byndcivilization** [comment]
@alexander-elgin can you look into these two?

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/278, https://github.com/NRGI/rgi-assessment-tool/pull/279

**Comment by ahasemann** [comment]
The order for these is still not correct

**Comment by byndcivilization** [comment]
Should be patched in tonights push.
