### ISSUE TITLE
Not urgent: Add webpage reference: Pop up window is squashed

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#249]
Pop up window is squashed (using Chrome)
![webpage reference](https://cloud.githubusercontent.com/assets/12699192/13493543/8622b6d8-e136-11e5-8dd6-919ad9ca552a.JPG)

**Comment by ahasemann** [comment]
This seems to happen when the webpage was already uploaded previously and saved in the system. The window when adding a completely new webpage looks fine

**Comment by byndcivilization** [comment]
@alexander-elgin can you make this 800 width?
