### ISSUE TITLE
Add webpage bug: upload not working and empty error message

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#251]
The function did work initially, getting either an empty error message or the tool just being stucked
![webpage5](https://cloud.githubusercontent.com/assets/12699192/13493956/4c5d14f4-e139-11e5-89b5-320b1d341202.JPG)
![webpage3](https://cloud.githubusercontent.com/assets/12699192/13493963/54bd57bc-e139-11e5-9147-2592e2cd3bf4.JPG)

**Comment by ahasemann** [comment]
After trying several more times, the upload eventually worked a couple of times, but also totally hung up the tool after I tried to cancel to upload. Couldn't access any other pages anymore and had to log out and in again
![webpage4](https://cloud.githubusercontent.com/assets/12699192/13494007/93ccfafc-e139-11e5-841e-32bde9d392bb.JPG)

**Comment by byndcivilization** [comment]
Let me look when I get in. May need to tackle this on slack.

**Comment by byndcivilization** [comment]
I cant recreate this. It does take a bit but i can get it to break. Ill leave this up as a post launch bug and will move it if it comes up again in testing.

**Comment by byndcivilization** [comment]
I've also added a cancel button at the bottom.

**Comment by gjacovella** [comment]
I've been unable to create a webpage reference this morning: 
![image](https://cloud.githubusercontent.com/assets/16592996/13527421/b895940c-e206-11e5-9c23-a4254343cf64.png)

**Comment by byndcivilization** [comment]
Any website or just this one?

**Comment by byndcivilization** [comment]
I think this is related to this mornings server issues.

**Comment by ahasemann** [comment]
This is still happening, upload just hangs itself up
<img width="1440" alt="screen shot 2016-03-05 at 21 09 06" src="https://cloud.githubusercontent.com/assets/12699192/13550485/a1f27664-e316-11e5-8cc0-8a13f264320f.png">

**Comment by ahasemann** [comment]
It worked with other pages I tried though (resourcegovernance.org/ guardian.co.uk), so maybe something's going on with the kind of url for the EITI site

**Comment by byndcivilization** [comment]
i think this is a timeout issue.

**Comment by ahasemann** [comment]
Do you think it's specific to this website?

**Comment by byndcivilization** [comment]
Yes. I've upped the timeout limit and it seemed to work. We give the upload a certain amount of time to retrieve stuff. The tension is you don't want users to reload pages because of a slow server somewhere else. We might want to give the ability to cite Web pages in the old way in cases like this. Manually creating a Web page pdf and uploading that as a new doc

**Comment by isabellee** [comment]
This is still bugging.

**Comment by byndcivilization** [comment]
Bugging how?

**Comment by isabellee** [comment]
Tried several links - the blank warning message would appear and nothing would happen.

**Comment by byndcivilization** [comment]
All from eiti or from all sites now

**Comment by isabellee** [comment]
I've tried BBC, DailyMail, IMF, jotform.

**Comment by isabellee** [comment]
I've actually never been able to get this to work though.

**Comment by byndcivilization** [comment]
imf and jotform work for me

**Comment by isabellee** [comment]
Just tried again, on chrome and IE, still not working. Not working for @HumairaP

**Comment by isabellee** [comment]
Good internet connection atm too

**Comment by HumairaP** [comment]
It doesn't work for me either. 

![image](https://cloud.githubusercontent.com/assets/17277178/13571346/4789f362-e46c-11e5-8c1c-a26dbe018475.png)

**Comment by byndcivilization** [comment]
your internet connection doesnt have anything to do with it. this is all server to server

**Comment by isabellee** [comment]
Just mentioning it in case.

**Comment by byndcivilization** [comment]
moving this to #290
