### ISSUE TITLE
After reassigning assessment to another R/PR it is not possible to answer questions as there are no "save answers", "mark complete" buttons. Only a button to return to assessment page.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#252]

**Comment by HumairaP** [comment]
@ahasemann had the same problem

**Comment by ahasemann** [comment]
![reassigned](https://cloud.githubusercontent.com/assets/12699192/13494307/584cfb24-e13b-11e5-9e88-4dee71db4b37.JPG)

**Comment by ahasemann** [comment]
Answer criteria don't show up either

**Comment by byndcivilization** [comment]
@alexander-elgin this is an issue with the reassignment function. This function needs to check if a reassignment id is the same as the edit control id. If so, that should be updated also.

Also, the user that is unassigned needs to have that link removed from their profile document.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/272
