### ISSUE TITLE
The dropdown showing all the assessments is quite useful. It showed up on my computer yesterday and then disappeared. It seems to have reappeared again.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#254]
![image](https://cloud.githubusercontent.com/assets/17277178/13494310/5a7cd87e-e13b-11e5-8716-34d4a68fd2e8.png)

**Comment by HumairaP** [comment]
Having the country names on this would also be useful.

**Comment by byndcivilization** [comment]
@alexander-elgin this is a bug in the way the navigation bar is rendered.

**Comment by HumairaP** [comment]
This only happened when I was an admin.

**Comment by byndcivilization** [comment]
@HumairaP Just to be clear, those are not to take you directly to assessements. They take you to assessment subpages, i.e. show me all the 2016 pilot assessments. The list would be too long if you added all the assessments to the drop down, especially in later years. 

So the dropdown should only show up on admin. Is that working?

**Comment by ahasemann** [comment]
I can't see it in my admin view
![assessments](https://cloud.githubusercontent.com/assets/12699192/13501167/8262a45a-e15d-11e5-8b46-cb8f0e150aeb.JPG)

**Comment by HumairaP** [comment]
Thanks for the clarification Chris. That makes more sense. I can no longer see it in my admin view.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/270
