### ISSUE TITLE
Not urggent: Admin view: Can we change the label on the 'continue review' button, to 'start review' before admin has reviewed

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#255]
Researcher has submitted the trial, has not been reviewed yet, but the button says continue review
![continue review](https://cloud.githubusercontent.com/assets/12699192/13494537/c77c1e52-e13c-11e5-92bc-3d5fd0308cef.JPG)

**Comment by ahasemann** [comment]
When the complete assessment has been submitted it actually says 'start review'

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/312
