### ISSUE TITLE
In external reviewer mode there is no way of looking at completed questionnaire.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#259]
![image](https://cloud.githubusercontent.com/assets/17277178/13501263/df41affe-e15d-11e5-8921-9face6bebd94.png)

**Comment by HumairaP** [comment]
Furthermore, I had assigned 3 countries to this external reviewer, (Egypt, Iran and Azerbaijan) however only azerbaijan shows up.

**Comment by byndcivilization** [comment]
How complete are the ones that dont show up?

**Comment by HumairaP** [comment]
Fully completed

**Comment by byndcivilization** [comment]
this is likely the 80% threshold that was asked for.

**Comment by byndcivilization** [comment]
which years/versions are Egypt, Iran

**Comment by HumairaP** [comment]
Fully completed

**Comment by byndcivilization** [comment]
that isnt what i asked

**Comment by HumairaP** [comment]
Sorry, I'm having issues with my laptop and internet connection. Egypt: 2019 hydrocarbons Iran: 2019 hydrocarbons
