### ISSUE TITLE
researcher view: Unresolved questions not indicated on overview page

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#261]
Researcher view:
![flagged](https://cloud.githubusercontent.com/assets/12699192/13503339/cfeca1fe-e166-11e5-8ff8-10b583e2ba90.JPG)

Admin view:
![unresolved](https://cloud.githubusercontent.com/assets/12699192/13503354/e05a5e5a-e166-11e5-8131-ef0950d0b1b6.JPG)

**Comment by byndcivilization** [comment]
It was determined that unresolved questions shouldn't be indicated since we want the researcher and reviewers to complete things somewhat independently.

**Comment by ahasemann** [comment]
But they can see that others have been aproves, so doesn't that kind of give it away?

**Comment by byndcivilization** [comment]
how did we get here. is this passed back from reviewer to researcher?

**Comment by ahasemann** [comment]
Yes, this at a stage where it was passed back from reviewer to researcher

**Comment by byndcivilization** [comment]
Unresolved is a marker for things that dont concern the person in question as opposed to flags that are addressed to that person. I would rather leave it this way. At the end of the day i dont really like this solution since it lets crappy data through instead of forcing respondants to adhere to a bare minimum of completeness.

**Comment by ahasemann** [comment]
But the flags can still be seen by the other person even if they're marked unresolved? Sorry, can't check this right now because I finalised that assessment. Because as we discussed previously sometimes we will want to have flags that have come up with the researcher to be passed on to the reviewer and vice versa

**Comment by ahasemann** [comment]
Ok, checked, reviewer can see flags addressed at reseacher, so this is fine.
