### ISSUE TITLE
In external reviewer mode, once the ER has selected a different answer, it should be compulsory for them to add a reference to justify their answer.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#267]
![image](https://cloud.githubusercontent.com/assets/17277178/13524886/bc3817f8-e1f5-11e5-890d-cbc202ffda47.png)

**Comment by byndcivilization** [comment]
I see the reasoning behind this but i can almost guarentee this will cause problems. Especially for the gov reviewers.

**Comment by ahasemann** [comment]
We do require them to provide evidence as well though, scores can't be changed unless they can substantiate why

**Comment by byndcivilization** [comment]
In cases where an external reviewer choses an answer that isnt either the researcher answer or the reviewer answer, a new ref dialog should be triggered. This should be a based on the workflow that comes out of the biblio directive.

**Comment by HumairaP** [comment]
I think there may be another issue opened somewhere but I can't find it so since it relates to this, I am writing about this here.

As a peer reviewer I tried to change my answer to something that does not agree with the researcher's and I was able to do so without providing evidence.

![image](https://cloud.githubusercontent.com/assets/17277178/13678308/d9becaac-e6e5-11e5-90ea-b0be9c66e77c.png)

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/363
