### ISSUE TITLE
Second ER is able to comment and select answer even after the assessment has been fully finalised.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#268]
![image](https://cloud.githubusercontent.com/assets/17277178/13525904/325254ca-e1fc-11e5-9a28-bb8d9941ad74.png)

**Comment by byndcivilization** [comment]
This is still unclear to me. My understanding is that things here need to be relatively flexible as an assessment may go get external input even after approved.
