### ISSUE TITLE
Sometimes, when opening an assessment, instead of going to the overview page with the precepts and questions, it jumps straight to the first question.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#269]
![image](https://cloud.githubusercontent.com/assets/17277178/13526009/f104bd68-e1fc-11e5-8054-ce124825a705.png)

![image](https://cloud.githubusercontent.com/assets/17277178/13526018/fad2d848-e1fc-11e5-9585-a01d9df6d219.png)

**Comment by gjacovella** [comment]
same issue

**Comment by byndcivilization** [comment]
This should be the first time the assessment is opened in each stage.

**Comment by byndcivilization** [comment]
reopen if thats not he case
