### ISSUE TITLE
Can no longer see the external reviewer's comments. Was able to earlier, as a PR

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#273]
![image](https://cloud.githubusercontent.com/assets/17277178/13532966/24500d2a-e226-11e5-85c3-0bbe751a495f.png)

**Comment by HumairaP** [comment]
Can see the comments as admin though.

**Comment by gjacovella** [comment]
I can't see them as an admin.

**Comment by gjacovella** [comment]
When I click on the external reviewer comment ("PM reviewer"), it opens the flag above and this has happened a few times when I have flags in my assessments

![image](https://cloud.githubusercontent.com/assets/16592996/13535407/e8bd7142-e231-11e5-86ff-d8c39645e103.png)

**Comment by byndcivilization** [comment]
PRs should not be able to see external reviewer answers. Has that changed?

**Comment by byndcivilization** [comment]
@gjacovella moving this to issue #275

**Comment by byndcivilization** [comment]
I'm closing this part as it seems like the main issue is the flags opening for admins.

**Comment by ahasemann** [comment]
PRs and researchers should be able to see external reviewers answers, they just shouldn't be able to see their names

**Comment by byndcivilization** [comment]
This is a new feature.

**Comment by HumairaP** [comment]
I have the same problem that giulia described above, as admin:

![image](https://cloud.githubusercontent.com/assets/17277178/13705292/156be60e-e798-11e5-88a1-7edaa6b225f5.png)

**Comment by byndcivilization** [comment]
I dont understand @HumairaP theyre right there under the external answers heading. It's the same interaction as flags. click on the div and it will expand. Is this not working?

**Comment by gjacovella** [comment]
No, we click on the external reviewer's heading and it doesn't expand but it opens the flag above

**Comment by gjacovella** [comment]
This happens only when there are flags above the external reviewer's answer

**Comment by byndcivilization** [comment]
That is a different ticket. #275
