### ISSUE TITLE
Researcher is able to open and modify a question/score while the assessment is under admin review and the admin is not notified when a score has been changed

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#274]
While working as a researcher, I was able to open my assessment by double clicking on the "under admin review" button and modify my score for question 1.a from C to A. The admin had already approved score C and when the score changed to A, the question remained approved 

![image](https://cloud.githubusercontent.com/assets/16592996/13533090/bfa2c290-e226-11e5-8c2b-d8b9af5f0adf.png)

![image](https://cloud.githubusercontent.com/assets/16592996/13533267/9e792766-e227-11e5-8c3a-ee0d162c531c.png)

![image](https://cloud.githubusercontent.com/assets/16592996/13533290/ba753004-e227-11e5-99a5-916ae7b046a8.png)

![image](https://cloud.githubusercontent.com/assets/16592996/13533306/d186bda8-e227-11e5-814c-895c1d6313aa.png)

![image](https://cloud.githubusercontent.com/assets/16592996/13533319/d8d88820-e227-11e5-8cce-867bbb6747ab.png)

**Comment by HumairaP** [comment]
The peer reviewer is able to do the same.

**Comment by gjacovella** [comment]
I tried with the peer reviewer. I can still open the assessment, but I cannot change the score while under admin review (which is good)

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/13533870/59f0501c-e22a-11e5-82f0-7893573a176a.png)

The same applies for me as a researcher.

**Comment by gjacovella** [comment]
Ok I think it is fixed now

**Comment by byndcivilization** [comment]
Yeah its fine if they can see the page but everything is disabled now when under review. However they can still comment.
