### ISSUE TITLE
Sometimes external clicking on external review div opens flag div

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#275]
from #273

**Comment by alexander-elgin** [comment]
Are you reporting about this block?
![ext-reviewers](https://cloud.githubusercontent.com/assets/1811689/13564312/f89425c8-e472-11e5-9f96-732caab1a5fa.png)

**Comment by byndcivilization** [comment]
no this is an issue when external reviewers add answers to an answer page. The answer divs show up in a similar way to the flag divs. when you click an external reviewers collapsable answer div, it will close the flag div.

**Comment by byndcivilization** [comment]
@alexander-elgin was this addressed in your last push?

**Comment by alexander-elgin** [comment]
No. I still cannot reproduce the bug. Please, can you criteria / directions how I can reproduce the bug?

**Comment by byndcivilization** [comment]
from @HumairaP "This happens only when there are flags above the external reviewer's answer"

**Comment by gjacovella** [comment]
Just seen this, thanks Chris.

**Comment by byndcivilization** [comment]
fixed in next push.
