### ISSUE TITLE
Assessment overview: Precepts are not in correct order

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#280]
![Uploading precepts.JPG…]()

**Comment by ahasemann** [comment]
![precepts](https://cloud.githubusercontent.com/assets/12699192/13566023/5c78e6dc-e44b-11e5-8053-cac21a26829b.JPG)

**Comment by HumairaP** [comment]
Same for me

![image](https://cloud.githubusercontent.com/assets/17277178/13566825/762e3e48-e44f-11e5-96e5-17444871b5da.png)

**Comment by HumairaP** [comment]
In a different order on Internet explorer

![image](https://cloud.githubusercontent.com/assets/17277178/13567006/6f62dd84-e450-11e5-8968-d60dbf61128c.png)

**Comment by DianaHartmann** [comment]
Safari, same order that Internet Explorer (8,7,6,2)

**Comment by HumairaP** [comment]
Still not in order when you get the full questionnaire: 
![image](https://cloud.githubusercontent.com/assets/17277178/13571569/b3fe8804-e46d-11e5-8252-10c0b085925a.png)

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/313
