### ISSUE TITLE
Guidance note text is a bit off.

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#284]
![screenshot 2 for chris](https://cloud.githubusercontent.com/assets/16593138/13567480/774dd62c-e453-11e5-84bd-e96f125cadd2.png)
Guidance note text is wonky, missing letters here and there.

**Comment by HumairaP** [comment]
Anna said this will be updated once the guidance notes get back from copy-edit.

**Comment by isabellee** [comment]
I'm flagging it because it seems to be cutting off the first letters and spacing over several guidance notes rather than spelling mistakes which will be picked up on in copy edit.

**Comment by byndcivilization** [comment]
I think thats as good as its going to get tbh. There are other issues since you have multiple unordered lists in there. Because they arent the same list in the same cell i cant really close off the list from one to the next. So you or jason or whoever will need to go through and fix.

**Comment by isabellee** [comment]
Okay, that's fine, but it will need to be changed in the next few hours as it appears twice in the 10 questions. I don't know how to do it but I can ask Jason.

**Comment by byndcivilization** [comment]
admin -> question admin in the production tool

**Comment by byndcivilization** [comment]
rgi.nrgi-assessment-tools.org

**Comment by isabellee** [comment]
Thanks!

**Comment by byndcivilization** [comment]
Im closing this. reopen if its still an issue
