### ISSUE TITLE
References and answers are not saving in Internet Explorer version. Tool is very slow using this browser

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#285]
![image](https://cloud.githubusercontent.com/assets/17277178/13567811/71eb86aa-e455-11e5-9a5c-437588638b2f.png)

**Comment by HumairaP** [comment]
This is what the main page looks like even after I had saved my answers and added a reference:

![image](https://cloud.githubusercontent.com/assets/17277178/13567841/a962d6f6-e455-11e5-81e0-726d8a01a6bf.png)

**Comment by HumairaP** [comment]
When I click on the same question, I am asked to answer it all again: 
![image](https://cloud.githubusercontent.com/assets/17277178/13567866/c3ace3f8-e455-11e5-816a-aa21567607f0.png)

**Comment by byndcivilization** [comment]
I think we agreed not to use IE because of various issues with the browser.

**Comment by byndcivilization** [comment]
Im closing this because we've always said use non IE browser (preference for safari or chrome).
