### ISSUE TITLE
When is the "edit reference" feature going to be ready?

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#286]

**Comment by byndcivilization** [comment]
as soon as i can get to it

**Comment by byndcivilization** [comment]
Add an edit reference dialog similar to edit comment. for documents, it should allow you only the data held on the answer document, i.e. page number, comment and date accessed. for interviewees lets start with the same as documents for now (can edit date interviewed and interview content). We may need to allow a user to change the interview data, but lets start here.

**Comment by byndcivilization** [comment]
added editing for documents. there is a bug here where the serverside doc populate method isnt calling if you edit a ref immediately after posting it. 
still need to fix this bug and add edit interview fuction.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/342

**Comment by isabellee** [comment]
Lots of consultants complaining about this in the feedback, saying it doesn't work. e.g. Equatorial Guinea, Turkmenistan, Kyrgyzstan. @byndcivilization

**Comment by isabellee** [comment]
Reviewing the Technical Assistance conversation with Thomas Mayne, researcher for Turkmenistan, currently the administrators cannot edit the references at all but there are several changes we would like to make tho them.

**Comment by alexander-elgin** [comment]
@isabellee Please, can you provide some details? What's the desired behavior and what's the actual behavior of the system?
