### ISSUE TITLE
I can't see the other possible answers

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#287]
![image](https://cloud.githubusercontent.com/assets/16592996/13567959/3ed88b90-e456-11e5-8691-e18632a944c6.png)

**Comment by DianaHartmann** [comment]
Same for me using Safari (browser) for questions 145.8 (Precept 8) and 80.6 (Precept 6)
![image](https://cloud.githubusercontent.com/assets/16593022/13568351/94cd0d6c-e458-11e5-8c4b-a069ac62ff54.png)

**Comment by HumairaP** [comment]
I had the same issue before the big crash.

**Comment by isabellee** [comment]
Not an issue @byndcivilization . The only issue with this is that the question will say "Select Criterion F and enter your answer in the Justification section" and the only criteria we can select is A.

**Comment by byndcivilization** [comment]
can we just edit the question? either the letter or the question text?

**Comment by isabellee** [comment]
asking Jason. I don't know if he might want to keep F to help with scoring at a later point.

**Comment by byndcivilization** [comment]
you should probably flag @jim215

**Comment by isabellee** [comment]
thanks, I didn't know which jim he was. He's approved.

**Comment by byndcivilization** [comment]
can i close this then?

**Comment by isabellee** [comment]
Do I need to update the dependency in question 145?

**Comment by isabellee** [comment]
Otherwise it's been done.

**Comment by byndcivilization** [comment]
Just to confirm you are doing this in the production tool and not the question staging tool.

**Comment by isabellee** [comment]
Yes http://rgi.nrgi-assessment.org/admin/question-admin

**Comment by byndcivilization** [comment]
great. no one should be deploying from there just yet but definitely make any edits that you want to last.
