### ISSUE TITLE
The arrows for moving forward/ backward in the tool have disappeared

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#288]

**Comment by ahasemann** [comment]
Can see them while the page is loading, but then they disappear
![arrows](https://cloud.githubusercontent.com/assets/12699192/13569495/42f585f2-e460-11e5-82a1-928552c0b31a.JPG)

**Comment by byndcivilization** [comment]
Only in trial mode.

**Comment by ahasemann** [comment]
Why is that?

**Comment by ahasemann** [comment]
Got it, no worries

**Comment by gjacovella** [comment]
Today I don't have any arrows for my China assessment, but I have them in other assessments.

![image](https://cloud.githubusercontent.com/assets/16592996/14204832/bea7f3a4-f7fe-11e5-8903-3996c7e7d6c9.png)


![image](https://cloud.githubusercontent.com/assets/16592996/14204819/a9d17400-f7fe-11e5-9cd5-03a81a667eb5.png)
