### ISSUE TITLE
When you mark complete on a question, it jumps to the last question you answered on the trial questions, instead of going back to the assessment page or moving to the next question.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#291]
![image](https://cloud.githubusercontent.com/assets/17277178/13571548/953645b0-e46d-11e5-8a51-0c13cda5e8e3.png)

![image](https://cloud.githubusercontent.com/assets/17277178/13571553/9a73fc16-e46d-11e5-8854-bfa0daf7de27.png)

**Comment by gjacovella** [comment]
same for me

**Comment by byndcivilization** [comment]
This was from the trial questions making a divergence from the way that we navigate, i.e sequentially. I'm just going to set things to kick back out to the overview page if thats alright. its 10 questions and tbh im not sure the effort and potential bugs that will arrise from trying to get this working now is work the benefit.

**Comment by HumairaP** [comment]
I think going back to the overview would be most ideal.

**Comment by HumairaP** [comment]
This was happening to me when I was working on the questionnaire as a whole and not in the trial questions.

**Comment by byndcivilization** [comment]
it jumped back to the last question you worked on in the trial?

**Comment by HumairaP** [comment]
yes.

**Comment by byndcivilization** [comment]
navigation is only available for non trial assessments. during trials, answer submissions and approvals will be cicked out to the overview.

**Comment by HumairaP** [comment]
When I marked a question as complete, the view stayed still so I clicked return to assessment and then a few seconds later, it jumped on to the next question: 
![image](https://cloud.githubusercontent.com/assets/17277178/13601252/9a2809a0-e526-11e5-8361-4009dae89622.png)

**Comment by HumairaP** [comment]
I'm having the same problem as the reviewer. It is really frustrating to not be able to navigate. It's very "jumpy".

**Comment by byndcivilization** [comment]
I think this might be an issue with network lags. Can we just disable buttons while things are saving/transitioning? would be the same as what happens when you add a file from remote url.
