### ISSUE TITLE
Addressing flags as the researcher

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#292]
Editing feedback and flags from admin, working as researcher. Clicked on a flagged question, didn't touch anything to edit it, hit save answer and the tool didn't say that I needed to address the flag.

**Comment by isabellee** [comment]
Also tried changing my answer without providing a new reference and that worked too.

**Comment by byndcivilization** [comment]
theres not really a good way to check this since there are so many peices that would need to be checked. The best case is that you do a text match which would allow someone to submit if they just add a new line or a single character, so not much better.

**Comment by isabellee** [comment]
Sure, we won't really be reviewing anything until a few days from now, but if there's a way to ensure that if they are selecting a new multiple choice answer, they have to either justify their answer or submit a new reference, that's the essential thing that we have to look out for.

**Comment by byndcivilization** [comment]
I'll say it again, there's not really a good way to do this.

**Comment by byndcivilization** [comment]
On the resubmit button I need an error check to see if at least the answer selection, justification or length of reference array has changed. Only one of these criteria needs to be met.

**Comment by isabellee** [comment]
Thanks!

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/373
