### ISSUE TITLE
Tool accepting answer without reference

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#293]
I answered a question (multiple choice and justification). Then I uploaded a reference and deleted it from the citations. I then tried to save the mark complete without having a reference in the answer and the tool accepted it. Can we make it so that a reference is always required, regardless of whether one has been uploaded and kept, or uploaded and deleted?

**Comment by isabellee** [comment]
Tried to mark complete\*

**Comment by byndcivilization** [comment]
I'm moving this post launch

**Comment by HumairaP** [comment]
The Libya researcher was able to do this and did this for many questions once she had received my first set of feedback. I had to ask her to upload references once again.

**Comment by gjacovella** [comment]
The Liberian researcher was able to submit his question 145 without a reference (this is the second round of review on this assessment, so he might have uploaded and then deleted a reference)

![image](https://cloud.githubusercontent.com/assets/16592996/14256862/cf3289f0-fa92-11e5-9655-568c30c8f01d.png)

**Comment by alexander-elgin** [comment]
Answer submission without a reference is prevented in https://github.com/NRGI/rgi-assessment-tool/pull/380

**Comment by alexander-elgin** [comment]
If there is the only reference linked to the answer, the reference cannot be deleted. See https://github.com/NRGI/rgi-assessment-tool/pull/381
