### ISSUE TITLE
Catch giant webpages and error out before uploading

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#294]
big webpages are causing heap dump/fatal crash.

this one for instnace:
http://www.theguardian.com/environment/gallery/2016/mar/07/relocating-nepals-rhinos-in-pictures

There should be a check upfront to see size and make reject if too big.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/306
