### ISSUE TITLE
Webpage upload failing to create screenshot of site

### ISSUE THREAD

**Issue by jimc33** [NRGI/rgi-assessment-tool#295]
The process seems to work fine but no screenshot is created/visible. In the question page the hyperlink goes to the original url rather than the screenshot. Same when viewed as admin afterwards.

**Comment by byndcivilization** [comment]
- please post url
- what did you name it

**Comment by jimc33** [comment]
Name: asdasdasd
Link: https://s3.amazonaws.com/rgi-documents-dev/608a62363b79205a1e827d7af045e70747f32d75.png
URL: http://resourcegovernance.org

**Comment by jimc33** [comment]
The screenshot seems to have been created successfully (see above). However as the researcher, and as the admin, this is not visible via the Reference metadata block. This may not be a bug per se, however I presume the intent is for the metadata to include a link to the screenshot as well as the original url

**Comment by byndcivilization** [comment]
The screenshot is more for archiving purpose and should only really come into play in cases of dead links. We can certainly include something in the reference block.

**Comment by jimc33** [comment]
Ok makes sense

**Comment by byndcivilization** [comment]
do we want it or not? @ahasemann @jimc33

**Comment by jimc33** [comment]
I defer to Anna

**Comment by byndcivilization** [comment]
@ahasemann please confirm or close issue. Thanks!

**Comment by ahasemann** [comment]
Fine to leave as is for now then, we can revisit if  there turns out to be an issue with webpages disappearing more quickly than the data collection being completed.  (Can't close the issue as I'm not the creator)
