### ISSUE TITLE
Cannot copy text from word document into justification box

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#296]

**Comment by byndcivilization** [comment]
Know issue. Not possible. Really a big with word. Can copy-paste from odf format.

**Comment by gjacovella** [comment]
@byndcivilization I just received an email from the researcher for Liberia, who said that he completed the sample questions offline and now he is not able to copy and paste from his Word document

**Comment by byndcivilization** [comment]
this will not be fixed. we cant do it with the current text editor.

**Comment by byndcivilization** [comment]
odf format works.
