### ISSUE TITLE
This has happened before - can't find the old issue - Can't upload document, even though I have provided a title

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#298]
I tried with two different documents:

![image](https://cloud.githubusercontent.com/assets/17277178/13577330/d829b6c4-e489-11e5-9d42-f160ffd73bd1.png)

![image](https://cloud.githubusercontent.com/assets/17277178/13577335/dc1a4708-e489-11e5-91f9-e1b397763c18.png)

**Comment by byndcivilization** [comment]
Cant recreate. can you post higher res pictures. cant read error messages or fields.

**Comment by HumairaP** [comment]
It says - You must provide a title.

**Comment by byndcivilization** [comment]
I need to see the stuff you have entered in

**Comment by HumairaP** [comment]
As in the documents? I can't remember which ones I tried to upload. 

As for what I entered in the fields:

Title - Cambodia
type - book chapter

Title - Indonesia
Type - book chapter

**Comment by byndcivilization** [comment]
This is a long shot but are the fields auto completing because you had filled in the same word in a different ref?

**Comment by HumairaP** [comment]
I don't remember which documents I had put in.

**Comment by HumairaP** [comment]
Nothing was auto completed though.

**Comment by HumairaP** [comment]
I had typed in the title.

**Comment by byndcivilization** [comment]
This is throwing an uncaught 413 error entity too large. I think its being sent server side.

**Comment by DianaHartmann** [comment]
The researcher (Philippines) cannot create a reference, it is asking to enter a title even though she has entered one. 
![image](https://cloud.githubusercontent.com/assets/16593022/13744852/979babae-e9e2-11e5-9874-5065df28a5c3.png)

**Comment by DianaHartmann** [comment]
However, this problem has been solved as the researcher has submitted the trial
