### ISSUE TITLE
Welcome page: Change text

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#300]
Currently it says, Researcher R, welcome to the assessment to RGI Assessment Tool Portal.

Can that be changed to: Researcher R, welcome to the RGI Assessment Tool Portal.

**Comment by byndcivilization** [comment]
Is that the only text that needs to be changed?

**Comment by ahasemann** [comment]
@isabellee sent you a doc for the general text, have you received that?

**Comment by isabellee** [comment]
https://github.com/isabellee/RGI_isabellee/blob/master/RGI_toolwelcometext.md

**Comment by byndcivilization** [comment]
No I had not got that. Thanks.
