### ISSUE TITLE
Not urgent: Cannot delete a supervisor account

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#301]
The account you created for me has my name and email misspelled, I could change the name/ email, but I cannot change the user name which also has my name wrong. I've created a new account with the correct spelling, he incorrect should be deleted, so there is no confusion

**Comment by byndcivilization** [comment]
We need a workflow that alows for supervisor and external reviewer deletion. This should be similar to the general user deletion in that it checks to see if the supervisor/external reviewer is assigned to an assessment and fires back an error if so.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/321
