### ISSUE TITLE
Sometimes I can't upload a document because I can't enter the title and select a type of document

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#302]
![image](https://cloud.githubusercontent.com/assets/16592996/13599090/33018e02-e519-11e5-9578-9f7e7607da14.png)

**Comment by gjacovella** [comment]
I guess it is the same issue as in  #174
it happens only with some pdf files

**Comment by byndcivilization** [comment]
Is this consistent this morning?

**Comment by gjacovella** [comment]
no now it works, but this happened 4-5 times this morning

**Comment by HumairaP** [comment]
I tried to upload a pdf doc and it didn't work - can't write in title, type, publisher, year published:

![image](https://cloud.githubusercontent.com/assets/17277178/13601395/b2106408-e527-11e5-81c3-34c5abfce43b.png)
