### ISSUE TITLE
New document reference: FILE URL - cannot upload pdfs

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#303]
Receive error message, tried with several docs

https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwin_fW84rDLAhUJyRQKHVEnC8UQFggcMAA&url=https%3A%2F%2Fjobs.wateraid.org%2Fvacancy%2Ftraining-and-capacity-development-manager-0349%2F368%2Fdescription%2Fajaxaction%2Fdownloadfile%2F%3Fid%3D20552%26pagestamp%3Df346a3e6-f5b9-4c8d-b113-1cfb1e22c8a8&usg=AFQjCNFDWyNDtmruUAC3hI6GAx73oCRK9w&bvm=bv.116274245,d.d24

https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=10&ved=0ahUKEwin_fW84rDLAhUJyRQKHVEnC8UQFghdMAk&url=http%3A%2F%2Fresourcecentre.savethechildren.se%2Fsites%2Fdefault%2Ffiles%2Fdocuments%2Ffinal_pfa.pdf&usg=AFQjCNHe3rXrUC3H6zCFw_xuao9OB_bQNA&bvm=bv.116274245,d.d24&cad=rja

![pdf](https://cloud.githubusercontent.com/assets/12699192/13604706/ebbfe6c4-e53b-11e5-87b6-4d15100d6bcf.JPG)

**Comment by byndcivilization** [comment]
The remote url checks for file extension to make sure people arent uploading non approved files. Maybe add in the error that you should try to download the file and upload from your desktop?

**Comment by ahasemann** [comment]
Sorry, what do you mean with add in the error?

**Comment by ahasemann** [comment]
Oh, you mean an error message? Sure.

But do you why these aren't working? They are pdf urls

**Comment by byndcivilization** [comment]
no .pdf extension. TBH theyre download targets so they should be downloaded and then uploaded anyways.

**Comment by byndcivilization** [comment]
text addition reads "If this is in error, please try uploading file from desktop."

**Comment by ahasemann** [comment]
Ok great
