### ISSUE TITLE
Assessment page: Can't see the precept overview or any of the questions

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#308]
Everybody else can see them, I've re-started Chrome, but it's still not working
![answers](https://cloud.githubusercontent.com/assets/12699192/13634611/78710ae6-e5ee-11e5-84a5-b61ebc98f9c7.JPG)

**Comment by byndcivilization** [comment]
Is this still happening? Its working for me.

**Comment by ahasemann** [comment]
It's still not working, I'm the only one it's not working for though, have no idea why
