### ISSUE TITLE
Handle extra anonymous interviewees

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#309]
In some cases an interviewee will need to be anonymous throughout the system. So when a user uses the autocomplete for existing interviewees, these users should not show up. The best solution I can come up with is to create a generic "Anonymous Interviewee" with no email and no phone number. In cases where this interviewee is selected, an additional field should show up to allow html input of contact information. This information should only be viewable in the reference divs as a supervisor. The field should be stored on the answer document in the reference array.  
- [ ] update answer model
- [ ] update answer controllers
- [ ] update ui for input
- [ ] update ui for reference directive display

**Comment by ahasemann** [comment]
That sounds good!
