### ISSUE TITLE
assessment list dates lagging

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#310]
After trial submission submitted, the submission date/time did not update. Anna said it takes a few mins?
we need to set a refresh assessment list broadcast.

**Comment by byndcivilization** [comment]
There are time stamps recorded when when certain assessment stages are complete. these are displayed as calendar icons with a popup that displays date. this date does not populate immediately without a page reload. Moving assessments (submission, seding back, etc) needs to trigger a broadcast to regenerate this data on the assessment list page.

**Comment by alexander-elgin** [comment]
Once a trial assessment is submitted by the researcher or approved by the supervisor there is a redirect to the page 'Assessments List'. The last modified date is updated. Trial submission is not shown in the milestones.
What is required to implement? Is it required to update the last modified date for all users in all browsers where the page 'Assessments List' is open?

**Comment by byndcivilization** [comment]
We're storing the following time stamps:
- created (single timestamp)
- assignment_date (single timestamp)
- researcher_start_date (single timestamp)
- reviewer_start_date (single timestamp)
- researcher_submit_date (overwritten timestamp)
- reviewer_submit_date (overwritten timestamp)
- last_review_date (overwritten timestamp)
- approval_date (single timestamp)
- last_modified (overwritten timestamp)

on the supervisor view all of these should be seen if they exist
on the researcher/review view they should only see the start_date/submit_date that applies to them
