### ISSUE TITLE
Add delete interviewee and document functions

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#311]
These should only be availble if they are unreferenced in any answers.

**Comment by alexander-elgin** [comment]
referenced objects (interviewee & document) are unlinked on reference removal (see https://github.com/NRGI/rgi-assessment-tool/pull/364)

**Comment by alexander-elgin** [comment]
The feature 'Delete Interviewee' is done. See https://github.com/NRGI/rgi-assessment-tool/pull/366

**Comment by alexander-elgin** [comment]
The feature 'Delete Document; is done. See https://github.com/NRGI/rgi-assessment-tool/pull/367
