### ISSUE TITLE
Assessment tool user overview: Dates for Assigned, Started etc are not showing up

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#322]
![user](https://cloud.githubusercontent.com/assets/12699192/13669244/196e28c2-e6ba-11e5-93d0-298c93ce84d9.JPG)

**Comment by byndcivilization** [comment]
But these are showing up on the assessment list page right? We substantially changed this data model and i forgot to port it over to the user page.

**Comment by ahasemann** [comment]
Yes, it's working on the country page

**Comment by byndcivilization** [comment]
yeah okay so its my fault. will fix in tonights push
