### ISSUE TITLE
When picking a score as ER, the score is saved twice. This happened to me a couple of times.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#326]
![image](https://cloud.githubusercontent.com/assets/17277178/13702812/39def986-e789-11e5-86e0-b75963a77d0c.png)

**Comment by alexander-elgin** [comment]
I cannot reproduce the issue

**Comment by byndcivilization** [comment]
@HumairaP did you hit save twice? Did you enter twice. the answer is stored as an object array meaning that the the same user can save two different answers.

**Comment by HumairaP** [comment]
I might have done so, my computer can be very slow at times.

**Comment by byndcivilization** [comment]
@alexander-elgin can we disable the submit button while the answer is saving?

**Comment by alexander-elgin** [comment]
I've made the button disabled while the request is being processed. See https://github.com/NRGI/rgi-assessment-tool/pull/352
