### ISSUE TITLE
Production tool: The dependencies information is not visible on the question pages

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#328]

**Comment by byndcivilization** [comment]
the answer page, the answer dialog that pops up on first viewing or the question edit page?

**Comment by ahasemann** [comment]
On the answer page, for example Q129.7 has this dependency listed in the edit question page:
![capture9](https://cloud.githubusercontent.com/assets/12699192/13758449/e8796828-e9ff-11e5-88ac-a1ea2043fb32.JPG)

But that instruction is not visible on the actual answer page

![capture10](https://cloud.githubusercontent.com/assets/12699192/13758476/04e96800-ea00-11e5-827e-c006a6741cef.JPG)

**Comment by byndcivilization** [comment]
Oh sorry its on the question guidance page.

**Comment by byndcivilization** [comment]
question guidance tab rather

**Comment by ahasemann** [comment]
Ah, ok! That's fine then, formatting is just a bit off
![capture11](https://cloud.githubusercontent.com/assets/12699192/13758785/967c1154-ea01-11e5-8010-069b4d28005e.JPG)

**Comment by byndcivilization** [comment]
Yeah it was kind of a list minute addition. i removed some of the space but let me know if there is anything you want in there.

**Comment by ahasemann** [comment]
Is there a way to minimise the heading for the Dependencies section?

**Comment by byndcivilization** [comment]
Yeah it can be whatever you want. Do you want it one step down and maybe italics?

**Comment by ahasemann** [comment]
Yes, that would be great
