### ISSUE TITLE
Can we add a column on the assessment overview page to see the external reviewer's scores?

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#329]
This would be helpful for  both the external reviewer and admin.

**Comment by byndcivilization** [comment]
this needs to appear only with isSupervisory() auth. i think its best in the interest of legibility to make this cell of rows collapsable with a default of collapsed. It should show each reviewer on a row as:
- "reviewer first name" "reviewer last name" - "reviewer letter score"

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/351
