### ISSUE TITLE
I couldn't open a book source that our researcher for Australia used several times - is it an issue on our side or a problem with his pdf/url?

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#336]
![image](https://cloud.githubusercontent.com/assets/16592996/13741133/6de40128-e9cc-11e5-82dc-b77e11e12385.png)

**Comment by byndcivilization** [comment]
Can you post the link?

**Comment by byndcivilization** [comment]
Oh its not a pdf. It was an archived html page.

**Comment by ahasemann** [comment]
The same is also happening with a source for the Philippines assessment: https://s3.amazonaws.com/rgi-documents/4d3b67210e2cc7feefd8c086529f418fcca95841.pdf

**Comment by byndcivilization** [comment]
Yeah there are a couple like this. Best solution is to just create an issue page for broken document links.

enter them as:
'- [ ] [broken link in our db]()'

this will render as:
- [ ] [broken link in our db]()

and i can mark them off as i add from the source link.

**Comment by ahasemann** [comment]
So I would enter that one as:
'- [https://s3.amazonaws.com/rgi-documents/4d3b67210e2cc7feefd8c086529f418fcca95841.pdf] '

**Comment by ahasemann** [comment]
Is that correct?

**Comment by byndcivilization** [comment]
- [ ] https://s3.amazonaws.com/rgi-documents/4d3b67210e2cc7feefd8c086529f418fcca95841.pdf

'- [ ] https://s3.amazonaws.com/rgi-documents/4d3b67210e2cc7feefd8c086529f418fcca95841.pdf'

**Comment by ahasemann** [comment]
'- [ ] 'https://s3.amazonaws.com/rgi-documents/4d3b67210e2cc7feefd8c086529f418fcca95841.pdf

**Comment by byndcivilization** [comment]
from the number i get the metadata page so that should be enough

**Comment by ahasemann** [comment]
Sorry, how does that work?

**Comment by ahasemann** [comment]
- [ ] https://s3.amazonaws.com/rgi-documents/4d3b67210e2cc7feefd8c086529f418fcca95841.pdf

**Comment by byndcivilization** [comment]
closing this and moving to #338

**Comment by ahasemann** [comment]
- [ ] https://s3.amazonaws.com/rgi-documents/4d3b67210e2cc7feefd8c086529f418fcca95841.pdf
