### ISSUE TITLE
Sometimes I need to fill in extra information (title, position, organisation) when creating a user account - without entering this info I can't create the account 

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#337]

**Comment by byndcivilization** [comment]
Does this only happen sometimes? I think this is an issue with external reviewer requirements.

**Comment by gjacovella** [comment]
Yes, it happened only a few times while I was creating all the user accounts. I needed to add extra information for at least 4 consultants.

**Comment by byndcivilization** [comment]
@gjacovella does this happen anymore?

**Comment by gjacovella** [comment]
yes, it happened again on Tuesday when I created the user accounts for the PRs of Cambodia and Nigeria. I took a screenshot from my personal laptop as I was working from home, I can send it to you on Monday if you think it might be useful.

**Comment by gjacovella** [comment]
![image](https://cloud.githubusercontent.com/assets/16592996/16725239/4aa92168-474e-11e6-9c7a-1d42d6926277.png)

![image](https://cloud.githubusercontent.com/assets/16592996/16725264/64f3b74a-474e-11e6-8763-fdec5e63de54.png)

**Comment by ahasemann** [comment]
@alexander-elgin Hi Alex, can you disable the requirement for the below fields to be completed for new user accounts?
- Title
- Position
  -Organisation

**Comment by alexander-elgin** [comment]
@ahasemann done (see https://github.com/NRGI/rgi-assessment-tool/pull/523)

**Comment by ahasemann** [comment]
Hi Alex,

Thanks, the system still requires these fields to be completed

**Comment by ahasemann** [comment]
![user](https://cloud.githubusercontent.com/assets/12699192/17923186/d03342ba-69da-11e6-97bd-d3771c883dc4.JPG)

**Comment by ahasemann** [comment]
![user2](https://cloud.githubusercontent.com/assets/12699192/17923194/d6adaf90-69da-11e6-8b8c-c8898915fce7.JPG)

**Comment by alexander-elgin** [comment]
The production server was not updated automatically. Now it is.
