### ISSUE TITLE
Assessment list page cleanup

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#343]
There is too much information on the assessment list page. Can we collapse all the dates into a single calendar popup that only populates once an assessment has been assigned. We can call the column "Milestones". the popup should list row wise the all of the milestones currently displayed and maintain the logic regarding which milestone is shown to which user.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/348
