### ISSUE TITLE
I think the time displayed for the last edit is not always accurate

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#344]
The researcher was able to login for the first time yesterday and this morning the questions were still blank. Now the questions have a score, so it means that the researcher has been working on them,  but it is written that the assessment was last edited on 8th March at 7:26 pm.

![image](https://cloud.githubusercontent.com/assets/16592996/13816239/7d9558b4-eb85-11e5-9b64-38561e9972e2.png)

**Comment by byndcivilization** [comment]
Issue with capturing latest last edit. I believe this happens on the answer controller server side.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/347
