### ISSUE TITLE
URLs as references in the tool have multiple https

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#374]
![image](https://cloud.githubusercontent.com/assets/17277178/14214217/af5f0cc2-f833-11e5-8adf-777cb25a3d65.png)

**Comment by gjacovella** [comment]
Same for my assessments - this is what happens when I click on one of those links:

![image](https://cloud.githubusercontent.com/assets/16592996/14241859/e519c488-fa45-11e5-94f5-9f6d33b88430.png)

However, I'm able to open the links by copying and pasting them and deleting one of the https.

**Comment by byndcivilization** [comment]
Bug patched and data more or less cleaned.
