### ISSUE TITLE
References jumping to the tool homepage

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#375]
I'm reviewing Eritrea for the second time and I noticed that some of the references have the type, title and author information missing and when I click on "view here" I'm redirected to the RGI Tool homepage.

![image](https://cloud.githubusercontent.com/assets/16592996/14276663/9ab7f5cc-fb17-11e5-8708-7fde9e4afb9a.png)

![image](https://cloud.githubusercontent.com/assets/16592996/14276675/aa6146cc-fb17-11e5-8344-c9ed5f61cd90.png)

**Comment by byndcivilization** [comment]
@gjacovella this was my mistake when dealing with the http bug. I've restored this and I think its the only record corrupted but let me know if you see others.
