### ISSUE TITLE
Full assessment was sent to Bolivia

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#377]
@byndcivilization the researcher for Bolivia got the full assessment. She has completed the trial and  needs to send  it back, but she can't as the tool is telling the full assessment need to be completed. Could you help me to reverse it?

![image](https://cloud.githubusercontent.com/assets/16593022/14315431/12957d8e-fbf5-11e5-8f4a-092096d9ed9a.png)

![Uploading image.png…]()

**Comment by gjacovella** [comment]
The same just happened to the researcher for China, she can't submit the trial because she has access to the entire questionnaire. Can you please help me with this? 
![image](https://cloud.githubusercontent.com/assets/16592996/14378359/5ddf5d28-fd6c-11e5-88e6-942e62cf7ac6.png)

**Comment by DianaHartmann** [comment]
Same issue with Peru. 
![image](https://cloud.githubusercontent.com/assets/16593022/14390206/e2c04a02-fdad-11e5-9b2a-aa652dcf8195.png)

**Comment by gjacovella** [comment]
Same issue with Papua New Guinea. I sent back the assessment as the researcher couldn't address any of my flags and he received the entire assessment instead. He said that the reasons why he couldn't work on the assessment were that the assessment was not responding:
1. Editing of the description - not responding
2. Reference Required -  not responding
3. Edit Reference - not responding

I don't know if this is still the case, but now he has also access to the entire questionnaire.

I still need to review his trial questions, could you please help me with this? @byndcivilization 

![image](https://cloud.githubusercontent.com/assets/16592996/14536931/be9cd780-026c-11e6-88c2-6f880cfc5a0e.png)

**Comment by DianaHartmann** [comment]
Full assessment to Chile.Could you please help me with this?

**Comment by DianaHartmann** [comment]
Full assessment to Colombia. 
![image](https://cloud.githubusercontent.com/assets/16593022/14852074/1859ce0e-0c7c-11e6-900f-b9db08ea66cd.png)

**Comment by DianaHartmann** [comment]
@byndcivilization. Full assessment was sent to Mozambique. She needs to send back the trial. Could you please help me? Thanks.

![image](https://cloud.githubusercontent.com/assets/16593022/16038236/01267c08-321c-11e6-9e01-3eb35f07bb3b.png)
