### ISSUE TITLE
restricted autopopulate on interviewees

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#379]
The autopopulate function needs to be refined to only return interviewees that have been tagged to a given assessment. This tagging mainly happens when a new interviewee is cited but will also need to happen on the admin side.
- [x] autopopulate needs to return only those interviewees where assessments contains assessment_ID
- [x] when adding a new interviewee if the record already exists it should fire off error to say that the interviewee already exists and the user should contact the site administrator.
- [x] on the interviewee detail page for admins, there should be some ui to add interviewees to assessments manually.

**Comment by byndcivilization** [comment]
@alexander-elgin I set this to autopopulate based on user id instead of assessment id. I've left the stuff there for assessment id just incase we need to use both.

**Comment by byndcivilization** [comment]
@ahasemann do we need to restrict based on both assessmetn and user? i.e. if a user has cited on a different assessment is that fine to let them see via autopopulate or do we only want them to be able to see those interviewees that theyve cited in a given assessment?

**Comment by ahasemann** [comment]
No, doesn't need to be restricted to a specific assessment if it's the same user - I can think of two scenarios here: one user is doing a dual country and thus seperate assessments or a user is doing several countries and thus has separate assessments -  no need to restrict either of those
