### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#385]
A few different things to flag on flags:
1. If we've created a new flag, and want to close it, for example because we've noticed another element to an answer in a different question, we would click on Addressed. This would close the flag. However, if we click out of the question page (1), for example to go to a different question (2), and then come back to the original question page (1), the flag will not appear as addressed. It will still have a red background and it will be open.
2. When checking consultants' newly submitted work against our flags from the first round of reviews, sometimes they have not properly responded to the flags and we wish to leave some open. For example, I may approve 2/3 and want to leave one open. When first clicking on Addressed for the two that I wish to approve, these will close and have a green background. One would still be open. However, if I click out of the question page, and click back in afterwards, all the flags will still be open, with a red background.
3. Similar situation to above: if I try to edit the text of the flag that I wish to remain open, and click Addressed on two others, this still does not work. If I click out of the question page, and then back in, all the flags are open and red.
4. If I want to leave 1/3 flags open, I can do so by clicking Addressed on 2/3. Then, I add a new flag. In total there are 4 (2 addressed, 1 not-addressed from first round, 1 new). This allows me to keep an old flag open. If I click out of the question page and click back in, my changes are saved. However, it is not always the case that I wish to create a new flag.
5. I can also click addressed on all flags previously logged, and create all new flags for each round of reviews. This saves the changes. However, this can suggest to the researcher/peer reviewer that flags which we think they have not addressed have in fact been addressed.
@ahasemann @HumairaP @DianaHartmann @gjacovella

**Comment by HumairaP** [comment]
I have the same issues.

**Comment by HumairaP** [comment]
I clicked 2/5 flags as addressed, when on to the next question and then back to that one but they were all showing up as red - unaddressed. I then tried again by clicking on the 2 that were addressed and then pressed on the "save answer" button. This saved the two addressed flags as being addressed and left the 3 unaddressed flags open.

**Comment by byndcivilization** [comment]
all of these are issues with a disabled save button bug. basically you should save the answer state to change flag status. will push out save button later today.

**Comment by HumairaP** [comment]
I am having issues again with this.

For example: Say there are 4 flags and I click 3/4 as addressed, and press the save answer button, when I want to send the assessment back it states that I have not flagged or approved all questions. This is because the question with the flag that I did not click as being addressed is marked as "answer saved". I have to click the flag as being addressed and create a new flag, in order to be able to send the assessment back.

**Comment by isabellee** [comment]
Ditto

**Comment by byndcivilization** [comment]
Fixed. will push tonight.
