### ISSUE TITLE
When external reviewers disagree with either the score given by the researcher or peer reviewer they will need to provide evidence to support their answer. Currently the tool accepts the different score without additional evidence

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#386]

**Comment by alexander-elgin** [comment]
According to https://github.com/NRGI/rgi-assessment-tool/issues/267 an external reviewer should provide a reference if he selects an alternative answer. If the external reviewer tries to submit an alternative answer without a reference an error message _'You must add at least one reference for justification'_ will be shown.
