### ISSUE TITLE
remove restrictions on dependant questions

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#387]

**Comment by byndcivilization** [comment]
@jim215 @ahasemann this is ready to go. Get me a list of questions and I can bulk set those to dependant = true.

**Comment by byndcivilization** [comment]
@ahasemann the other option is for you or the RAs to go through and manually mark those questions that are dependant. This is done through the question detail page. The appropriate place is the box labeled Dependancy? it should be checked only if the question is a dependant question.

**Comment by ahasemann** [comment]
Do any questions have that box ticked yet, i.e. can we avoid ticking those that are in precept sections other than the SOEs/ Funds/ sub-national ones?

**Comment by byndcivilization** [comment]
everything has been defaulted to false. Basically check the box only if you are fine with not restricting citation and justification requirement.

**Comment by ahasemann** [comment]
Ok, great, we'll do that tomorrow then
