### ISSUE TITLE
RGI wsywig is very slow when the full questionnaire is deployed

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#390]
When a user is doing the trial of 10 questions, the wsywig is fine. When they pass the trial, wysiwig gets very unresponsive. it looks like all questions and all answer records are being stored as XHR data.

**Comment by alexander-elgin** [comment]
In the demo data there 2 questions only. However I do not observe any lags in the Wysiwyg editor after several trial assessments submission.

**Comment by byndcivilization** [comment]
you can see the issue in action here. http://rgi-question-staging.nrgi-assessment.org/admin/assessments-admin/answer/AL-2016-PI-001

user name = jcust
password = jcust

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/395
