### ISSUE TITLE
rgi-wysiwyg not saving text

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#392]
Submission/Mark Complete works, but saving does not.

**Comment by alexander-elgin** [comment]
textAngular (that did not have such issues) is restored in https://github.com/NRGI/rgi-assessment-tool/pull/396

**Comment by alexander-elgin** [comment]
if you save a justification without a selection nothing saves, but if you have a selection the text saves

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/397
