### ISSUE TITLE
Contact system administrator for technical assistance form data davalidation

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#398]
when I log in with researcher (user:cperry), the form data validation is not correct with first name, last name  browser version.
first name and last name can not be number, symbol.They can be only string(a-z).
It can have a negative value ex:  -2.
![screenshot from 2016-04-25 21 20 01](https://cloud.githubusercontent.com/assets/15853986/14797750/128eb77e-0b2c-11e6-9db7-b6bd8faf2e02.png)

**Comment by ion-alecsandri** [comment]
ok

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/426
