### ISSUE TITLE
Profile page information validation error

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#399]
when log in (as researcher, supervisor,reviewer,external viewer), go to the profile page.
And I updated my information.
Here, the first name and last name can not be number, or special letter(%,&..).
They must be only common string.
But it allows that, even tough the data does not be changed.
In this case the dialog can say "Invalid firstname!"
![screenshot from 2016-04-26 03 08 58](https://cloud.githubusercontent.com/assets/15853986/14804870/c81b2d66-0b5e-11e6-89cc-f5b3b6a059c1.png)

And then, when I updated my name to anna$.(At this time, the log out button is not working..)
Also the name can not be anna$.
So I delete $, and click submit button, and then that button is also not working.

I think that we need to validate the data of the user.

**Comment by alexander-elgin** [comment]
First name & last name validation is added. If the name is invalid the submit button becomes disabled and the field is highlighted.
