### ISSUE TITLE
Admin  - Create user page form data validation

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#400]
Please check the screenshot.
The phone number can not be string, it should be number or mix number & '+'.
ex: +123 456 789 456
![screenshot from 2016-04-26 04 04 29](https://cloud.githubusercontent.com/assets/15853986/14805540/ac23a312-0b64-11e6-84c0-5fd7f6a44dc7.png)

when admin create user, the user  should have  one role of supervisor, researcher, reviewer, external viewer.
But now the survey module check this with username, not email.
So one man create lots of roles(no limit) with one email.
I have created lots of roles (supervisor, reviewer,researcher) with my one email.
This is very serious issue.
If I have lots of usernames on same email, there will be many complex problems.
For example, when I forget my password, then I reset the password with sending password reset email.
But here, I can't know about which account would be reset

And for the security, the password should be more than 8 characters (including one number or special letter).

**Comment by alexander-elgin** [comment]
Is it really required that the email should be unique? Authorization is done by username. @ion-alecsandri or you like to avoid the potential issue if the authorization become based on email (not username)?

**Comment by byndcivilization** [comment]
Password validation: I think this is a reasonable requirement.
Phone number: I'm okay to validate against digits
Unique email: I dont think this is a big issue. We have potential times where wed like to have the ability to handle multiple users from a single email account. For instance, when we fire a researcher, we dont want to lose their data. the current methodology is to change their password and change their email address to a single holding email address.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/413

**Comment by alexander-elgin** [comment]
password validation is done in https://github.com/NRGI/rgi-assessment-tool/pull/415

**Comment by byndcivilization** [comment]
Just want to confirm that this will only apply to new passwords, right?

**Comment by alexander-elgin** [comment]
Yes, the password field is empty in the profile form. If the user leaves the field blank the password won't be changed.

**Comment by byndcivilization** [comment]
perfect thanks!
