### ISSUE TITLE
Admin - Createuser reset password page - The token is not found

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#401]
when I create new user, the password set up email is sent to the email address.

And it is working well, but sometimes the below issue appears.
Please check the screenshot.
![untitled](https://cloud.githubusercontent.com/assets/15853986/14806239/3191e190-0b69-11e6-8ba7-9fd09382b00b.png)

**Comment by byndcivilization** [comment]
@ion-alecsandri can you add some additional information to help us reproduce the bug? What are the exact steps that lead to this?

**Comment by ion-alecsandri** [comment]
I don't know that exactly.
I met this error accidentally, and now I can not see this error.

**Comment by byndcivilization** [comment]
Did it only happen once?

**Comment by ion-alecsandri** [comment]
yes, now I try on lots of cases,but this error does not appear again.

**Comment by byndcivilization** [comment]
Lets put this on the back burner then. It might have been an issue with the Mandril failurel from this weekend
