### ISSUE TITLE
Question Admin - Edit question - validate form data error

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#402]
When log in as admin, let's go Admin>Question Admin.
And here, select any question, and click edit button.
And then the edit dialogue appear.
any order value can not be negative number.

![screenshot from 2016-04-26 10 58 45](https://cloud.githubusercontent.com/assets/15853986/14814790/c0638802-0b9f-11e6-9cef-3f5a428d43c3.png)

And we delete button for option , it would be better appear confirm dialog such as "do you want to delete really?"

**Comment by byndcivilization** [comment]
Lets add a confirmation dialog on saving the question.
as for the ordering, yes on validation for question order.
@alexander-elgin do you know of a way to add draggability to the option divs? that might be better than makeing sure the admin adds the right order numbers.

**Comment by alexander-elgin** [comment]
@byndcivilization Yes, I also thought about it once I had seen the issue. I'll integrate https://github.com/angular-ui/ui-sortable
