### ISSUE TITLE
Question Admin - Edit question - 1

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#403]
Sometimes, after edit question I click save button, then it says like "Question data has been updated".
And the below window appears.
![screenshot from 2016-04-26 11 01 02](https://cloud.githubusercontent.com/assets/15853986/14815069/289f14a8-0ba1-11e6-87a5-45dd7a1fe489.png)
And then if I click the back button on browser, then also the empty window appear.
![screenshot from 2016-04-26 11 01 59](https://cloud.githubusercontent.com/assets/15853986/14815090/44aeb7b6-0ba1-11e6-92b2-ffb34b6d7db4.png)

**Comment by byndcivilization** [comment]
This might be an issue with node failing in the container and resrtarting. @ion-alecsandri do you have to re-login?

**Comment by ion-alecsandri** [comment]
yes, if I log in again, it works well as before.

**Comment by byndcivilization** [comment]
so to be clear, you save an edit, it gives you this screen and then requires you to login again.

**Comment by ion-alecsandri** [comment]
yes, correct

**Comment by byndcivilization** [comment]
Okay express is probably throwing an error somewhere in the save prcess. Lets get the rest of the issues around question save worked out and then come back to this to see if it still exists.

**Comment by alexander-elgin** [comment]
There is an issue https://github.com/NRGI/rgi-assessment-tool/issues/439 regarding such kind of problems

**Comment by alexander-elgin** [comment]
#439
