### ISSUE TITLE
Question Admin - Edit question - order values is not saved

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#404]
let' s go Admin>Question Admin >Edit question
And here change orders of options like below screenshot.

![screenshot from 2016-04-26 11 25 16](https://cloud.githubusercontent.com/assets/15853986/14815348/c43541fc-0ba2-11e6-887d-62026d8a09d3.png)

And click any delete button of options on right side of window.
Then the option order values rearranged.

![screenshot from 2016-04-26 11 06 43](https://cloud.githubusercontent.com/assets/15853986/14815370/e785cbcc-0ba2-11e6-9841-40b4f0a6296d.png)

**Comment by byndcivilization** [comment]
Question editing has always been a bit sketchy. this is linked to #402. I think if we can figure out a way to convert this to a draggable option it will help.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/445
