### ISSUE TITLE
Question Admin - Ordering questions error

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#405]
After edit questions. and save it then it lead us the questions list page.
But there is no correct order rule for questions.
Please check below screenshot.
![screenshot from 2016-04-26 11 05 39](https://cloud.githubusercontent.com/assets/15853986/14815459/6ebd9642-0ba3-11e6-8dee-c99dd327d54a.png)

**Comment by alexander-elgin** [comment]
The questions are grouped by precept first. Then inside the groups (precepts) you can sort the questions by any of the given fields. As I see in the provided picture the questions are ordered properly inside the groups. But indeed the precepts are ordered incorrectly. It seems that they are ordered as strings.

**Comment by byndcivilization** [comment]
Yeah lets fix the precept ordering issue. Question ordering is on #402

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/412
