### ISSUE TITLE
When trying to open an assessment in a new tab from the dashboard, you are unable to see questions.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#406]
![image](https://cloud.githubusercontent.com/assets/17277178/14848993/8856d2f6-0c68-11e6-9546-f310450fcc90.png)

![image](https://cloud.githubusercontent.com/assets/17277178/14849022/a7b0a744-0c68-11e6-9ee8-92150dcc1944.png)

**Comment by byndcivilization** [comment]
@HumairaP does this happen everytime or just once. I cant recreate this in chrome or safari on mac.

**Comment by HumairaP** [comment]
Every time. @ahasemann had the same issue earlier.

**Comment by ahasemann** [comment]
Yep, happened to me several times in both Firefox and Chrome. Currently still happening

**Comment by byndcivilization** [comment]
Okay i can recreate this. It happens sporadically for me. Session id seems to be going over but the call isnt completing. Even reload doesn't seem to load the answers. Additionally, reloading the page sometimes also causes this.

**Comment by byndcivilization** [comment]
@alexander-elgin I think this is related to the issue that came through today with assessment detail pages.
