### ISSUE TITLE
Edit document - data validation Error

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#407]
when log in as admin, and then go to doc admin.
Click Meldata button.
Click Edit Meldata button.then edit window appears.
Here are some data validation issues.
![screenshot from 2016-04-27 16 27 21](https://cloud.githubusercontent.com/assets/15853986/14858045/6dce0d7c-0c96-11e6-9bf3-c6e1335800bb.png)

The firstname and lastname of authors and editors can not be number, they should be string.
source should have a form of url , for example: http://asdfasdfasdfaf.....
year and pages can not be string.
City can not be number. 

And after input some data to this window, then click  "save document" button.
and then it does not say anything.
It can say like "Document saved" ,and then the edit data should be closed.

**Comment by byndcivilization** [comment]
First name last name: yes
url: yes if we can find an easy way to implement this that doest cause us too many headaches
year and pages: no (year could be a range for instance as could pages)
city: yes
