### ISSUE TITLE
Admin Profile Edit - data validaton module does not exist 

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#408]
when log as admin, and go to profile.
And edit some data(first name, last name).
![screenshot from 2016-04-27 16 48 41](https://cloud.githubusercontent.com/assets/15853986/14858538/55255864-0c98-11e6-9781-7aff2d52d5fe.png)

This can not be.

and eveb though we input right data , when click submit button, it does not work.
Also the log out button does not work.
I should re log in.

**Comment by byndcivilization** [comment]
Yes on validation, logout and save issues point to a session being dropped so lets open a new ticket if that appears again.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/441
