### ISSUE TITLE
Interview Admin - Edit Meldata - validation error

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#409]
log in as admin, go to in interview admin.
And click edit meldata button.
![1](https://cloud.githubusercontent.com/assets/15853986/14859136/b54538a2-0c9a-11e6-885e-25acb5fc0cb3.png)

All fields data should be validate.

**Comment by byndcivilization** [comment]
@alexander-elgin lets validate first name last name and email.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/497
