### ISSUE TITLE
Resource order can not be negative order

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#410]
log in as admin, go to Resources Admin.
and then create new block or edit existing resource.
here, the resource order can not be negative number. 
![1](https://cloud.githubusercontent.com/assets/15853986/14859505/4d823a24-0c9c-11e6-8860-72028f10af76.png)
After edit or create, the resources are be reordered by the resource order.
I think that these should be ordered by precept.

**Comment by byndcivilization** [comment]
this is the same as #411. closing
