### ISSUE TITLE
FAQs and Resources admin order can not be negative and should not be reorder by this FAQs order.

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#411]
This is same as Resources admin order error.
![1](https://cloud.githubusercontent.com/assets/15853986/14859669/1ab1cd02-0c9d-11e6-80aa-ab090a62f594.png)

**Comment by byndcivilization** [comment]
@alexander-elgin can we add validation here?

**Comment by byndcivilization** [comment]
Or actually better, just implement the dragging function we have in the question admin detail page for options.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/490
