### ISSUE TITLE
Assessment Admin - spam assessment delete function not exist

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#414]
log in as admin, go to assessment admin.
And here we can deploy new assessment.
But we can make wrong assessment, and at that time we need to delete that assessment.
But here is no this function.

**Comment by byndcivilization** [comment]
Im a bit hesitant to introduce this. Lets back burner this until we can get a sense of what sorts of checks we need to mitigate data loss.
