### ISSUE TITLE
Admin assessment - answer page - no back button does not exist

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#416]
log in as admin, go to assessment admin.
![1](https://cloud.githubusercontent.com/assets/15853986/14890068/1a153228-0d59-11e6-8a01-30169785aa8c.png)

click Albania 2016 Pilot  link.
then it will lead below page.
![2](https://cloud.githubusercontent.com/assets/15853986/14890128/550fff66-0d59-11e6-91af-9ad5efd59c51.png)

On this page we can answer assesment, and set flag, approved and so on.
Next, we need to go to before page.
But there is no back button.
We can go to before page using "Backspace" keyboard, but this does not display the content that we have saved before.

**Comment by byndcivilization** [comment]
@ahasemann whats your pref on this. You can get back to an assessmetn list via the header bar. Do we need another back button on the page?

**Comment by ahasemann** [comment]
I am not quite understanding where exactly a back button is missing - on the question page? There is a back to assessment button on the question page or are we talking about a different page?

**Comment by byndcivilization** [comment]
the suggestion is to introduce a back button that would take you back to the assessment list page. The nav bar at the top also takes you there.

**Comment by ahasemann** [comment]
From which page, the one in the second screenshot?

**Comment by byndcivilization** [comment]
yes

**Comment by ahasemann** [comment]
Ok, I think I get it now, so it's about going back to the site with all the assessments, is that correct? If so, I'm fine with how it is currently - using the top nav bar

**Comment by byndcivilization** [comment]
yeah thats my pref also. I'll close this then.
