### ISSUE TITLE
Reassign researcher/reviewer then go to homepage

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#417]
log in as admin, go to assessment admin.
And choose any assessment, and assign Researcher/or Reviewer.
after, click Reassign users to assessment button.
![1](https://cloud.githubusercontent.com/assets/15853986/14891362/3e5c6b24-0d5e-11e6-81e4-a3f32bce744c.png)

Then it will go to homepage.
It should go to admin assessment page before.

**Comment by byndcivilization** [comment]
Yes this is actually a holdover from an earlier iteration. @alexander-elgin can you add a $broadcast function that re-renders the list on dialog close?

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/440
