### ISSUE TITLE
Assign assessment to external reviews issue.

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#419]
We have already assign assessment to  3 external reviewers.
![1](https://cloud.githubusercontent.com/assets/15853986/14892273/ff8cdc86-0d61-11e6-946c-9d240ed81adf.png)

and we edit assign>external reviewers.
Here we delete one.
![2](https://cloud.githubusercontent.com/assets/15853986/14892295/16e019d4-0d62-11e6-83ff-c942a5b3bbef.png)

and we click "Assign external reviewers" button, it says nothing and does not any action.
But we refresh the page, there are 2 correct external reviewers.
![3](https://cloud.githubusercontent.com/assets/15853986/14892347/4d3198d2-0d62-11e6-90c1-e385549e8fdc.png)

**Comment by byndcivilization** [comment]
@alexander-elgin We need a confirmation message and  close dialog method here.

**Comment by alexander-elgin** [comment]
Sure. Actually I think that delete confirmation is redundant here. It will make the feature more complex. The action is not permanent. If you delete a supervisor by mistake you simply can click `Cancel` the dialog will be closed and the supervisor set will not be modified. To apply the changes you should confirm them by clicking on the button `Assign supervisor(s)`

**Comment by alexander-elgin** [comment]
@ion-alecsandri is it the same issue that was reported in https://github.com/NRGI/rgi-assessment-tool/issues/418?

**Comment by ion-alecsandri** [comment]
yes

**Comment by byndcivilization** [comment]
okay so just the confirmation message, close the dialog and broadcast changes

**Comment by alexander-elgin** [comment]
fixed in https://github.com/NRGI/rgi-assessment-tool/pull/421
