### ISSUE TITLE
Is it impossible add more than one researcher/reviewers like external reviewers?

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#420]
We can not add more than one researchers or reviewers at once.
Is this error ?
![1](https://cloud.githubusercontent.com/assets/15853986/14892658/d0a1d1a4-0d63-11e6-8006-020410c4b13b.png)

**Comment by byndcivilization** [comment]
No there is only one researcher and one reviewer per assessment.
