### ISSUE TITLE
Researcher add interview data validation~

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#422]
when you login as researcher(user:ionresearcher, pw:ahsus), then you can see assessments that the supervisor assigned.
About that assessment, you can edit, answer, review..
In here , you can add document(or add interview.)
When you add interview, the all data in that dialogue should be confirmed.
Please see the below screenshot.
 ex: the interview date can not be past, it should be future.
![screenshot from 2016-05-02 03 54 31](https://cloud.githubusercontent.com/assets/15853986/14946482/d1cd21d2-101a-11e6-9ec9-ce90ae6ce310.png)

**Comment by alexander-elgin** [comment]
The interview date cannot be a date in the future. See https://github.com/NRGI/rgi-assessment-tool/issues/138

**Comment by byndcivilization** [comment]
right

**Comment by byndcivilization** [comment]
Oh but yes there should be validation on the rest of the fields.

**Comment by ion-alecsandri** [comment]
I understood

**Comment by byndcivilization** [comment]
validate:
- interviewee name
- email address

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/498
