### ISSUE TITLE
Validation of the 'Add Document' form

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#423]
Let's take look into a "add document" instead of "add interview" like before.
![1](https://cloud.githubusercontent.com/assets/15853986/14946650/82351898-101d-11e6-9d08-c8aa1edfed8e.png)

Here the image file can not be upload.
But now I can do that.

And all data on "new document reference form" should be validated.
![2](https://cloud.githubusercontent.com/assets/15853986/14946667/c4e26e7a-101d-11e6-88d2-40d9360e86b5.png)

**Comment by alexander-elgin** [comment]
179e90ccc4047322e99e2ddb34b3ecd650bfa4ad
