### ISSUE TITLE
Reviewer role

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#425]
reviewer can only add comment to the assessment.
Is this all right?

**Comment by alexander-elgin** [comment]
No, the set of available actions depends on the assessment status. Until the assessment is submitted to the reviewer, the reviewer can submit comments on the answers only. Once the assessment is answered by the researcher and submitted then to the reviewer by the supervisor, the reviewer can review (post his answers confirmed by documents / interviews) the assessment.
@ion-alecsandri I think it is better to ask questions in Slack. If you do not have access to it, ask @byndcivilization  to grant you access, please

**Comment by alexander-elgin** [comment]
@ion-alecsandri If you any question about the app features / use cases, you can ask me. My Skype is sasha.elgin
