### ISSUE TITLE
Admin - Deploy new assessment - pop up dialogue enhancement

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#427]
Log in as admin, go to deploy assessment.
![screenshot from 2016-05-02 16 55 12](https://cloud.githubusercontent.com/assets/15853986/14959870/81fd2ba6-1089-11e6-9775-9c51ef3f286b.png)

we should select all of year,version,country, if not it does nothing.
But here it might better if  the alert "please select version" appear.

**Comment by byndcivilization** [comment]
Yeah we can add an error notifier.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/438
