### ISSUE TITLE
Supervisors need the ability to hard switch Assessment status in certain cases.

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#428]
So far, weve seen a bug that in certain cases causes a flagged trial assessment to be handed back to a researcher as a full assessment. The status is set to assessment_assigned instead of trial_started. We havent been able to reproduce the bug but in cases like this we need a way for supervisors just to flip the status instead of having to log into the database and change it manually.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/432
