### ISSUE TITLE
researcher should fill all requirements for completing assessments

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#429]
Please look at the screenshot.
![untitled](https://cloud.githubusercontent.com/assets/15853986/14981279/b9ee1644-1136-11e6-80d7-325bab329bf7.png)

log in as (user: ionresearacher, pw: ahsus).
and go to "Uruguay 2020 pilot"
here, I have picked only score, not reference, justification.
And I press "Mark complete" button, it says "answer submitted"..
But it should say "you must pick justification", "you must pick reference".

The second question, it works.

**Comment by byndcivilization** [comment]
There are certain questions that are dependant on other questions. I.e. if the researcher answers one way on a linked question, they don't have to supply additional info for these questions.
