### ISSUE TITLE
Supervisor approve answer enhancement

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#430]
The supervisor can approve the approved answer again.
This needs to be fixed.
Please look below screenshot.
![untitled](https://cloud.githubusercontent.com/assets/15853986/14987199/b52c7530-1157-11e6-9396-759ee5f5821e.png)

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/483
