### ISSUE TITLE
Researcher "Reset answer" button does not work correctly

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#433]
when you log in as researcher, you can see the "Reset answer" button about the assessment that is assigned newly to that researcher.
If you add justfication, score, reference, and then click the reset answer button,
then score, justification will be reset.
But the reference will be remained.
![1](https://cloud.githubusercontent.com/assets/15853986/14989284/add44da0-115f-11e6-8f20-92ecd68aaeba.png)
![2](https://cloud.githubusercontent.com/assets/15853986/14989426/68f81602-1160-11e6-96fc-05a9a7172731.png)

And if you submit comment, then the "Reset answer" button disappears.
Also if you click the "Save button", then "Reset answer" button disappears.

**Comment by byndcivilization** [comment]
The reset button is only availble for a fresh quesiton
