### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#435]
Well, researcher mark complete assessments and submit.
The supervisor reviews them and flag to researcher again.
then researcher mark complete them again.
During that time, I met some unknown issue.
Please check below screenshot.
![3](https://cloud.githubusercontent.com/assets/15853986/14994790/4e4a1098-117a-11e6-85eb-1e45fa1f5f7b.png)

Even though I refresh the page, but it still remains.

**Comment by alexander-elgin** [comment]
@ion-alecsandri Please, can you provide more details about the following steps:
1. The supervisor reviews them and flag to researcher again.
2. then researcher mark complete them again.
3. During that time, I met some unknown issue.

**Comment by ion-alecsandri** [comment]
researcher can complete the assessment assigned to self by supervisor.
And  submit it to supervisor for reviewing.
The supervisor can flag it and move assessment to researcher.
Then the researcher can edit flagged assessment and submit it to supervisor.
then the supervisor can review.

This process loops till the supervisor approve the answer,
And during repeating  this process, I met some issue.
Please check the link.
http://rgi-staging.nrgi-assessment.org/assessments/UY-2020-PI

**Comment by ion-alecsandri** [comment]
Uruguay 2020 Pilot Assessment

**Comment by byndcivilization** [comment]
This is an issue with network lag i think. In slower browsers this tends to happen from time to time.

**Comment by ion-alecsandri** [comment]
ok
