### ISSUE TITLE
Flag answer to approved answer ~

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#436]
This is serious issue with "save answer" function.

when I log in as supervisor, I flagged one answer to researcher.
![1](https://cloud.githubusercontent.com/assets/15853986/15010521/07e7881c-11f5-11e6-8c93-f33a4df544be.png)

and if I review this flagged answer, and click "save button", "Return to assessment menu", the the flagged answer changes into not flagged answer.
![2](https://cloud.githubusercontent.com/assets/15853986/15010545/3c64102e-11f5-11e6-8291-fc4e209b3fb3.png)
 But if I look into that answer, it was flagged as I saved before.

Also when I save the approved answer, then the approved answer changed not approved answer.

**Comment by byndcivilization** [comment]
I think this was fixed in a push to production last night. I'll push to staging and see if it still pops up.

**Comment by ion-alecsandri** [comment]
Ok, Please push~
