### ISSUE TITLE
Passing full assessmetn bug

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#437]
let's look the "Japan 2021 Pilot Assessment".
![1](https://cloud.githubusercontent.com/assets/15853986/15012179/5794e45e-11ff-11e6-9370-529c332d328f.png)

There are 2 answers.
And researcher mark complete these and submit,
![2](https://cloud.githubusercontent.com/assets/15853986/15012223/9d281c52-11ff-11e6-9a25-74bfbd5b1496.png)

And supervisor  reviews these, and move assesment to researcher again.
Log in as researcher, go to these assessment.
Then there will be 5 answers, come 3 answers newly.
![3](https://cloud.githubusercontent.com/assets/15853986/15012284/1cf6959e-1200-11e6-9b33-fe6e5434ab18.png)

**Comment by byndcivilization** [comment]
@ion-alecsandri can you tell me the exact steps that created this. This is an ongoing bug that I havent been able to recreate.

**Comment by ion-alecsandri** [comment]
I.log in as jcust, 
2.deploy new assessment called ABC
3.assign it to researcher(ionresearcher), reviewer(ionreviewer)
4.log out and log in as ionresearcher
5.complete the assigned assessment ABC(here are 2 questions)
6.submit trial for review
7.log out and log in as jcust
8.approve the ABC
9.submit this to ionresearcher agian
10. log out and log in as ionresearcher
then you will see that there are 5 questions.

Is this OK?

**Comment by alexander-elgin** [comment]
That's correct behavior. There are 2 stages of working with assessment:
1. Trial Assessment stage
2. Full Assessment stage

A trial assessment includes several questions to check the researcher / reviewer qualification. Once the trial assessment is submitted and approved by the supervisor the supervisor grants access to the entire set of the assessment questions.

**Comment by ion-alecsandri** [comment]
I understood.
