### ISSUE TITLE
403 error message.

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#439]
From time to time when we push out updates it kills the container and recreates a new one. However, client side, the browser still thinks its bootstrapped and maintains some limited browsing functionality. So for example if a user has a question opened, we push an update or the server crashes, and they fire off a save button request, the new container will return a 403 error. However this shows up as an error notifier with no content. In these cases can we either redirect to the home page, force reload, or at least add an not authorized error message please re-login?

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/446

**Comment by byndcivilization** [comment]
@alexander-elgin was this in #446?

**Comment by alexander-elgin** [comment]
The empty error message is shown because of incorrect failure case processing. As I see in the source code of our module it is expected that in failure case the response comes with `reason` field in data. In reality the response data is a string with optional error message e.g. 'Forbidden'. There are a lot of such cases in our app. https://github.com/NRGI/rgi-assessment-tool/pull/446 fixes the issue and redirects to the home page signing out the current user for the following features
- create user
- delete user
- edit user

**Comment by byndcivilization** [comment]
Awesome I'll look at that today. When you can get to it, the functions around answers are a priority...save, Mark complete, comment, etc

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/450

**Comment by alexander-elgin** [comment]
In https://github.com/NRGI/rgi-assessment-tool/pull/451 HTTP error processing was fixed for the following features:
1. view answer
2. add comment
3. delete comment
4. edit comment
5. delete reference
6. edit reference
7. save answer
8. mark answer completed
9. final choice
10. flag answer

**Comment by alexander-elgin** [comment]
answer & assessment related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/470

**Comment by alexander-elgin** [comment]
document related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/471

**Comment by alexander-elgin** [comment]
interviewee related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/472

**Comment by alexander-elgin** [comment]
question related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/473

**Comment by alexander-elgin** [comment]
contact tech, country and interviewee answer related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/474

**Comment by alexander-elgin** [comment]
resource related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/475

**Comment by alexander-elgin** [comment]
user list related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/476

**Comment by alexander-elgin** [comment]
user related HTTP request failures are processed in https://github.com/NRGI/rgi-assessment-tool/pull/477

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/479
