### ISSUE TITLE
the document reference and interview reference are exist together on same assessment?

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#442]
log in as researcher.
And to complete answer, I added 2 documents, 1 interview as reference.
Then if I click "mark complete" button, then the 2 documents disappear.
Is this OK?
please see the below screenshots.
![1](https://cloud.githubusercontent.com/assets/15853986/15035001/66d27484-1274-11e6-9669-168e937652cc.png)
![2](https://cloud.githubusercontent.com/assets/15853986/15035002/6bd3d78e-1274-11e6-9277-e77f037953c3.png)

**Comment by alexander-elgin** [comment]
No, it is definitely a bug. The references should not disappear. But how dd you do that? I cannot reproduce the issue. Is the issue repeated for any question or just for a particular one? Please, can you provide a more detailed test case description i.e. how you added the document references (uploaded from your PC, from a URL or linked an already uploaded document). What was the document mime type / extension? Which interviewee you selected a new one or an existitng one?

**Comment by ion-alecsandri** [comment]
Now I am trying add interview, but it says on any case:
"The interviewee is cited by a different user. 
Please contact your supervisor with the interviewee details!"

**Comment by alexander-elgin** [comment]
@ion-alecsandri Create an interview reference with a new interviewee

**Comment by ion-alecsandri** [comment]
Ok, Please check with this.
Chile 2016 Gold Mining Assessment

**Comment by alexander-elgin** [comment]
@ion-alecsandri Please, can you provide the answer URL?

**Comment by alexander-elgin** [comment]
It is the same case as you reported in https://github.com/NRGI/rgi-assessment-tool/issues/444. Once you marked the answer as completed you were redirected to another answer. Check the URLs in the attached pictures.
