### ISSUE TITLE
Survey workflow issues~~

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#443]
1.log in as supervisor (user: jcust, user: jcust)
2.deploy new assessment.
   I have deployed 2016 France Pilot.
3.assign this assessment to researher, reviewer, external reviewer.
here, researcher : ionresearcher, ahsus
         reviewer:      ionreviewer, a
         external reviewer : external, external
![1](https://cloud.githubusercontent.com/assets/15853986/15035159/891e7428-1276-11e6-9c36-6f8ed55fcd03.png)
4.go to this assessment and flag any question.
 I flagged "Question 1.a: Is the EITI ratified in national legislation? (Dejure)".
![1](https://cloud.githubusercontent.com/assets/15853986/15035301/6444fc6a-1278-11e6-93df-fc2b87fe8c88.png)

5.click "Return to assessment menu".
![2](https://cloud.githubusercontent.com/assets/15853986/15035323/94617806-1278-11e6-8901-68468b8ca4fc.png)
Can you see "Completed: 1 (50.00%)"? Is this ok? Is this completed really?

6.Click review button for this flagged question.
![1](https://cloud.githubusercontent.com/assets/15853986/15035439/e1b9c7d8-1279-11e6-9343-86f1928f9103.png)
7.check  "Addressed", then you can see below
![2](https://cloud.githubusercontent.com/assets/15853986/15035452/04fcd334-127a-11e6-8ede-302f1deda30e.png)
8.Click the return assessment menu button.
 then you can see the below screenshot.
![screenshot from 2016-05-05 04 31 41](https://cloud.githubusercontent.com/assets/15853986/15035500/65e8bb04-127a-11e6-9d5c-64edb6703724.png)
What I mean:
On both of cases that you check addressed, or not check addressed, if you click the "return assessment menu" button, then the same result appear.
1. To avoid upon the error, I click save answer button.
   Then below screenshot appear on both of cases that checked and unchecked
   ![screenshot from 2016-05-05 04 35 45](https://cloud.githubusercontent.com/assets/15853986/15035591/63c4b6ba-127b-11e6-9db5-d3e64901da48.png)

Any way, there is no answer (approved or flagged) even though we did.
This was issue.
but we need to pass this assessment to researcher, so we can ignore this issue.
But if the supervisor does not know about this well, then this needs to fix, too.

Then let's go with researcher.
10.Please log out and log in as researcher (ionreviewer, ahsus)

**Comment by alexander-elgin** [comment]
@ion-alecsandri Please, can you resubmit the screenshots #3, #6 and #7 with expanded precept 2? I am not sure what the logic should be but at the moment an answer can be marked as completed (a choice is selected, reference and justification are provided) but not approved yet and probably flagged. @byndcivilization In assessment statistics should we count such answer (with selected choice, provided reference and justification but flagged) as completed or not?

**Comment by ion-alecsandri** [comment]
supervisor assign the assessment to researcher, reviewer, external reviewer now.
this case is just when supervisor does not move assessment to anybody.
![1](https://cloud.githubusercontent.com/assets/15853986/15039623/6282c4f6-12a6-11e6-80dc-81c1b393bd9e.png)
But supervisor can flag it.
Click "go to answer page" on the <Precept 2: Accountability and transparency (0 of 1 approved)>.
![screenshot from 2016-05-05 09 52 05](https://cloud.githubusercontent.com/assets/15853986/15039751/3629758e-12a7-11e6-9ed5-284175a55368.png)
As you see screenshot, at the moment anybody did not answer.(supervisor did not move assessment)
But here you can check or uncheck the Addressed?
Please check it or uncheck it.
Then please click the "Return to assessment menu".
Then you can see 
![screenshot from 2016-05-05 09 58 40](https://cloud.githubusercontent.com/assets/15853986/15039895/268d2a16-12a8-11e6-9650-0b6bfa71a267.png)
if you check or not, the answer does not flagged, even though we flag it.

another case: 
if you deploy new assessment, and please repeat above action.
 !important:  Never click "Save answer" button on any case.
                    Only click "Return assessment menu".
If you click the "Save answer" button, you will see the above result.
      I mean you will meet this case: "if you check or not, the answer does not flagged, even though we flag it."

so if you try to flag assessment as soon as deploy new, then you will see those screenshot #8.

**Comment by alexander-elgin** [comment]
@ion-alecsandri If I've understood you properly you reported about 2 issues:
1. the supervisor can flag a not completed answer
2. the check box `Addressed` is active and can be set even if there is nobody assigned to the assessment

Correct?

**Comment by ion-alecsandri** [comment]
yes,
But I can understand the check box .
What is difference between checked or unchecked?

**Comment by byndcivilization** [comment]
I see whats happening here but its a bug  on our end and i cant see anyone going in to flag unanswered questions. Closing.
