### ISSUE TITLE
Researcher Edit answer UI issue

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#444]
log in as researcher, and go to Argentina 2017 Diamond Mining Assessment.
now we are editing  precept3 - 2(oversight and ...).
![1](https://cloud.githubusercontent.com/assets/15853986/15040242/0e745e88-12ab-11e6-990b-8c68a7565c58.png)
![screenshot from 2016-05-05 10 21 25](https://cloud.githubusercontent.com/assets/15853986/15040263/3c754b94-12ab-11e6-93dd-471c109cef77.png)

There are already two references, and the picking the score.

Next click "Mark complete" button.
Then below screen appear.
![1](https://cloud.githubusercontent.com/assets/15853986/15040317/afe077d4-12ab-11e6-9768-8e3ceb4128b4.png)

But we return to assessment menu and go to into this answer again, then the values we saved before remains.
![screenshot from 2016-05-05 10 21 25](https://cloud.githubusercontent.com/assets/15853986/15040345/e5f026b2-12ab-11e6-8a56-74457d2842fa.png)

So this is angular front issue.

**Comment by alexander-elgin** [comment]
It seems that the test case is incomplete and should be corrected

![correct_test_case-cropped](https://cloud.githubusercontent.com/assets/1811689/15041150/9891442a-12db-11e6-94fa-677232b6926e.png)

**Comment by ion-alecsandri** [comment]
Please check with 2021 Japan Pilot

**Comment by alexander-elgin** [comment]
@ion-alecsandri I think I know what caused you to think that the form becomes blank. Once you mark an answer as completed you are redirected to the next answer. In your case the next answer was not modified. You were redirected from the answer 2 to the answer 3.a. See the pictures 2, 3 and 4.
The bug report can be closed. Just as enhancement we can scroll top on answer navigation.

**Comment by ion-alecsandri** [comment]
right,

**Comment by ion-alecsandri** [comment]
yes, right
