### ISSUE TITLE
When researcher click "save answer", then the "reset answer" disappear

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#447]
when researcher answer one question newly, there will be four buttons.
 "Mark Complete", "Save answer", "Reset button" "Return to assessment menu".

Here if you click "save answer" button, then the "Reset button" will be  disappear.

Please check below screenshots.
![4](https://cloud.githubusercontent.com/assets/15853986/15110581/7e1b1fc8-15ea-11e6-9ae0-cd97c637e4be.png)

![5](https://cloud.githubusercontent.com/assets/15853986/15110584/84df2fac-15ea-11e6-8b37-62f32a11fd62.png)

**Comment by byndcivilization** [comment]
All reset does is reset to the last saved version. This only really makes sense when an answer is completely fresh.
