### ISSUE TITLE
Document Admin Function 

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#448]
I edited a title of a document. However, the dialog does not close or notify when the save is complete.

**Comment by alexander-elgin** [comment]
I've reproduced the issue. I am fixing it now.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/449

**Comment by DianaHartmann** [comment]
@alexander-elgin @gjacovella 
Hi Alex, having the same issue today. I'm trying to change the title of a reference for Papua New Guinea assessment, Q15.2, the tool does not let me do it. the dialog does not close or notify when the save is complete. Could you please help me?

**Comment by alexander-elgin** [comment]
@DianaHartmann @gjacovella The issue was fixed in the development branch. As I can see the fix has not been applied yet to the production server neither to the staging server. Usually @byndcivilization does it.

**Comment by DianaHartmann** [comment]
@ahasemann @alexander-elgin thanks. @byndcivilization Chris could you please help me with this? Thanks
