### ISSUE TITLE
Editing document metadata - Save button missing 

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#454]
The save button is missing when Diana is trying to edit document metadata (she is now on leave, so posting for her). No one else is having this issue for the moment
@DianaHartmann

**Comment by ahasemann** [comment]
https://files.slack.com/files-pri/T0312GL2V-F189ZS918/pasted_image_at_2016_05_12_10_44_am.png

**Comment by ahasemann** [comment]
https://files.slack.com/files-pri/T0312GL2V-F189CQ41J/pasted_image_at_2016_05_12_10_44_am.png

**Comment by ahasemann** [comment]
![pasted image at 2016_05_12 10_44 am](https://cloud.githubusercontent.com/assets/12699192/15221982/9d41bea2-1865-11e6-9b08-30e03befe869.png)

**Comment by ahasemann** [comment]
![pasted image at 2016_05_12 10_44 am 1](https://cloud.githubusercontent.com/assets/12699192/15221988/a3eb5038-1865-11e6-97b3-c4892fb6cb86.png)

**Comment by alexander-elgin** [comment]
I see on the pictures a big empty space after the editors form group. That's really weird. However I opened the edit metadata dialog for the same document and did not observe any issue. See the picture below.
![edit-document-metadata](https://cloud.githubusercontent.com/assets/1811689/15240805/ec68240a-190d-11e6-904e-d54d5bd9b0b5.png)
I used both Crome and Firefox. Perhaps it is a browser-specific issue. What browser do you use? Did you observe the issue only once?

**Comment by ahasemann** [comment]
Hi, responding on Diana's behalf since she is on leave. She uses Chrome, she's encountered the same issue for several days, logging in and out again has not helped either. 

She's the only one encountering the issue though, it works fine for everybody else now. It seems like there's not an obvious cause, so maybe we leave this until she's back?
