### ISSUE TITLE
Can we get a home button that allows you to return to the landing page? 

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#456]
By landing page, I mean this page:

![landing page](https://cloud.githubusercontent.com/assets/12699192/15245212/1fdbf034-18fd-11e6-87be-97fa55079217.JPG)

**Comment by alexander-elgin** [comment]
I can suggest to increase font size of the abbreviation RGI in the top menu bar and assign the link to it. Or we can replace the phrase 'Technical assistance' with one of the icons below
![support](https://cloud.githubusercontent.com/assets/1811689/15383634/6b25f6d0-1db6-11e6-8b7c-8d57aef8eff2.png)
![operator_support_boy-512](https://cloud.githubusercontent.com/assets/1811689/15383643/79a2be00-1db6-11e6-8c99-6b3327a2b0ec.png)
![support_woman-512](https://cloud.githubusercontent.com/assets/1811689/15383647/7f673fdc-1db6-11e6-808a-8ebe4b1445aa.png)
I many apps e.g. Ubuntu for help and support a life-ring icon is used. We can use a life-ring / support icon from the font-awesome icon set that we use already
![life-ring](https://cloud.githubusercontent.com/assets/1811689/15383686/c2797d44-1db6-11e6-9e02-764dd3b7eb69.png)
Perhaps someone else has better ideas?

**Comment by ahasemann** [comment]
To clarify, are you suggesting to add a link to the welcome page to the RGI abbreviation and then making the technical assistance link an icon? 

If so, the technical assistance link is fine as it is, no need to make any changes there. 

What would be useful would be adding a home button (either spelled out as "home" or with a house icon).

**Comment by alexander-elgin** [comment]
@ahasemann Like this?
![home button](https://cloud.githubusercontent.com/assets/1811689/15468916/c83fce36-2108-11e6-96a2-91d83005239a.png)

**Comment by ahasemann** [comment]
Yes, exactly!

**Comment by alexander-elgin** [comment]
OK, done in https://github.com/NRGI/rgi-assessment-tool/pull/480

**Comment by ahasemann** [comment]
Brilliant thanks!
