### ISSUE TITLE
After supervisor select final answers, the workflow stopped~

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#457]
Now the supervisor selected final answers about  all questions.
![screenshot from 2016-05-13 11 12 38](https://cloud.githubusercontent.com/assets/15853986/15245025/1be2def8-18fc-11e6-9a90-0226d88a6fcf.png)
Click "Move assesment", then there will be 4 actions.(send back to Jim Cust,Move to internal review, Move to external review, Final approval)
![2](https://cloud.githubusercontent.com/assets/15853986/15245055/503a751c-18fc-11e6-8601-29b819b4dc61.png)

When the supervisor select "Send back to Jim Cust", then below error appear.
![3](https://cloud.githubusercontent.com/assets/15853986/15245113/a093c414-18fc-11e6-8674-a4a1ce30f7b4.png)
And here , if I cancel and reclick the "Move assessment" button, then the below issue appears.
![4](https://cloud.githubusercontent.com/assets/15853986/15245243/3e254cfc-18fd-11e6-977b-fb2fb8f55719.png)

When the supervisor select "Move to internal review", then below error appear.
![1](https://cloud.githubusercontent.com/assets/15853986/15245293/8e3f4328-18fd-11e6-81ec-48dfac4f1523.png)

When the supervisor select "Move to external review" and "Final approval", then below error appear.
![1](https://cloud.githubusercontent.com/assets/15853986/15245396/16b1d0ae-18fe-11e6-9f3b-eaf89b95b84b.png)

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/485
