### ISSUE TITLE
The same interviewee is linked to the Gabon and Turkmenistan assessment

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#458]
![interviewee](https://cloud.githubusercontent.com/assets/12699192/15245757/82b23e7c-1900-11e6-8d46-49394fccfdbb.JPG)

**Comment by ahasemann** [comment]
I assume this happened when the auto-populate function for interviewees was not restricted yet, this interviewee should only be linked to the Gabon assessment. The Turkmenistan interviewee is a different one and needs a separate record.

**Comment by byndcivilization** [comment]
We'll  tackle this in post assessment data cleaning.
