### ISSUE TITLE
user profile password error

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#459]
In any case when I log in with any role such as supervisor,researcher, reviewer and change password, the error occurs.

Please check below screenshot.
1 log in as jcust,jcust
2.go to profile(Jim Cust)
3. Change password
Here I have entered "asdASDF123", so it includes all conditions(at least one lower character, upper character, number).
But it will make error message.

![1](https://cloud.githubusercontent.com/assets/15853986/15380799/2d19d1f6-1d82-11e6-8839-4037ade40f9d.png)

**Comment by alexander-elgin** [comment]
Please, read the error message carefully. It is written that the password length should be between 6 and **8** characters. The length of the password you used is 10.

**Comment by ion-alecsandri** [comment]
ok
