### ISSUE TITLE
External reviewer - completed Assessments Error

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#460]
Please log in as external reviewer (user: external, pass:external), go to assessments.

And here, there should 'comment on assessment' button if the number of completed answers + number of approved answers is at least 80% of the whole answers number.
Else there should an inactive button 'Waiting for completion'.

Please check the screenshot.
![2](https://cloud.githubusercontent.com/assets/15853986/15391271/ec2f3b58-1dc8-11e6-89f1-065d99a886f3.png)

**Comment by alexander-elgin** [comment]
At the moment I see the following:
![assessment-list](https://cloud.githubusercontent.com/assets/1811689/15393750/cdc0be62-1df0-11e6-8a45-57c95af8a934.png)
![australia](https://cloud.githubusercontent.com/assets/1811689/15393792/f84b4bde-1df0-11e6-9e0e-60b22cf02d31.png)
![china](https://cloud.githubusercontent.com/assets/1811689/15393779/ed5adabe-1df0-11e6-941f-e27db59bed59.png)
![argentina](https://cloud.githubusercontent.com/assets/1811689/15393963/d95b6c6c-1df1-11e6-887a-7ef79a230ccb.png)
![france](https://cloud.githubusercontent.com/assets/1811689/15393818/1fcd9df6-1df1-11e6-9175-6dea62793832.png)
![uruguay](https://cloud.githubusercontent.com/assets/1811689/15393831/2b1ca83c-1df1-11e6-8b15-e384369dae76.png)
![usa](https://cloud.githubusercontent.com/assets/1811689/15393837/318a7d34-1df1-11e6-9e44-bec65b025189.png)
There is no contradiction. The assessment China 2021 is approved. Among the rest ones only the assessment Australia 2020 is completed for at least 80%.

**Comment by alexander-elgin** [comment]
@ion-alecsandri Is it still an issue?
