### ISSUE TITLE
Enhancement~

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#461]
can we add "Go Back" button or link  that return from 
![4](https://cloud.githubusercontent.com/assets/15853986/15391406/afb83390-1dc9-11e6-8a96-f059392490ee.png)

to 
![3](https://cloud.githubusercontent.com/assets/15853986/15391428/d03f902c-1dc9-11e6-8f6e-e2d604041f68.png)?

At the moment, we can only go back previous page with pressing backspace keyboard(browser provides).
This is not good.

**Comment by alexander-elgin** [comment]
It seems that you made already the suggestion and it was declined in https://github.com/NRGI/rgi-assessment-tool/issues/416.
