### ISSUE TITLE
The buttons for external reviewers are restored~

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#464]
log in as external reviewer and go to assessments.
Then you will see the below screenshot.
![5](https://cloud.githubusercontent.com/assets/15853986/15400708/1febef1e-1df5-11e6-98d7-e23186aa0653.png)

As you see, there is only one button "Comment on assessment".
And click this button, and go back.
then you will see right buttons. the all buttons are restored.
![7](https://cloud.githubusercontent.com/assets/15853986/15400745/47b6ea6c-1df5-11e6-84ee-6eb26c63676e.png)

**Comment by alexander-elgin** [comment]
There are several issues reported which are caused by history back (browser back button). Perhaps it would be better to disable history back in the app. @ion-alecsandri, @byndcivilization what do you think?

**Comment by ion-alecsandri** [comment]
I think that that is a good idea.
But I think this kind of issues should be fixed in the future.

**Comment by alexander-elgin** [comment]
history back is disabled in https://github.com/NRGI/rgi-assessment-tool/pull/467
