### ISSUE TITLE
External reviewer can add interview/document now.

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#465]
I think that we agreed that the external reviewers can only comment to answer.

but now, the external reviewer can add reference like researcher/reviewer.

![8](https://cloud.githubusercontent.com/assets/15853986/15401051/818bd62a-1df6-11e6-9985-8fd071610d48.png)

**Comment by alexander-elgin** [comment]
At the moment an external reviewer can
- confirm the researcher answer;
- confirm the reviewer answer;
- select an alternative answer.

In the first two cases he does not need to provide a reference (justification only is required). In the third case he **should** provide at least one reference (justification is not required).
