### ISSUE TITLE
File upload of file 468MB causes 'empty document title' error message

### ISSUE THREAD

**Issue by alexander-elgin** [NRGI/rgi-assessment-tool#468]
However the document title is set in the form

**Comment by byndcivilization** [comment]
Its actually a network time out "Failed to load resource: The network connection was lost." Rather than trying to deal with this it might make sense just to recommend compressing the pdf.

**Comment by alexander-elgin** [comment]
Yes, that's right. An error message about file size should be shown if a user tries to upload a big file.

**Comment by alexander-elgin** [comment]
I set the file size limit to 400MB in https://github.com/NRGI/rgi-assessment-tool/pull/469. The limit value can be changed easily.
