### ISSUE TITLE
Sunniva, Giulia and Isabelle have overlapping assignments

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#481]
![image](https://cloud.githubusercontent.com/assets/16592996/15473180/a53f18c2-20f6-11e6-8430-e8880303d58d.png)

E.g. it appears that I have 30 countries and Isabelle still has 10

**Comment by byndcivilization** [comment]
That was requested during the initial build.

**Comment by gjacovella** [comment]
@ahasemann

**Comment by ahasemann** [comment]
@byndcivilization I don't remember that conversation, what was the rationale for keeping assessments linked to supervisors even if the supervisor gets changed? Can this be changed?

**Comment by byndcivilization** [comment]
Not sure what the reasoning was on your end, but I asked if you wanted a single admin for each assessment or the ability to handle multiples. You said multiples.

**Comment by byndcivilization** [comment]
It can be changed but not sure what having multiple admins assigned to an assessment hurts.

**Comment by ahasemann** [comment]
Ok, thanks, not sure what my thinking there was. It seems like changes are not always being recorded properly atm, e.g. Mali was still being shown as being supervised by Isabelle even though Giulia changed this. It's showing up under Giulia's assessments as well though, but notifications continue to go to Isabelle's account rather than to Giulia

**Comment by byndcivilization** [comment]
There are two parts here. One is the assessments that show up on the user list. Thats a bug in that when you reassign an assessment it doesnt remove them from the old admin. The other is emails and that may be an issue with assessments not being reassigned. Im showing at least one congo assessment assigned to Isabella.  I have no idea how many other ones are.

**Comment by byndcivilization** [comment]
Ive removed the ones that Isabella is no longer assigned to. Shes still the only supervisor for Congo and Morocco.

**Comment by ahasemann** [comment]
Congo (DRC) is not reassigned yet because it's been on hold while the researcher gets replaced.

**Comment by ahasemann** [comment]
Thanks! Giulia is checking for Morocco.

**Comment by ahasemann** [comment]
Mali was reassigned already to Giulia though and the emails still went to Isabelle. Giulia's reassigned it to herself again so we'll see if that resolves anything

**Comment by byndcivilization** [comment]
Do you have access to Isabellas account to confirm this?

**Comment by ahasemann** [comment]
Yes, I do. Have forwarded you the email in case that helps

**Comment by byndcivilization** [comment]
History is showing that Mali wasnt reassigned until today. As of Sun May 22 2016 09:43:04 GMT-0400 (EDT) Isabelle was still assigned.

**Comment by ahasemann** [comment]
That's strange, we checked the assignments this morning when I saw the email and it did already show Mali as assigned to Giulia on the user admin page

**Comment by byndcivilization** [comment]
I'm closing this. Go ahead and reopen if it shows up again.
