### ISSUE TITLE
Anyone logged into the tool is automatically logged out after a couple of mins.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#482]
This is also happening to consultants. @gjacovella has two consultants (Gabon and Chad) who came across the same issue.

**Comment by gjacovella** [comment]
![image](https://cloud.githubusercontent.com/assets/16592996/15498560/079e0626-2198-11e6-9523-1dac7a9d5f46.png)

**Comment by alexander-elgin** [comment]
@gjacovella, @HumairaP are you able to reproduce the issue? I am online for 10 minutes and I am not encountering anything like this. Is the issue repeated or several users reported about it at about the same moment? Actually all users become unauthorized once the app is updated (for more details see https://github.com/NRGI/rgi-assessment-tool/issues/439). Hence we log the user out by force and ask them to re-login. As I see the app was updated yesterday. It can be that several users encountered the issue at that moment.

**Comment by gjacovella** [comment]
Sunniva has reported that in her case she can stay logged in from 1 to 15 minutes at the time, in my case not more than 5 minutes.

**Comment by gjacovella** [comment]
![image](https://cloud.githubusercontent.com/assets/16592996/15499878/398588b6-219e-11e6-9552-adb4be559126.png)
 Load question data failure

**Comment by gjacovella** [comment]
Now I'm logged in but the tool is completely frozen:
![image](https://cloud.githubusercontent.com/assets/16592996/15499941/74e57cb8-219e-11e6-8090-f2cf85d201c0.png)

**Comment by alexander-elgin** [comment]
Yes, I have encountered the issue on http://rgi.nrgi-assessment.org/. That's really weird. But on http://rgi-staging.nrgi-assessment.org I am remaining authorized.

**Comment by gjacovella** [comment]
We have received another complaint from a consultant. They say that they can't save their answers and that when they are logged out they lose their data.
In regards to the staging tool, we don't usually work on it so we haven't tried.

**Comment by alexander-elgin** [comment]
I am online for 14 minutes. During this period I was always active (I was doing something sending requests to the back end). I am not sure but It can be that the users become unauthorized because of the inactivity.
