### ISSUE TITLE
Is this a broken link from our end? 

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#484]
@byndcivilization Do you think the attached link is a problem on our end? the researcher has attached 2 different documents, and both showed up "this XML file does not appear to have any style information associated with it" when opened them. 

![image](https://cloud.githubusercontent.com/assets/16593022/15611484/72d8ad92-2422-11e6-9756-ac09cf5924f0.png)

**Comment by byndcivilization** [comment]
Yeah that was an issue of a bad variable passed into the system. Ive updated the record so it should be good now.

**Comment by byndcivilization** [comment]
Please let me know if you see any more like this.

**Comment by DianaHartmann** [comment]
@byndcivilization. Same problem as before.

Q. 82.6 - Philippines
-[ ] https://s3.amazonaws.com/'rgi-documents'/0da513499085a89352e9173455be067ed2727534.pdf

**Comment by DianaHartmann** [comment]
Same for Q. 83.6

- [ ] https://s3.amazonaws.com/'rgi-documents'/7cfa4a5f868a5ec93c29aeab2f58a5ee286128e8.pdf

**Comment by byndcivilization** [comment]
@DianaHartmann they should be good now.

**Comment by DianaHartmann** [comment]
@byndcivilization 

Q. 86.6
- [ ] https://s3.amazonaws.com/'rgi-documents'/5ae8439ef141a5a2b84cb2798ea0d95efea23e17.pdf

**Comment by DianaHartmann** [comment]
96.6 Philippines

- [ ] https://s3.amazonaws.com/'rgi-documents'/a6df3486df9ad113640175fe87c2ca637bf240cb.pdf

**Comment by DianaHartmann** [comment]
@byndcivilization Do the links need to be fixed one by one? I have several link with the same problem.

**Comment by byndcivilization** [comment]
Ive got some time now so ill see if i can hit them in bulk. Just to clarify whats happening, we store docs in whats called a bucket. I specify the bucket name when i start up the application. There was about a 2-3 hour window where the bucket name was 'rgi-documents' instead of rgi-documents. Because of that the URL is bad but also the PDF never made it to our storage area. So I need to find the document and fix the link. There are about 61 docs left fell in this window. However if the researcher didnt supply a source url, i need the researcher to send me the actual document.

**Comment by byndcivilization** [comment]
okay looks like about 25 documents left that I dont have links to the source.

**Comment by DianaHartmann** [comment]
@byndcivilization. Thank you so much.

Here is the link and URL to another one.

Q. 13.2 Philippines

- [ ] https://s3.amazonaws.com/rgi-documents/5d94846efe3b70d00d4a793138a1fc757ea1dd8e.pdf

http://www.mgb.gov.ph/2015-05-13-01-44-56/2015-05-13-01-47-51

**Comment by byndcivilization** [comment]
file extension was wrong (supposed to be png). Should be good now.

**Comment by HumairaP** [comment]
Iran Q118
- [ ] https://s3.amazonaws.com/'rgi-documents'/ce991db80af5f88c16a76cff9de85c8080b79d6f.pdf

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/15853005/37a8d428-2c9b-11e6-87c5-3b548832019e.png)

**Comment by byndcivilization** [comment]
@HumairaP I need either the original document or a link  to it.

**Comment by HumairaP** [comment]
I have flagged it and have asked the R for it.

**Comment by sgautvik** [comment]
I'm getting the same for Zimbabwe:
- [x] Q 31.3 + 51.4:
- https://s3.amazonaws.com/rgi-documents/38438e16727032ed24ebecd811464d6d9861e341.pdf 
- Finance Act Amendment: http://sp.zimra.co.zw/Formstest/Legislation/finance%20act%202304updated.pdf 
- [x] Q 31.3+52.4 
- https://s3.amazonaws.com/rgi-documents/43e9e17351eec12188cb258c2899bbd198f1051f.pdf 
  -Indigenisation and Economic Empowerment:
  http://www.nayoyouth.org/docs/Zimbabwe's%20Indigenisation%20and%20Empowerment-Act.pdf
- [x] Q 53.4
- https://s3.amazonaws.com/rgi-documents/fc7273c5bfd5565363f00c3e72830a521c64b6d0.pdf
- Income Tax Act: http://sp.zimra.co.zw/Formstest/Legislation/income%20tax%20act%202306updated.pdf
- [x] Q 54.4
- https://s3.amazonaws.com/rgi-documents/13ef63caae2b4dd507723581626aa3c2065f0c63.pdf
- Gold Trade Act: http://www.law.co.zw/downloads/statutes/21/Gold%20Trade%20Act.pdf
- [x] Q 55 + 63 + 64 
- https://s3.amazonaws.com/rgi-documents/5b6af6023bda07aea34b88f219f105e5eb5a7abe.pdf
- Revenue Authority Act 1999: http://sp.zimra.co.zw/Formstest/Legislation/revenue%20authority%20act%202311updated.pdf
- [ ] Q 59 + 60 + 61
- https://s3.amazonaws.com/'rgi-documents'/4a85b0a881f70694e53cec390aee415ccbf6cf94.pdf
- MISSING

Do you need the original documents?

**Comment by byndcivilization** [comment]
@sgautvik either the original doc of a good link to it.

**Comment by sgautvik** [comment]
Waiting for the final document from the reseracher.

**Comment by sgautvik** [comment]
South Africa
Q9, 10, 11, 12, 13: 
https://s3.amazonaws.com/'rgi-documents'/0184731b8ef28baa98bd9c988baa95505c0abdb7.pdf

**Comment by byndcivilization** [comment]
@sgautvik im aware of the list of documents that are corrupted. Anything you come across are ones that the researcher didnt supply a a good source link to. For any of these, I need either the document or a like to the document.

**Comment by gjacovella** [comment]
Timor Leste

Q. 66
Decree Law No.13/2005 Timor-Leste Petroleum Activities (This is the document: http://anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Petroleum%20Activities%20Law%20No.13-2005%C2%A0/$File/Law-2005-13-Petroleum%20activities.pdf?openelement)

- [ ] https://s3.amazonaws.com/rgi-documents/2067bc318a7751dbafad0e7307740af332953850.pdf?openelement

Petroleum Mining Code (This is the document: http://anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Petroleum%20Mining%20Code/$File/PMCtoCoM0602.pdf?openelement)

- [ ] https://s3.amazonaws.com/rgi-documents/38c5cbed9b797cf4b0f2b4c8e03b763943e25b20.pdf?openelement

Q. 68
ANPM Annual Report 2014 (This is the document: http://anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Annual%20Report%202014%20rev%20English/$File/Annual%20Report%202014%20rev%20English.pdf?openelement)

- [ ] https://s3.amazonaws.com/rgi-documents/9e1e41e28ec8b0ae145d0556d918e483eef9a39e.pdf?openelement

Q. 72 Decree Law No.5/2011 Environmental License (This is the document: http://anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Environmental%20Licensing-Decree%20Law%20No.5-2011/$File/DECREE%20LAW%205-2011-ENVIRONMENTAL%20LICENSING.pdf?openelement)

- [ ]  https://s3.amazonaws.com/rgi-documents/1a06fb38826b459747ab1f810f914070d6efe438.pdf?openelement

**Comment by gjacovella** [comment]
Timor Leste:

Q. 29 PSC JPDA 11-106 (This is the document: http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-JPDA%20PSC%2011%20-%20106/$File/JPDA%20PSC%2011%20-%20106.pdf?openelement)

- [ ] https://s3.amazonaws.com/rgi-documents/98b7cb432fafbcf06b3be003ba43ac0c8ed5bbee.pdf?openelement

**Comment by gjacovella** [comment]
Timor Leste

Q. 83 
TIMORGAP E.P Annual Report 2013 (This is the document: https://www.timorgap.com/databases/website.nsf/vwAllNew2/Resource-Report_2013/$File/TG%20Annual%20Report%202013%20%5BEnglish,%20Portuguese_%20for%20public).pdf?openelement)

- [ ] https://s3.amazonaws.com/rgi-documents/30ac66da8b67c07c3166f0439ebfabc86e8bac4a.pdf?openelement

Q. 100
TimorGap Newsleter April 2016 (https://www.timorgap.com/databases/website.nsf/vwAllNew2/Resource-Newsletter%20of%20April%202016/$File/Newsletter%20of%20April%202016.pdf?openelement)

- [ ] https://s3.amazonaws.com/rgi-documents/c61b4175ccd15246db74760874439c25f440b5d6.pdf?openelement

**Comment by sgautvik** [comment]
South Africa
Q9, 10, 11, 12, 13: 
[sami_2013-2014.pdf](https://github.com/NRGI/rgi-assessment-tool/files/346174/sami_2013-2014.pdf)

- [ ] https://s3.amazonaws.com/'rgi-documents'/0184731b8ef28baa98bd9c988baa95505c0abdb7.pdf

**Comment by gjacovella** [comment]
Timor Leste
Q3. (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-RO-Annual%20Report%202015%20ENGLISH%20FINAL/$File/RO-Annual%20Report%202015%20ENGLISH%20FINAL.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/37c87d0673a6413db0d559799ca5ec4ecaa6bc3e.pdf

**Comment by gjacovella** [comment]
Timor Leste
Q. 51 "A Model of PSC for Onshore Area, Key Terms and Conditions"  (the researcher is on holiday, so he will send me the document when he's back in August)
- [x] https://s3.amazonaws.com/rgi-documents/d664d773153baea3f2135c5857b52f710e2ccf59.pdf

**Comment by gjacovella** [comment]
Timor Leste
Q. 71 Timor Gap report (https://timorgap.com/databases/website.nsf/vwAll/Resource-Full_TIMOR%20GAP%202015%20Annual%20Report_EN_Final/$File/TIMOR%20GAP%202015%20Annual%20Report_EN_Final.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/f46b88b3b7fd3ecf58185a6aa3ae6a6fdcb46e46.pdf

**Comment by HumairaP** [comment]
**Iran** - Have emailed you the documents that the researcher has sent - but will do so again.

Q117 The law on adjustment of the government's fiscal rules
- [x] https://s3.amazonaws.com/rgi-documents/8af2bd9770785824c267e8c84c030e1a80620ab3.pdf

Q118 NDF offers fund to the government
- [x] https://s3.amazonaws.com/rgi-documents/bb0e60e4d81ae134ad2181a3cbace9d94bcbac2b.pdf

Q119
The bylaw for the National Audit Organisation regulations
- [x] https://s3.amazonaws.com/rgi-documents/b9d081b538b18e574e497e72c02b9e82e20a849e.pdf

The law on adjustment of the government's fiscal rules
- [x] https://s3.amazonaws.com/rgi-documents/8af2bd9770785824c267e8c84c030e1a80620ab3.pdf

Q120
The law on adjustment of the government's fiscal rules 
- [x] https://s3.amazonaws.com/rgi-documents/8af2bd9770785824c267e8c84c030e1a80620ab3.pdf

Q156 NDF denies allegations
- [x] https://s3.amazonaws.com/rgi-documents/a491e8aa2ff30102e2515d0f775ec4d300703a0b.pdf

NDF offers fund to the government
- [x] https://s3.amazonaws.com/rgi-documents/bb0e60e4d81ae134ad2181a3cbace9d94bcbac2b.pdf

Q166
NDF Website
- [x] https://s3.amazonaws.com/rgi-documents/b9cb21722c72098f89da845e03ded3ae49ffdad9.pdf

NDF Statute is permanent
- [x] https://s3.amazonaws.com/rgi-documents/4d67698028e1a647b000a505419ad6d82f948a07.pdf

Q168 Parliament ratification for NDF
- [x] https://s3.amazonaws.com/rgi-documents/a713e44f3fe4b29be62ee0303f732bf175334855.pdf

**Comment by gjacovella** [comment]
Timor Leste
Q29 
Decree law no.1-2012 Downstream Sector (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Downstream%20Decree-Law%201-2012%20-%20English/$File/Decree-Law%20No.%201-2012%20on%20Downstream%20Sector%20-English%20Version.pdf?openelement) 
- [x] https://s3.amazonaws.com/rgi-documents/29b7dcaa76354e2153b948ea42772d3a15a30bab.pdf

Regulation no.2-2014 First Amandment to Regulation 1-2012 (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-First%20Amendment%20to%20Regulation%20No.%201.2012%20on%20Administrative%20Procedures.%20Requirements%20and%20Fees%20(English)/$File/First%20Amendment%20to%20Regulation%20No.%201.2012%20on%20Administrative%20Procedures.%20Requirements%20and%20Fees%20(English).pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/f5a4193291d51e0531dcba7791eee32026eea446.pdf

Regulation no.2-2012 Downstream Activity Inspection (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Downstream%20Activity%20Inspection%20Division%20Regulation%20(Eng)%20/$File/Downstream%20Activity%20Inspection%20Division%20Regulation%20(Eng).pdf?openelement) 
- [x] https://s3.amazonaws.com/rgi-documents/668d4105c65db0218d2c92031a1d887b2dbaccb7.pdf

First Amandement to regulation 1/2013 instalation and operation fuel filling stations (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-First%20Amendment%20to%20Regulamentu%20No%201.2013.%20on%20Installation%20and%20Operation%20of%20Fuel%20Filling%20Stations%20(English)/$File/First%20Amendment%20to%20Regulation%20No.%201.2013%20on%20Installation%20and%20Operation%20of%20Fuel%20Filling%20Station%20(English).pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/1ecc66e26ac7cef68b6f1dba881c2236b4c2ae78.pdf

First Amandement to Regulation No.1-2014 On Fuel, Biofuel, Lubricants Quality Standard Specifications (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-First%20Amendment%20to%20Regulation%20No.%201.2014%20on%20Fuel.%20Biofuel%20and%20Lubricant%20Quality%20Standards%20and%20Specifications%20(English)/$File/4.%20First%20Amendment%20to%20Regulation%20No.%201%202014%20on%20Fuel.%20Biofuel%20and%20Lubricant%20Quality%20Standards%20and%20Specifications%20(English).pdf?openelement) 
- [x] https://s3.amazonaws.com/rgi-documents/06410023460de136b2293ea9d82bbd46b6599c49.pdf

Q. 38
ANPM Annual Report 2008 (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-2008%20ANP%20Annual%20Report/$File/2008%20ANP%20Annual%20Report%20_Final.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/176f422d248c129f61c95d7e714291813bf8ed04.pdf

ANPM Annual Report 2009 (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-2009%20Annual%20Report/$File/FINAL-2009%20Annual%20Reportt_FOR%20PRINT_C.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/fc5d9dacf085e3997df7739e7044e9b1021bfe9b.pdf

ANPM Annual Report 2010 (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-2010%20ANP%20ANNUAL%20REPORT/$File/2010%20ANP%20ANNUAL%20REPORT.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/14f25ec67101c06526f5f4b0909de1ffd77f7c66.pdf

ANPM Annual Report 2011(http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-2011%20Annual%20Report/$File/ANP%202011%20Annual%20Report.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/ac5c53b858191be925a1ee130674ca2175107dfa.pdf

ANPM Annual Report 2012 (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-2012%20ANP%20ANNUAL%20REPORT/$File/2012%20ANP%20ANNUAL%20REPORT.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/dd48616ebf165dc7de4882110637f3be8dc2f840.pdf

ANPM Annual Report 2013 (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-FINAL%20-%20Annual%20Report%202013-ENGLISH/$File/FINAL%20-%20Annual%20Report%202013-ENGLISH.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/f3036c29fc72c282df3cc49178f1e333419d54da.pdf

**Comment by gjacovella** [comment]
Timor Leste

Q. 104
- Production Sharing Contract key terms and conditions Model for Onshore (https://www.timorgap.com/databases/website.nsf/vwAllNew2/Resource-PSC%20Principal%20Terms%20and%20Conditions/$File/PSC%20Principal%20Terms%20and%20Conditions.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/ce0e7e1c530222b4f56bbd824b7890185600b5fd.pdf
- Model joint Operating Agreement between TimorGap and Join venture (consultant is on leave for a month, I don't have the original document)
- [x] https://s3.amazonaws.com/rgi-documents/af66f22f7d20de8b1fcaae2726ecae238a246d65.pdf

Q. 105
- Draft Comercial Agreement for PSCs Onshore Area (https://www.timorgap.com/databases/website.nsf/vwAllNew2/Resource-Draft%20Commercial%20Agreement/$File/Draft%20Commercial%20Agreement.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/b641071988544c7c264fa863140c41a5aa07015a.pdf
- Request For Proposals of Block A Onshore Area (https://www.timorgap.com/databases/website.nsf/vwAllNew2/Resource-RFPTG16001%20%20Block%20A/$File/RFP_TG_016_001%20Block%20A.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/5254aa387bc1d9bcce8acf289602894cb6eefd19.pdf

Q. 109
- Interim Petroleum Mining Code for Joint Petroleum Development Area (http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Interim%20Petroleum%20Mining%20Code/$File/JPDA%20Interim%20PMC%202%20April%2003.pdf?openelement)
- [x] https://s3.amazonaws.com/rgi-documents/5254aa387bc1d9bcce8acf289602894cb6eefd19.pdf

**Comment by HumairaP** [comment]
Iran Q168
- [ ] https://s3.amazonaws.com/'rgi-documents'/65574f946a8dde120d00a616959abd1f00591326.pdf
  @HumairaP The DB record does not include source URL. Hence ask the researcher to provide the file, please

**Comment by gjacovella** [comment]
Timor Leste
Q. 15  Interim Petroleum Mining Code for Joint Petroleum Development Area (the document is available at: http://www.anp-tl.org/webs/anptlweb.nsf/vwAll/Resource-Interim%20Petroleum%20Mining%20Code/$File/JPDA%20Interim%20PMC%202%20April%2003.pdf)
- [x] https://s3.amazonaws.com/rgi-documents/8f567ac61fbbc1ae1c4ca772ff45ba23f831c31a.pdf?openelement

**Comment by gjacovella** [comment]
Madagascar
Q. 50 2016 General Tax Code (but I can open this document in other questions), 
- [x] https://s3.amazonaws.com/rgi-documents/aae2f489f3aa7e93ef38de9785756a90455d2203.pdf)
  works for me
- [x] https://s3.amazonaws.com/'rgi-documents'/f2250661d0259b4d0b7b523c17bd45bbc55e2f54.pdf
  available now on https://s3.amazonaws.com/rgi-documents/f2250661d0259b4d0b7b523c17bd45bbc55e2f54.pdf

**Comment by HumairaP** [comment]
Libya Q152:
- [ ] https://s3.amazonaws.com/'rgi-documents'/dbfa93c2d74f30635bd28ffd6ac78b7ccb505fa0.pdf
  source required

**Comment by gjacovella** [comment]
Chad
Q 50 General Tax Code (I will ask the researcher to provide the original)
- [ ] https://s3.amazonaws.com/'rgi-documents'/7acc685f39744c5131a6eaa043fc84912f970eab.pdf
  source required
  @alexander-elgin [General Tax Code 2006.pdf](https://github.com/NRGI/rgi-assessment-tool/files/432139/General.Tax.Code.2006.pdf)

**Comment by gjacovella** [comment]
Guinea
Q. 114 The missing source that I can't open is the same document that the researcher has provided for other questions (working link: https://s3.amazonaws.com/rgi-documents/775fe2741f0e16a1d243e214a9655efadd5c4338.pdf)
- [x] https://s3.amazonaws.com/'rgi-documents'/586f3e6f327f604ba18f5ccf56a3504214feddcd.pdf
  FIXED. I've changed the URL to https://s3.amazonaws.com/rgi-documents/586f3e6f327f604ba18f5ccf56a3504214feddcd.pdf

**Comment by gjacovella** [comment]
Morocco 
Q. 58 (I need to ask the R to provide the document)
- [x] https://s3.amazonaws.com/rgi-documents/3e4d51e6868ec29da75e20b7f767e60b389d0475.pdf?MOD=AJPERES

**Comment by alexander-elgin** [comment]
All corrupted files are reported in https://github.com/NRGI/rgi-assessment-tool/issues/538, https://github.com/NRGI/rgi-assessment-tool/issues/539 and https://github.com/NRGI/rgi-assessment-tool/issues/540
