### ISSUE TITLE
Add function to snapshot web reference

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#49]
a user should submit a website and fire off a screen capture of said website using something like node-webshot.

**Comment by byndcivilization** [comment]
This needs the ability to create a pdf or png full page capture of a webpage. this is a possible node madule for it:
https://www.npmjs.com/package/url-to-screenshot

**Comment by alexander-elgin** [comment]
Where should I store the snapshot files?

**Comment by byndcivilization** [comment]
Webpage snapshots should be handled in the same way as document uploads. File goes to s3 and data goes to document collection. This is already partially implemented in that Web upload requires a user to upload a PDF or perhaps g snapshot to initiate a Web citation.

**Comment by alexander-elgin** [comment]
See https://github.com/NRGI/rgi-assessment-tool/pull/236. Make sure you have a working installation of [phantomjs](http://phantomjs.org/) in your $PATH

**Comment by byndcivilization** [comment]
code from alex and new docker file should handle this.
