### ISSUE TITLE
The peer reviewer is required to provide justification and evidence even when the PR agrees with the researcher

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#491]
This is happening to the PR for Australia. She also mentioned that: "Some answers would let me complete, whereas other want justification and a document in support. I have saved those."

@byndcivilization @DianaHartmann

**Comment by DianaHartmann** [comment]
![image](https://cloud.githubusercontent.com/assets/16593022/15972494/b344b000-2f36-11e6-8f0a-5abc6ce46753.png)

**Comment by DianaHartmann** [comment]
![image](https://cloud.githubusercontent.com/assets/16593022/15972724/05c43d2c-2f38-11e6-864f-b33364bc9769.png)

**Comment by alexander-elgin** [comment]
If a reviewer selects the same answer as the researcher did no reference either justification is required, right?

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/494
