### ISSUE TITLE
Tool shows that the researcher has not selected an answer - however the R has done so and has uploaded evidence.

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#501]
![image](https://cloud.githubusercontent.com/assets/17277178/16738255/d4b2abd4-478c-11e6-8e77-5b38c8c71c30.png)

![image](https://cloud.githubusercontent.com/assets/17277178/16738278/f17eac4a-478c-11e6-8796-0a193b869ae4.png)

**Comment by HumairaP** [comment]
This is for two questions in the Yemen assessment - precept 6 - Q101 and Q105.

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/16738430/8a44a0f6-478d-11e6-8375-74842aa198f5.png)

![image](https://cloud.githubusercontent.com/assets/17277178/16738441/94b04c2a-478d-11e6-9263-69e965b5aa98.png)

**Comment by HumairaP** [comment]
The same issue has come up on the Uganda assessment: http://rgi.nrgi-assessment.org/admin/assessments-admin/answer/UG-2016-HY-088

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/19077016/cfe68e1a-8a42-11e6-835c-efd58b5a6c39.png)

**Comment by HumairaP** [comment]
![image](https://cloud.githubusercontent.com/assets/17277178/19077027/d8cf262c-8a42-11e6-9e54-b279bd73b9e4.png)

**Comment by alexander-elgin** [comment]
@HumairaP May I contact the researcher (Ronald B.) directly by email to get more details?

**Comment by HumairaP** [comment]
@alexander-elgin is it necessary to contact the researcher? The answer history page shows that the question was answered.

**Comment by alexander-elgin** [comment]
@HumairaP It is not the first time when the issue occurs. However we still do not know what causes the issue. We cannot even reproduce it. I would like to collect more info e.g.
1. Name and version of the browser
2. What's the exact behavior of the tool? Does the user see an error message or everything works as it should work, the user sees a success message but the answer data are not saved?
3. Was any special actions performed with the answer?

**Comment by HumairaP** [comment]
@alexander-elgin This sounds good. Please note that the work was completed in late May/early June. Perhaps an older version of a browser was used then. 

I did not see any user error message when working on this question.

**Comment by alexander-elgin** [comment]
@DianaHartmann reported that the reviewer of the `LR-2016-MI` assessment encountered the same issue.

**Comment by alexander-elgin** [comment]
The issue disappears on the page reload

**Comment by alexander-elgin** [comment]
It is required to put logs transferring data to the log server (Slack) to understand what going on is underline

**Comment by alexander-elgin** [comment]
How to reproduce the issue
1. Open an answer without any references
2. Create a reference
3. STAYING ON THE PAGE (do not reload the page, do not navigate to another page)
   1. Select a score
   2. Write a justification
   3. Submit the answer
