### ISSUE TITLE
Q. 38.3 is not showing up the options (a, b, c, d) even though the options are there

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#502]
@alexander-elgin 

assessment
![image](https://cloud.githubusercontent.com/assets/16593022/16776735/ac4fceb0-485e-11e6-95f4-86e66a45466e.png)

Questions Adm
![image](https://cloud.githubusercontent.com/assets/16593022/16776758/c1b43386-485e-11e6-82b7-2bab53f30e63.png)

**Comment by alexander-elgin** [comment]
@DianaHartmann That's because of the duplicated letters in the last two options. I've changed the letter of the last option to `e`. It works properly now. I'll add validation to prevent duplicated values of the letters.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/503
