### ISSUE TITLE
Problems: Incorrect Document Filtering by Assessment

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#504]
@byndcivilization @alexander-elgin 

I'm having problems editing references. I can't get access to the documents. I’ve been filtering by type of assessment or by consultant name.

Google chrome
![image](https://cloud.githubusercontent.com/assets/16593022/16812097/82a39770-4923-11e6-8c79-022d69755e26.png)

![image](https://cloud.githubusercontent.com/assets/16593022/16812134/aae1d9c2-4923-11e6-8910-fef0e66647db.png)

Firefox
![image](https://cloud.githubusercontent.com/assets/16593022/16812113/9a546a52-4923-11e6-8d77-fffafcdfcbe6.png)

![image](https://cloud.githubusercontent.com/assets/16593022/16812148/b44e5238-4923-11e6-90ee-dfc6e5b08b9d.png)

**Comment by alexander-elgin** [comment]
I can filter the documents by assessment
![filter-document-list-by-assessment](https://cloud.githubusercontent.com/assets/1811689/16836332/e1c18738-49de-11e6-87b8-787bf877356e.png)
or by a keyword
![filtered-document-list](https://cloud.githubusercontent.com/assets/1811689/16836396/2be4b56a-49df-11e6-9eac-ea316f852bf8.png)
then I can navigate to the 'Edit Document' page
![edit-document](https://cloud.githubusercontent.com/assets/1811689/16836366/0555a6b6-49df-11e6-8337-e21b63074a10.png)

**Comment by DianaHartmann** [comment]
@alexander-elgin. When I filter the documents by assessment. It mix the documents

![image](https://cloud.githubusercontent.com/assets/16593022/16836770/1f9a6520-49b7-11e6-8575-0c0ca84a5053.png)

**Comment by gjacovella** [comment]
![image](https://cloud.githubusercontent.com/assets/16592996/16836886/dff98f80-49b7-11e6-8217-a313ad7bdee4.png)
Same here

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/505
