### ISSUE TITLE
"Mark as unresolved" option for the flags in the peer reviewed assessments

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#506]
We can mark flags as "unresolved" when we move the assessment from the researcher to the peer reviewer, but we can't mark as unresolved the flags that we want to pass to the researcher after the peer reviewer's review.
![image](https://cloud.githubusercontent.com/assets/16592996/17245440/610cda7e-557e-11e6-9ee7-a9e5bcf686c8.png)
We have the "mark unresolved" option when we review the assessment sent by the researcher, so that we can move these flags to the peer reviewer.

![image](https://cloud.githubusercontent.com/assets/16592996/17245407/3f906b9a-557e-11e6-83c3-5b6238911ac3.png)
We don't have the "mark unresolved" option when we review the assessment sent by the peer reviewer, so we can't move the flags back to the researcher.

**Comment by alexander-elgin** [comment]
Originally the button 'Mark as Unresolved' was shown for assessments with status `resubmitted` and `under review`. In https://github.com/NRGI/rgi-assessment-tool/pull/507 I added the status `reviewer assigned` to the list. @gjacovella Are there any other statuses to include into the list?
