### ISSUE TITLE
Can't delete reference I have added

### ISSUE THREAD

**Issue by sgautvik** [NRGI/rgi-assessment-tool#508]
I need to delete a piece of dummy evidence I have added to the Botswana assessment (Q15), but the delete and edit reference buttons are inactive.

![image](https://cloud.githubusercontent.com/assets/19529874/17293100/1bb61e44-57e6-11e6-81cc-764e33703c5b.png)

**Comment by alexander-elgin** [comment]
@sgautvik You cannot delete the only reference (attached by you) unless you provide another one

**Comment by sgautvik** [comment]
Ok, I didn't realise it was user specific. Is this something we can change? So that it requires only one reference, regardless of who has uploaded it? We are attaching dummy evidence to ensure peer reviewers are checking the references properly, and need to be able to remove them once the review is done.

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/509
