### ISSUE TITLE
Delete references from previous researchers

### ISSUE THREAD

**Issue by DianaHartmann** [NRGI/rgi-assessment-tool#510]
@alexander-elgin. I can't delete references from researchers that are not longer in the project. I need to clean the assessment so it would be useful if you have a look at this issue. Thanks

**Comment by alexander-elgin** [comment]
@DianaHartmann The task is to allow the supervisor to delete the researcher references, right? 
@alexander-elgin Yes

**Comment by alexander-elgin** [comment]
The feature is implemented in https://github.com/NRGI/rgi-assessment-tool/pull/511. Once the deployment fixed it will be applied to the production server
