### ISSUE TITLE
Delete reference button inactive

### ISSUE THREAD

**Issue by sgautvik** [NRGI/rgi-assessment-tool#526]
The delete and edit reference buttons are inactive. They seem to become active for a short while, and then they revert back to being inactive. This is happening across all the supervisors accounts, and across assessments as well. For any given assessment (I have been checking Sierra Leone today), some delete buttons are active, while others are not. Some where only one reference is provided are active, while other questions with a single reference are inactive. 

![image](https://cloud.githubusercontent.com/assets/19529874/18003624/c86b62b2-6b86-11e6-9201-bfef67591a0e.png)

![image](https://cloud.githubusercontent.com/assets/19529874/18003633/d677e0f6-6b86-11e6-9f74-ac2365623e76.png)

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/528

**Comment by DianaHartmann** [comment]
@alexander-elgin. Hi Alex I ned to delete and the delete reference button is not active. Could you please help me?
