### ISSUE TITLE
Can we change the word limitation of the justification box from 1000 to 350 words?

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#527]

**Comment by alexander-elgin** [comment]
@ahasemann At the moment justification is restricted by 4000 characters (not words). Do you like to restrict it by words number or it is enough to decrease the characters number restriction to e.g. 1350 characters?

**Comment by alexander-elgin** [comment]
I've restricted length of the justification fields up to 1350 characters in https://github.com/NRGI/rgi-assessment-tool/pull/529

**Comment by DianaHartmann** [comment]
@alexander-elgin. Coul you please add characters? We need 2000 characters.

**Comment by HumairaP** [comment]
@alexander-elgin Could you please increase the character limit to 4000 for the time being? Thank you.
