### ISSUE TITLE
Questions jump regularly. 

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#530]
Sometimes they jump to the last question when you press the "next" arrow and other times, they jump back to the assessment page with all the precepts on it.

**Comment by alexander-elgin** [comment]
@HumairaP Once you complete an answer in a trial assessment you'll be navigated to the assessment details page. That's correct behavior for trial assessments only. Did you encounter such behavior in full assessments?

**Comment by HumairaP** [comment]
@alexander-elgin Yes, this occurred in full assessments. It has not happened for a few days now but it happens every now and again.

**Comment by alexander-elgin** [comment]
@HumairaP I cannot reproduce the issue in the reported assessment (see http://rgi.nrgi-assessment.org/admin/assessments-admin/AE-2016-HY).

**Comment by DianaHartmann** [comment]
@alexander-elgin. This is still happening in full assessments.
