### ISSUE TITLE
Ghana (hydrocarbons)

### ISSUE THREAD

**Issue by sgautvik** [NRGI/rgi-assessment-tool#531]
The Ghana (H) assessment is acting very strangely. The researcher (as you'll know) has been having issues with entering justifications and adding references, and also, when we first launched the peer review the assessment went straight to the full questionnaire, not just the 10 trial questions. We had to manually revert back to the trial questions, but now when I open the assessment I see that several of the questions in the trial have been marked as approved, without the researcher completing and submitting.

Could you have a look and see if there is something going on with this assessment/the tool? There seems to be a lot of issues occurring and we cannot see a reason for it as it has been treated the same as all the others.

This is the assessment now, the first time I have accessed it since I launched the peer reviewers trial. I have not opened any of the questions before, so I do not understand why they are marked as approved.

![image](https://cloud.githubusercontent.com/assets/19529874/18210462/81b94096-7130-11e6-82b7-9ad78118b5ea.png)

**Comment by alexander-elgin** [comment]
@sgautvik In the assessment http://rgi.nrgi-assessment.org/admin/assessments-admin/GH-2016-HY every answer has score and score history. All answers have the same status `Needs review`.
