### ISSUE TITLE
deleting for comments and flags

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#58]
It might be useful for users to delete comments and flags. This will require some version control since we don't want to loose data unless necessary.

**Comment by byndcivilization** [comment]
edits implmented...still need to do deletes. @jimc33 do you have any methodology/transparency problems with authors being able to delete their comments/flags?

**Comment by byndcivilization** [comment]
I'm less worried about this since we are versioning answers now.

**Comment by jimc33** [comment]
Ok- if versioning answers that sounds ok (and we as the RGI team can retrieve/view the deleted comments if necessary)

**Comment by byndcivilization** [comment]
moved to issue #141
