### ISSUE TITLE
Dependant question model

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#88]
Some questions will need to only appear based on previously answered questinon. This is likely addressed by pending pull but will check.

**Comment by byndcivilization** [comment]
Lets start from scratch here:
- Don't worry about the Admin UI for assigning dependant questions as they will be fed in this way and wont likely change
- Data fields
  - there is a field in the question model, "question_dependancies" which is a place to start, its an array that contains _id of the questions depenant on this answer
  - there is also a field called question_dependancies_trigger that currently holds a string. go ahead and change this if you need to.
- Behaviour
  - When a parent question hasn't been answered, the dependant questions should be skipped. They should not appear in the assessment-detail page and should not be navigated to when the next button is clicked.
  - when a parent question has been answered with a trigger (i.e. selection a, selection b, etc from the radio buttons), the child questions should still not appear, however, the parent question should propagate a predetermined answer out the the answers corresponding to the child answers. Answers should also be set to submitted. Again this does not mean that researchers, reviewers or external reviewers should be able to see the answers.
  - When a parent question has been answered but not with a trigger answer, the child questions should be available and necessary for the researcher to answer.

**Comment by alexander-elgin** [comment]
See https://github.com/NRGI/rgi-assessment-tool/pull/235

**Comment by alexander-elgin** [comment]
See https://github.com/NRGI/rgi-assessment-tool/pull/378
