### ISSUE TITLE
draggable flag

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#91]
When flagging an answer an admin needs the flag dlalog to be moved. This requires a move from redactor to text angular. This is likely addressed in pending pull. Will check

implemented except for two bugs:
- [x] disabled textAngular control bar
- [x] scroll bar follows dialog

**Comment by byndcivilization** [comment]
implemented except for two bugs:
- [ ] disabled textAngular control bar
- [ ] scroll bar follows dialog

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/116

**Comment by alexander-elgin** [comment]
https://github.com/NRGI/rgi-assessment-tool/pull/117
