### ISSUE TITLE
Clear Dropdown for new ref.

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#97]
After uploading, e.g., a document, cannot directly upload another document. Need to switch to either ‘Add a webpage’ or ‘add interview’ for the pop up menu to work

**Comment by byndcivilization** [comment]
Uses $reload as immediate fix but needs a better solution. Issue is that the dlalog does not have access to $parent element where the ref drop down is contained.

**Comment by byndcivilization** [comment]
@alexander-elgin do you know the right way to do this?

**Comment by alexander-elgin** [comment]
`$route.reload` is a bad approach because the state of the page e.g. modified input / textarea content will be lost. I've fixed it easily using `$rootScope.$broadcast` and `$rootScope.$on`
